- panel/panels.py
The HTML object didn't follow the naming convention of the other Panel objects, and the PanelBase error message stripped off the last 5 characters of the class name when reporting issues, leaving this name with nothing in it. Renamed to HTMLPanel to match the other objects, so that the error message correctly reports that it expects HTML objects.
> Renamed HTML to fix error message

- panel/panels.py
HTMLPanel works well, but it doesn't seem to allot any space for the actual object being shown:
```
import numpy as np, pandas as pd, datashader as ds
from datashader import transfer_functions as tf
from datashader.colors import inferno, viridis
from numba import jit
from colorcet import fire
@jit
def clifford_trajectory(a, b, c, d, x0, y0, n):
xs, ys = np.zeros(n), np.zeros(n)
xs[0], ys[0] = x0, y0
for i in np.arange(n-1):
xs[i+1] = np.sin(a * ys[i]) + c * np.cos(a * xs[i])
ys[i+1] = np.sin(b * xs[i]) + d * np.cos(b * ys[i])
return pd.DataFrame(dict(x=xs,y=ys))
def clifford_plot(a, b, c, d, n=10000000, cmap=fire[::-1]):
cvs = ds.Canvas(plot_width=400, plot_height=400)
agg = cvs.points(clifford_trajectory(a, b, c, d, 0, 0, n), 'x', 'y')
return tf.shade(agg, cmap=cmap)
```
```
from panel …
```
> Added optional height and width to HTMLPanel

- .travis.yml
- README.md
- panel/layout.py
- panel/panels.py
- panel/param.py
- panel/tests/test_layout.py
- panel/tests/test_param.py
- panel/tests/test_widgets.py
- panel/util.py
- panel/viewable.py
- panel/widgets.py
- setup.py
- tox.ini
> More dynamic ParamPanel and more widgets

- codecov.yml
- panel/panes.py
- panel/tests/fixtures.py
- panel/tests/test_panes.py
- panel/tests/test_util.py
- panel/util.py
- setup.py
> Cleaned up Panes and added tests

- panel/__init__.py
- panel/models/plotly.ts
- panel/panes.py
- panel/param.py
- panel/plotly.py
- panel/tests/test_layout.py
- panel/tests/test_panes.py
- panel/tests/test_param.py
- panel/tests/test_plotly.py
> Gave panes simpler names

- panel/pane.py
- panel/tests/test_layout.py
- panel/tests/test_panes.py
When raw bokeh widgets (of which ``Div`` is one example) are laid out in a Row or Column some strange sizing issues can occur. This can be prevented by wrapping these models in a `WidgetBox`, which is what I've done here.
This additional nesting is quite annoying, particularly as you can see when looking at the tests. The layout work that's currently happening in bokeh promises to get rid of WidgetBox types, which hopefully means all this mess will disappear and the majority of this PR can be reverted once that happens.
> Wrap raw bokeh model widgets in WidgetBox

- panel/pane.py
- panel/tests/test_panes.py
- panel/util.py
Makes the handling of Div and widget bokeh models more consistent by always wrapping them in a widget box, which inherits width/height/sizing_mode from the model.
> Always wrap Div and widgets in WidgetBox

- panel/pane.py
- panel/param.py
- panel/plotly.py
- panel/tests/test_panes.py
@jlstevens suggested we add support for a string-based representation for any Python object as a Pane.  About 20 minutes after his suggestion, I already realized that I needed that, so here it is.
Adding the Repr class is the only change; the other diffs are just to reorganize the other classes to be in a more readable order.
Questions:
> Add String pane to support any representable object

- .travis.yml
- panel/models/plotly.ts
- panel/models/vega.ts
- panel/tests/test_plotly.py
- panel/tests/test_vega.py
- panel/vega.py
Adds support for rendering vega specs and altair charts. Just like the plotly renderer, the embedded data is synced using ColumnDataSources, which means binary transport is supported.
> Add support for rendering Vega and altair plots

- panel/pane.py
The [yt](https://yt-project.org/) library uses Matplotlib to render one or more plots per object to PNG.  Although yt objects have a `_repr_html_` and can thus be displayed without any special support, the enclosing Bokeh Div does not resize appropriately to the size of the contents, which is very inconvenient.  This PR adds a pane.YT class that is the same as pane.HTML except that it calculates the total height (of all stacked PNGs) and the maximum width (of all stacked PNGs) and uses those to size the Div.  This implementation is somewhat inefficient, in that it renders the images to PNG just to get their sizes, but doing so seemed simpler than trying to parse them out of the HTML representation to find out their sizes.  Example:
```
try:
import yt
except:
!conda install -c conda-forge …
```
> Added yt support

- .travis.yml
As far as I know, there should be no reason to use nbsite master any more, since the released version has caught up (and releases can be generated by tagging, so shouldn't fall behind again).
Also, fixed an 'ioam' reference (download notebook links).
(Note: I think the recent release of sphinx 1.8 might have broken nbsite, but that's an unrelated issue I'll try to fix asap...)
> Use released nbsite package

- panel/pane.py
- panel/param.py
Ensures that number parameters without bounds are editable as literals and that string parameters use a regular ``TextInput`` widget.
> Uneditable params

- MANIFEST.in
- conda.recipe/meta.yaml
- setup.py
Some things I just happened to notice:
* fix summary on anaconda.org (is currently 'Bidirectional communication for PyViz')
* include ts files in sdist (currently they're missed, although it doesn't really matter yet since we don't yet put a package on pypi)
> Minor packaging fixups

- panel/pane.py
Decorated parameterized methods used as a ``Pane`` may now listen to subobject parameters. Together with https://github.com/ioam/param/pull/264 it is now also possible to listen to all subobject parameters by using ``param.depends('subobject.param')``.
> Add support for listening to subobject dependencies

- panel/param.py
- panel/tests/test_widgets.py
- panel/widgets.py
Selector widgets currently need to do a reverse lookup on object identity, which requires that objects be hashable, which Bokeh palettes (as lists) are not.  This PR and a [matching PR on param](https://github.com/ioam/param/pull/268) converts lists to tuples when doing lookups, which works:
```
import panel as pp
from colorcet import kbc, fire
pp.extension()
def fn(a=1.7, cmap=kbc):
return a,cmap[0]
pp.interact(fn, cmap=[kbc,fire])
```
```
import param
class C(param.Parameterized):
a = param.Number(1.7, bounds=(-2, 2))
cmap = param.ObjectSelector(kbc,[kbc,fire])
def view(self):
return self.a, self.cmap[0]
c=C()
pp.Row(c.param,c.view)
```
However, note that in both cases the representation of the list is vastly larger than the widget box, which in the second example ends before `(2, …
> Added support for selecting lists and dicts

- panel/pane.py
Adds a dpi parameter that scales the resolution but not the displayed size of the image.
> Add control over Matplotlib pane dpi

- examples/user_guide/Widgets.ipynb
- panel/param.py
- panel/tests/test_widgets.py
- panel/widgets.py
Allows entering a datetime as a string providing control over the ``format`` and the bounds.
> Added DatetimeInput widget

- .travis.yml
Means panel will keep using the same version of pyctdev that it's using currently, rather than some potentially disruptive dev releases before the next main release.
> Switch to pyviz main channel for pyctdev on CI

- panel/pane.py
- panel/tests/test_panes.py
This PR allows the HoloViews pane to display widgets for a DynamicMap and HoloMap. By default the display will match the HoloViews behavior but by setting ``show_widgets=False`` the widgets may be laid out manually:
Additionally it also allows overriding the default widgets with a custom widget instance:
> Implemented support for HoloViews widgets

- panel/pane.py
- panel/tests/test_panes.py
Adds an SVG pane, unlike other image types the size and/or aspect ratio of the SVG cannot be easily computed ahead of time, but it still seems default to its native size unless explicitly overridden.
> Added SVG Pane

- panel/pane.py
- panel/tests/test_panes.py
- setup.py
The ``Markdown`` pane renders to HTML using the markdown python library. It has a precedence of None which means it will never be used automatically, therefore a user has to explicitly wrap their markdown formatted text in a ``Markdown`` pane.
> Add Markdown pane

- panel/pane.py
- panel/tests/test_panes.py
- setup.py
Accepts LaTeX strings and objects with `_repr_latex_`, such as `IPython.display.Latex`:
```
from panel import pane
from IPython.display import Latex
pn.Row(pane.LaTeX(r'$\frac{x}{y^2}$'), Latex(r'$\frac{x}{y^2}$'))
```
Uses Matplotlib to render to a PNG and Pillow to crop it and make it transparent.  Could also consider using MathJax to create true (non-image) equations, but that would require a custom Bokeh model to get the JavaScript required.
> Added PNG/Matplotlib-based LaTeX pane

- panel/layout.py
- panel/pane.py
Sympy Expr objects have a `.latex()` method for generating a LaTeX-syntax version of the expression, so it's simple to add support to pane.LaTeX for them:
```
import sympy
x = sympy.symbols('x')
i = sympy.integrate(sympy.sin(x**2), (x, -sympy.oo, sympy.oo))
pn.Row(x, pn.Spacer(width=-150), i, pn.Spacer(width=30), sympy.sin(x**2)) 
```
Other changes:
- As the spacing is still unpredictable, which I think is unrelated to LaTeX, I also allowed Spacer to accept negative widths and heights to let things be lined up properly.
- The error message when explicitly instantiating a pane with an unallowed object was still trimming off the last 5 characters (P,a,n,e,l) despite the long-ago renaming, so I fixed that.
> Add support for Sympy objects to pane.LaTeX

- panel/interact.py
- panel/param.py
When a ParamMethod pane or interact pane updates a plot without replacing the model entirely the internal state of the callback needs to be updated to keep track of the current models. On bokeh server this update to the state needs to be scheduled on the event loop rather than executing it immediately.
> Ensure that model state is updated inside interact and Params

- panel/pane.py
Pandas dataframes have both `_repr_latex_` and `_repr_html_` methods, but pane.LaTeX can only handle equations, not full LaTeX tables, so we need to use pane.HTML instead.  In general pane.HTML is more general in its support than pane.LaTeX, so it makes sense to prefer pane.HTML.
> Reduced LaTeX pane priority so it is a last resort

- panel/param.py
- panel/tests/test_param.py
Allows a Params widget to be hidden and shown again by setting a precedence below the display threshold.
> Allow hiding Params widget by setting negative precedence dynamically

- examples/user_guide/Widgets.ipynb
- panel/holoviews.py
- panel/models/player.ts
- panel/models/widgets.py
- panel/tests/test_holoviews.py
- panel/viewable.py
- panel/widgets.py
This PR adds a custom bokeh model which replicates the "scrubber" style widget from HoloViews.
Unlike the HoloViews version this one is fully dynamic and the state can be controlled from Python.
Also implements support for using the widget on HoloViews plots:
> Implement Player widget

- examples/user_guide/Panes.ipynb
- panel/__init__.py
- panel/holoviews.py
- panel/interact.py
- panel/layout.py
- panel/models/vega.ts
- panel/pane.py
- panel/param.py
- panel/plotly.py
- panel/tests/test_holoviews.py
- panel/tests/test_interact.py
- panel/tests/test_layout.py
- panel/tests/test_param.py
- panel/tests/test_vega.py
@jbednar Please test this extensively.
> Add pn.panel and ensure all Panes have layout attribute

- panel/layout.py
- panel/pane.py
- panel/param.py
- panel/tests/test_layout.py
- panel/tests/test_panes.py
- panel/tests/test_param.py
- panel/tests/test_util.py
- panel/tests/test_widgets.py
- panel/util.py
- panel/viewable.py
An initial implementation of compositional reprs, which can be improved later.
Some sample outputs for moderately complex dashboards include:
```
Row(
HTML(str, width=200),
Spacer(width=30),
ParamMethod(method),
Spacer(width=50),
Column(
Param(ParameterSets, name='Attractors', width=220),
Param(Attractors, expand=True, name='Options', width=220)
)
)
```
```
Column(
Row(
Markdown(str, width=170),
Spacer(width=50),
Column(
Markdown(str, height=25, width=400),
Spacer(height=-15),
Markdown(str, width=500)
),
Spacer(width=180),
Column(
HoloViews(DynamicMap),
Button(name='Clear selection'),
Spacer(height=-15)
),
Markdown(str, width=80)
),
Spacer(height=-50),
Row(
HoloViews(DynamicMap),
HoloViews(DynamicMap)
),
Row(
HoloViews(DynamicMap),
HoloViews(DynamicMap)
)
)
```
> Add compositional reprs

- panel/cli.py
- panel/tests/test_cli.py
This PR helps transform arguments that may be passed to the `panel` console script that would not be accepted by bokeh without transformation.
> Transform command-line arguments passed by anaconda project

- panel/interact.py
- panel/layout.py
- panel/pane.py
- panel/param.py
- panel/tests/test_interact.py
- panel/util.py
- panel/viewable.py
The interactive layout was previously self-referential which causes issues when trying to display the plot/display component on its own. Additionally this ensures that a small fixes to assign a minimal height when no height is specified for the last item in a Column.
> Interactive layout fixes

- panel/interact.py
- panel/layout.py
> Better handling of layout changes

- panel/util.py
Avoids warnings when exporting the plot to a static file.
> Do not make bokeh instantiate a Comm

- panel/cli.py
- setup.py
Addresses #109. It isn't obvious how to do the right thing here but this seems to me like the easiest way to splice together two external parsers. It does mean if you mistype 'serve', then it is the pyct parser that will complain.
> Extended parser to support pyct commands

- panel/tests/test_widgets.py
- panel/widgets.py
> ToogleButtons : fix bug on empty list value

- examples/user_guide/Widgets.ipynb
- panel/models/fileinput.ts
- panel/models/widgets.py
- panel/tests/test_widgets.py
- panel/widgets.py
Allows uploading a file which can be accessed from Python as a bytestring.
@xavArtley I believe you said you wanted this. If you have a minute I'd appreciate it if you could test it a bit and see if there's anything you think that should be added/fixed.
> Add FileInput widget

- panel/models/player.ts
- panel/tests/test_models.py
Fix #208
Ensure windows compatibility
A simple test which failed on windows was trying to open().read() player.ts file
> Replace special charactere of player.ts by their unicode equivalent

- panel/models/audio.ts
- panel/models/widgets.py
- panel/widgets.py
Add ``Audio`` bokeh model and panel widget. The widget provides bidirectional control over:
* time
* volume
* pause/play state
* loop state
> Added Audio model and widget

- examples/user_guide/Pipelines.ipynb
- panel/pipeline.py
> Pipeline enhancements

- panel/links.py
- panel/tests/test_links.py
Ensures that setting an invalid property does not break JS links.
> Guard JS link property setter

- panel/holoviews.py
- panel/pane.py
- panel/param.py
- panel/plotly.py
- panel/tests/test_pipeline.py
- panel/vega.py
PR title says it all. I find using `precedence` for panes horribly confusing:
1) Panel uses parameters with defined precedence internally.
2) Panel sorts on parameter precedence when building widgets for parameterized objects.
3) Panel applies panes according to its own notion of precedence.
Now if you grep for `precedence`, you know that the only concept there relates to parameters.
> Renamed precedence to priority and deleted trailing whitespace

- panel/param.py
Since Python dictionaries preserve order since 3.6 (and it became part of the CPython spec in 3.7), you no longer have to use parameter precedence to order your widgets as they can appear in definition order. This PR implements this behavior for Python 3.6+.
> Use parameter definition order for Python 3.6+

- doc/index.rst
- examples/user_guide/Introduction.ipynb
The Installation section on http://panel.pyviz.org was being formatted at the wrong level:
Also cleaned up some wording and clarified in the intro that there are three completely different ways of using Panel, and that users should pick one of them for any particular application.
> Minor fixes to docs and website

- panel/layout.py
- panel/tests/test_reactive.py
- panel/tests/test_widgets.py
- panel/viewable.py
- panel/widgets.py
This PR forces a fixed height to be respected if specified either by setting sizing_mode='fixed' or by setting the corresponding `min_width` or `min_height` property at the same time.
Fixes https://github.com/pyviz/panel/issues/23
> Improved behavior for fixed widths and heights

- panel/__init__.py
- panel/holoviews.py
- panel/layout.py
- panel/pane.py
- panel/util.py
- panel/viewable.py
- panel/widgets.py
Fixes https://github.com/pyviz/panel/issues/138
Fixes https://github.com/pyviz/panel/issues/181
> Improved bokeh server functionality

- panel/holoviews.py
- panel/interact.py
- panel/layout.py
- panel/pane.py
- panel/param.py
- panel/plotly.py
- panel/tests/test_interact.py
- panel/tests/test_layout.py
- panel/tests/test_panes.py
- panel/tests/test_param.py
- panel/tests/test_plotly.py
- panel/tests/test_vega.py
- panel/tests/test_widgets.py
- panel/vega.py
- panel/widgets.py
This PR tries to minimize the amount of nesting widgets and panes use, i.e. objects that can be updated inplace do not need to be nested inside a container. Only objects where the bokeh model is not well defined and therefore may need to be replaced entirely need to be nested. 
This makes testing simpler, makes the bokeh model structure match the panel structure more closely and makes things easier for bokeh's layouts.
> Refactor model and root handling

- panel/layout.py
- panel/plotly.py
- panel/tests/test_layout.py
- panel/tests/test_param.py
> Fix Tabs.append and Plotly.applies bugs

- panel/__init__.py
- panel/io.py
- panel/layout.py
- panel/models/plots.py
- panel/pane/base.py
- panel/pane/holoviews.py
- panel/tests/test_server.py
- panel/util.py
- panel/viewable.py
This PR refactors the server handling such that all existing methods that start a bokeh server simply call the new ``Viewable.get_server`` method and then publish the server session in different ways. This also means that we now take full control over embedding servers inline in the notebook, which makes it possible to automatically clean up server sessions as cells are deleted or re-executed.
Depends on new versions of both the JLab extension and pyviz_comms: https://github.com/pyviz/pyviz_comms/pull/28
> Refactored server handling

- panel/layout.py
- panel/links.py
- panel/tests/test_layout.py
Closes #278  (adding `extend`) and adds `clear` and `reverse` as well. I think the only other missing list methods are copy, count, index, and sort of which only sort affects the list in-place. Sort doesn't work on most panel objects and probably doesn't make much sense (might later if we wanted to compare names or something).
> Adding some more list methods for layout and tests

- panel/param.py
- panel/viewable.py
The ``_expecting`` flag which was an attempt to ensure that events don't bounce around was not actually doing anything. Additionally the bi-directional link between a Parameterized and a widget was also not handled correctly and is now replaced by a ``_updating`` flag on the ``Param`` pane.
> Improved logic to avoid events boomeranging

- panel/param.py
- panel/tests/test_util.py
- panel/util.py
- setup.py
Now that https://github.com/pyviz/param/pull/319 is merged, there is no need for the label formatter in panel to format parameter names. Merging this PR will bump the param version requirements so I will update the pinning too.
> Param formatting via the new label property

- panel/tests/test_widgets.py
- panel/widgets/select.py
This fixes callbacks set on a MultiSelect widget which change the values. Due to the ordering of the watchers it can happen that the options change before the value change event has been propagated to the underlying bokeh model. Ideally we would have a way to elevate the precedence of watch calls which would allow us to order the watchers appropriately.
This PR simply addresses the symptom by skipping values that aren't found.
>  Fixed issue setting (Multi)Select value when options changed

- panel/pane/base.py
- panel/pane/holoviews.py
- panel/util.py
- panel/viewable.py
- panel/widgets/slider.py
Ensures that only the models that need it are updated across servers and notebook views.
Here is a demo of a bunch of synced views all updating each other:
> Ensure events do not bounce between server and client

- .appveyor.yml
- panel/io.py
- panel/models/state.py
- panel/models/state.ts
- panel/tests/fixtures.py
- panel/tests/test_io.py
- panel/viewable.py
- panel/widgets/base.py
- panel/widgets/button.py
- panel/widgets/input.py
- panel/widgets/select.py
- panel/widgets/slider.py
- setup.py
Makes it possible to export the embedded state to JSON files which can be loaded independently. Unlike the equivalent functionality in HoloViews each state is stored as a separate file which means it can be loaded only when it is needed, allowing a huge state space to be exported with a minimal file size penalty.
> Add support for saving and loading embedded data from JSON

- panel/param.py
- panel/tests/test_param.py
This is a bit of convenience to easily add single parameter widgets, i.e. this code:
```python
pn.pane.Param(parameterized, parameters=['parameter'], show_name=False)
```
becomes:
```python
pn.pane.Param(parameterized.param.parameter)
```
> Allow passing Parameter instances to Param pane

- panel/tests/test_widgets.py
- panel/util.py
- panel/widgets/player.py
- panel/widgets/select.py
Using a dictionary to map options from their value to their label did not work well because the values may be non-hashable or hash inconsistently. Instead this PR switches to using the value's identity to do the reverse mapping which should work reliably.
> Reverse map discrete options using identity

- panel/io.py
- panel/models/__init__.py
- panel/models/plotly.py
- panel/models/plotly.ts
- panel/models/vega.py
- panel/models/vega.ts
- panel/pane/base.py
- panel/pane/plotly.py
- panel/pane/vega.py
- panel/tests/test_plotly.py
- panel/tests/test_vega.py
- setup.py
Previously I used some horrible code to load plotly and vega dynamically when the models are used. Not only is this horrible, it also doesn't seem to work when exported in a notebook. This PR instead uses the ``__javascript__`` variable on the models, which loads vega and plotly js when the extension is loaded. To avoid it being loaded all the time these models are no longer imported by default, instead the corresponding Pane objects do the import dynamically. This works fine in server and commandline use cases but in the notebook the models need to be imported before the extension is run. Therefore I have added the ability to load these models via the extension, much like in holoviews. So you can now do ``pn.extension('vega')`` and it will load vega js in the notebook.
> Correctly load plotly and vega libraries

- doc/_templates/layout.html
- examples/gallery/panes/HoloViews.ipynb
- examples/gallery/panes/Plotly.ipynb
- examples/gallery/panes/Vega.ipynb
- panel/_templates/autoload_panel_js.js
- panel/io.py
- panel/models/katex.py
- panel/models/katex.ts
- panel/models/mathjax.py
- panel/models/mathjax.ts
- panel/models/plotly.py
- panel/models/plotly.ts
- panel/models/vega.py
- panel/models/vega.ts
- panel/pane/holoviews.py
- panel/pane/plotly.py
- panel/pane/vega.py
- panel/tests/test_holoviews.py
- panel/tests/test_plotly.py
This PR provides polish to all existing pane classes and then adds reference sections for each. I'll outline all the panes and the improvements made here:
* HoloViews
* Plotly
* Vega
> Improvements and Documentation for Panes

- examples/reference/panes/HTML.ipynb
- panel/models/__init__.py
- panel/models/html.ts
- panel/models/markup.py
- panel/models/widgets.py
- panel/pane/markup.py
- panel/pane/tests/test_markup.py
- panel/tests/test_server.py
This adds an HTML model which executes any script tags found inside of it. This makes it possible to execute arbitrary Javascript inside an ``HTML`` pane, and even allows embedding a panel inside an HTML pane. So if you really need it you can embed other panels or even bokeh servers inside a panel.
Implements https://github.com/pyviz/panel/issues/325
> Add HTML model capable of executing JS code

- examples/user_guide/Deploy_and_Export.ipynb
- panel/io/model.py
- panel/io/notebook.py
- panel/io/save.py
- panel/io/state.py
- panel/pane/base.py
- panel/pane/holoviews.py
- panel/pane/tests/test_base.py
- panel/pane/tests/test_equation.py
- panel/pane/tests/test_holoviews.py
- panel/pane/tests/test_image.py
- panel/pane/tests/test_markup.py
- panel/pane/tests/test_plot.py
- panel/pane/tests/test_plotly.py
- panel/pane/tests/test_vega.py
- panel/param.py
- panel/tests/test_interact.py
- panel/tests/test_io.py
- panel/tests/test_layout.py
- panel/tests/test_links.py
- panel/tests/test_param.py
- panel/viewable.py
- panel/widgets/tests/test_base.py
- panel/widgets/tests/test_button.py
- panel/widgets/tests/test_input.py
- panel/widgets/tests/test_player.py
- panel/widgets/tests/test_select.py
- panel/widgets/tests/test_slider.py
Addresses https://github.com/pyviz/panel/issues/294
> Expose curdoc and session_context when using serve

- .travis.yml
- examples/reference/panes/VTK.ipynb
- panel/models/vtk.py
- panel/models/vtk.ts
- panel/pane/tests/test_vtk.py
- panel/pane/vtk.py
- tox.ini
Does some refactoring for the VTK pane and adds some features:
* VTK pane now supports responsive sizing modes
* VTK pane now supports syncing (and therefore linking) camera state
@xavArtley, review would be appreciated but I'll probably merge some time tomorrow in any case.
@dharhas, it currently only supports uni-directional links between objects, which is something I need to think about and address in general, but you could now link multiple plots together and then interact with the plot they are linked to:
> Refactored and improved VTK model and pane [doc-build]

- .travis.yml
- doc/user_guide/index.rst
- examples/user_guide/Components.ipynb
- panel/__init__.py
- panel/layout.py
- panel/pane/image.py
- panel/pane/markup.py
- panel/tests/test_layout.py
- setup.py
- tox.ini
Implements a ``GridSpec`` layout based on the new GridBox model in bokeh. It works quite differently from the previous approach, you no longer have to declare the number of cols and rows, you simply declare a size (or sizing_mode='stretch_both') and then start filling the grid:
Supersedes https://github.com/pyviz/panel/pull/31
> Add GridSpec layout [doc-build]

- panel/io/server.py
- panel/links.py
- panel/models/vtk.ts
- panel/util.py
- panel/viewable.py
- panel/widgets/tests/test_select.py
> Various minor fixes

- examples/user_guide/Pipelines.ipynb
- panel/pipeline.py
> Improved Pipeline subway map styling

- panel/io/state.py
- panel/pane/base.py
- panel/pane/holoviews.py
- panel/viewable.py
Fixes #344 
@xavArtley Could you test this?
> Ensure that events are not launched from the wrong thread

- panel/pane/vtk.py
VTKjs currently only supports `vtkPolyData`. These changes use an extract geometry filter to get a useable representation of any VTK data object.
Note that these changes make creating compelling scenes with `vtki` a breeze!!
```py
import vtki
vtki.set_plot_theme('document')
from vtki import examples
import panel
panel.extension('vtk')
from panel.pane import VTK as panel_display
def display(p):
return panel_display(p.ren_win)
```
```py
data = examples.load_uniform()
p = vtki.Plotter(notebook=False, off_screen=True)
p.add_mesh(data.threshold_percent([0.25, 0.75]))
p.add_mesh(data.wireframe())
p.add_mesh(data.slice_orthogonal())
p.show(auto_close=False)
display(p)
```
```py
data = examples.download_st_helens().warp_by_scalar()
p = vtki.Plotter(notebook=False, off_screen=True) …
```
> Use extract geometry filter to enforce PolyData

- panel/models/vtk.ts
- panel/pane/vtk.py
fixes :  https://github.com/pyviz/panel/issues/350
However when renderding the vtkjs panel the texture does not appear unless an interaction is done
I tried to export the vtkjs file into the official scene explorer (https://kitware.github.io/vtk-js/examples/SceneExplorer.html) and the same issue arise
May be we need to open an issue on the main repo
> [vtk] correction of the texture serialization

- panel/param.py
Fixes https://github.com/pyviz/panel/issues/361
> Use Select widget for ObjectSelector

- panel/pane/vtk.py
There was a bug that would prevent scalars from being shown sometimes. This fixes it.
Here's code to see the difference (running off of `vtki` `master` branch - note there are several examples [here](https://mybinder.org/v2/gh/vtkiorg/vtki-examples/master) that show this happening):
```py
import vtki
vtki.set_plot_theme('doc')
sphere = vtki.Sphere(radius=3.14)
vectors = np.vstack((np.sin(sphere.points[:, 0]),
np.cos(sphere.points[:, 1]),
np.cos(sphere.points[:, 2]))).T
sphere.vectors = vectors*0.3
p = vtki.Plotter()
p.add_mesh(sphere.arrows, scalars='GlyphScale', color=None, lighting=False, stitle='Vector Magnitude')
p.add_mesh(sphere, color='grey', ambient=0.6, opacity=0.5, show_edges=False)
p.show()
```
> Fix get scalar array bug for VTK pane

- examples/reference/widgets/Spinner.ipynb
- panel/widgets/__init__.py
- panel/widgets/input.py
> add spinner widget

- panel/layout.py
This restores the behavior of Row/Column layouts that was present in bokeh 1.1.0rc2, which is for these layouts to expand to match the size of their largest contents.
> Set more sensible defaults for Row/Column size policies

- .travis.yml
- setup.py
Now that pyctdev uses `python setup.py develop --no-deps` in pyctdev, we no longer need to duplicate that line in the travis file.
> Getting rid of duplicate `python setup.py develop`

- panel/tests/test_docs.py
I thought it'd be useful to have a unit test that asserts that for every panel object (layout, widget, pane) there is a corresponding reference gallery entry.
Found that ToggleGroup, YT, and RGGPlot are missing. Allowing those ones to be missing for now.
> Adding tests to make sure the reference gallery is complete

- examples/reference/panes/Matplotlib.ipynb
- panel/pane/plot.py
https://github.com/pyviz/panel/issues/454
```
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
pn.extension()
fig = plt.figure(figsize=(8, 5))
ax = plt.axes()
im = ax.scatter([0, 1, 2], [3, 4, 5], c=[5, 6, 7])
ax.set_title('test')
ax.set_xlabel('someth', fontsize=40)
ax.set_ylabel('someth', fontsize=40)
divider = make_axes_locatable(ax)
cax = divider.append_axes("right", size="5%", pad=0.05)
cbar = plt.colorbar(im, label='colorbar', cax=ax)
plt.suptitle('somethingsomething loooong somethingsomething loooongsomethingsomething loooongsomethingsomething loooong')
pn.Pane(fig)
pn.Pane(fig, tight=True)
```
top is default render from Jupyter, second is wrapped fig with panel, and third is wrapped fig again but with tight
> Add tight option bbox

- panel/pane/vtk/vtk.py
- panel/pane/vtk/vtkjs_serializer.py
This PR improve the one to set a custom serializer for vtk RenderWindow (#409)
Here we can register serializer for different class not just the vtk RenderWindow wich is limitatting if as input of the serializer we have a custom class.
With this PR for example we can use the pyvista (#408) export function without major change in code:
```python
pn.extension('vtk')
import pyvista as pv
from pyvista import examples
mesh = examples.download_st_helens().warp_by_scalar()
p = pv.Plotter()
p.add_mesh(mesh)
def pyvista_serializer(plotter, delete_tmp_file=False):
filename = 'pyvista_tmp'
plotter.export_vtkjs(filename)
with open(filename + '.vtkjs', 'rb') as f:
vtkjs = f.read()
if delete_tmp_file:
import os
os.remove(filename + '.vtkjs')
return vtkjs …
```
> custom serializer registration improvement

- .travis.yml
- tox.ini
Not sure if this will work, but attempting to fix errors that have been cropping up in travis builds:
For instance in https://travis-ci.org/pyviz/panel/jobs/550370461:
```
0.03s$ pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
pyenv: version `3.6' is not installed (set by PYENV_VERSION environment variable)
The command "pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev" failed and exited with 1 during .
Your build has been stopped.
```
> Updating travis to python 3.7

- examples/getting_started/Introduction.ipynb
Might also want to consider rewording this last section, which was written before there was good reactive support and doesn't anticipate it much.  Maybe replace the separate API links with one link to the API section of the user guide?
> Fixed broken links

- panel/widgets/slider.py
Fixes https://github.com/pyviz/panel/issues/495
This small change gives the DateRangeSlider the same behavior as the DateSlider
> fixed DateRangeSlider crash

- panel/io/notebook.py
Closes https://github.com/pyviz/panel/issues/552.
The equality check in the `ABORT_JS` JavaScript snippet in `panel/io/notebook.py` used `==` to check whether two objects are equal and therefore do not need to be synchronized.  With simple properties (numbers, strings, etc) this works fine, but for object properties (e.g. the `camera` state in the VTK pane) this check always returns `false`.
This could lead to infinite feedback loops in the property synchronization logic.  An example of this is shown in https://github.com/pyviz/panel/issues/552#issue-473735398.
This PR update the equality check to use `JSON.stringify` on the objects before comparison, which does s decent job handling nested objects of simple types. We could look into optimizing this if performance here is a concern, but …
> Fix nested object equality check in notebook comm logic

- panel/io/notebook.py
This PR is one approach to addressing the issue mentioned in https://github.com/pyviz/panel/pull/529#issuecomment-514299433.  The symptom in that case was that occasionally a selection event would be dropped, and not synchronized from JavaScript to Python.  And this problem only happened when hover data events were being synchronized around the same time.
Here's an overview of my understanding of what's currently happening between Panel and pyviz_comms.
When working in the notebook, Panel builds a JavaScript fragment for each synchronized property of a model.  This JavaScript fragment is used to create a Bokeh `CustomJS` object which is passed to Bokeh for execution whenever the given property changes.  This fragment is built in the `get_comm_customjs` function …
> Avoid dropping events across properties

- panel/models/plotly.py
- panel/models/plotly.ts
- panel/pane/plotly.py
This PR is a follow on to the initial plotly callback support added in https://github.com/pyviz/panel/pull/529.
This adds a new `viewport` property to the plotly pane that holds the current axis ranges of all 2D cartesian axes in the figure.  This information isn't alway available through the `relayout_data` callback, for example when a figure is first displayed. This will be required to implement `Range*` streams in HoloViews, and by extension to support Datashader
Also added `viewport_update_policy` to control whether to update viewport
property with "continuous", "mouseup", or "throttle" policies.  When `viewport_update_policy='throttle'`, the throttle duration is controled by the new `viewport_update_throttle` property.  Here's an example of it in action.
```python …
```
> Add viewport property to plotly pane to hold the axis range for all axes

- panel/models/plotly.py
- panel/models/plotly.ts
- panel/pane/plotly.py
The goal of this PR is to make it possible to preserve user interaction states across updates to the plotly pane.  Examples of user interaction states include the current zoom level, the active modebar buttons, and the traces that were hidden by clicking on the legend.
By default, these user interaction states are reset during calls to `Plotly.react`, but Plotly.js provides `uirevision` properties for controlling which properties should persist across calls to `react`. See https://community.plot.ly/t/preserving-ui-state-like-zoom-in-dcc-graph-with-uirevision for more details.
Prior to this PR, there were a few issues that prevented `uirevision` from working properly.
1. First, the `render` function in `panel/models/plotly.ts` sometimes called `Plotly.purge` prior to `Plotly.react`.  This …
> Plotly: Support preserving user-interaction states across updates with `uirevision` property

- panel/models/plotly.ts
- panel/pane/plotly.py
This PR changes the default viewport update policy for the plotly pane from "continuous" to "mouseup".
I'm still seeing some quirks when updating the plot from a callback on viewport changes when in "continuous" mode, so I'm more comfortable having the default be the more conservative "mouseup" mode.
This PR also adds an extra guard to prevent calling `relayout` while in the middle of a `react` call.  This avoided some unstable behavior I saw while playing with the continuous updates.
> Plotly: change default viewport update policy to "mouseup"

- panel/pane/holoviews.py
This ensures that we construct a specific Pane subclass as `child_pane` whenever possible.  This is important for the current design of https://github.com/pyviz/holoviews/pull/3866.  But even if the design of that PR changes I think this is a reasonable thing to do.
> HoloViews: Fallback to holoviews.Store.backend in _get_model if backend undefined

- panel/tests/widgets/test_select.py
- panel/widgets/select.py
Right now you can't specify any chosen ordering in the selected list on the right side of a cross-selector as the filtering forces the items into the definition order for `options`. Note that when you set the order via `value`, the widget temporarily accepts the chosen ordering before reverting to definition order.
In some situations, you want to specify the ordering of the selected list based on the ordering you add/remove items to/from it. This PR adds a `definition_order` parameter that you can set to `False` to allow this use case.
I'm not entirely sure that `self._lists[selected].values` is the right set of values here but it does seem to work correctly in my (limited) testing. At the very least I no longer see the reordering back to definition order.
> Added definition_order parameter to CrossSelector

- panel/pane/holoviews.py
- panel/tests/pane/test_holoviews.py
- panel/widgets/slider.py
The current HoloViews pane generates a simple layout of the plot and the set of widgets generated from that plot. This makes it easy to compose these two components in different ways but it doesn't match the look that the old-style HoloViews widgets use. Since we want to swap out the widgets in HoloViews with as little disruption as possible this PR adds a ``fancy_layout`` option which tries to match the look and feel of the original widget implementation.
As a simple example here is the output of a HoloMap with this option enabled:
> Add fancy_layout option to HoloViews pane

- panel/io/notebook.py
- panel/models/plotly.py
- panel/models/plotly.ts
This PR contains a few more fixes for using the contunuous viewport update mode with the Plotly pane.
ccf45a8 Makes the Bokeh enum order consistent with the Param selector ordering.  Not quite sure why this was significant, but the mismatch caused the initial value of the `viewport_update_policy` param to not be synchronized from Python to JavaScript.
f8e5894 Adds a fix for calling `react` while panning.  Basically, while panning the axis `range` values should be set to the current `layout.range` values (the values from before the pan action began).  This avoids the unstable panning behavior that was happening when updating the figure while panning. 
327f5b5 is a fix for the "Cannot read property 'content' of null" error that I've been getting in Panel when property updates in both …
> Plotly: Fixes for continuous viewport updates

- examples/reference/panes/HoloViews.ipynb
- panel/layout.py
- panel/pane/holoviews.py
- panel/tests/pane/test_holoviews.py
HoloViews pane now offers a number of options for arranging the plot and widgets
> Improved fancy layout for scrubber

- panel/examples/gallery/simple/random_number_generator.ipynb
I wasn't really sure where to demonstrate it (reference gallery? user guide?) so I just dumped it under gallery simple examples
> Add periodic callback example

- panel/layout.py
In some vague circumstances I haven't been able to pin down changing a model after it has been dynamically added to a layout will not actually sync the model change client side. This PR ensures that events are held and combined while hooks are applied which allows changing models before they are synced with the frontend and ensures those changes actually occur.
> Ensure that events are held while hooks are applied

- panel/pane/holoviews.py
- panel/tests/pane/test_holoviews.py
As the title says. Should decide whether this should be the default and perhaps handle axiswise option on holoviews objects.
> Add preprocessing hook to link HoloViews plot axes across panel layout

- panel/pane/vtk/enums.py
- panel/pane/vtk/vtkjs_serializer.py
Work in progress
Need to test if the correction handle correctly the colormap of the vtk mesh in all case and does not bring regression
Should correct in https://github.com/pyvista/pyvista/pull/268 : 
- https://github.com/pyvista/pyvista-support/issues/15
- Make sure scalar/color mapping is working - sometimes the mapping is totally wrong. Blood vessels example shows this
- custom colormaps (see #345) (except we must create a pyvista plotter since mesh.plot(use_panel=True) does not work anymore due to auto_close=True
Concerning :
- Send text/labels to VTKjs or at least don't throw an error (text added with add_point_labels and add_text)
For me it does not throw error but the text does not show
@banesullivan it will be great if you could test it
> VTK panel scalar array choice correction

- examples/reference/widgets/FileInput.ipynb
- panel/tests/widgets/test_input.py
- panel/widgets/input.py
Bokeh's FileInput have an attribute `accept` which is not passed through
`panel` so this PR will allow `panel`'s FileInput to access `accept`
attribute. The `accept` attribute restrict FileInput to files with
specified extensions.
> Extending FileInput: Add accept param

- examples/user_guide/Deploy_and_Export.ipynb
Following our discussion in #611
> Add to docs on panel serve

- panel/io/server.py
This PR adds a `run()` method to the `StoppableThread` class. The method overrides the default `run()` from [threading library](https://github.com/python/cpython/blob/master/Lib/threading.py#L871-L886). The result from `_target` is used stop the bokeh server completely, thereby releasing the port.
This should fix #634. 
@friedrichknuth has tested this with his work, and it seemed to solve the issue.
> Add run() to StoppableThread class

- examples/gallery/apis/stocks_mpl.ipynb
- examples/gallery/layout/distribution_tabs.ipynb
- examples/gallery/links/plotly_link.ipynb
- examples/gallery/param/reactive_plots.ipynb
- examples/gallery/param/reactive_tables.ipynb
- examples/gallery/simple/iris_kmeans.ipynb
- examples/reference/layouts/GridSpec.ipynb
- examples/user_guide/Components.ipynb
- examples/user_guide/Links.ipynb
- examples/user_guide/Pipelines.ipynb
I addressed what I think are the obvious/uncontroversial ones from the output below:
```
(nbsdev) D:\code\pyviz\panel>pytest -v --nbsmoke-lint --nbsmoke-lint-debug examples
=============================================================== test session starts ================================================================
platform win32 -- Python 3.6.8, pytest-4.4.1, py-1.8.0, pluggy-0.9.0 -- d:\venvs\nbsdev\scripts\python.exe
cachedir: .pytest_cache
rootdir: D:\code\pyviz\panel, inifile: tox.ini
plugins: cov-2.7.1, nbsmoke-0.2.8.post44+gbdfd485
collected 92 items / 190 skipped
examples/gallery/apis/stocks_altair.ipynb::D:\code\pyviz\panel\examples\gallery\apis\stocks_altair.ipynb PASSED                               [  1%]
examples/gallery/apis/stocks_hvplot.ipynb::D:\code\pyviz\panel\examp …
```
> Removed some unused imports and names from examples

- panel/viewable.py
Fixes issues with `distributed` which raised the log level to severe by default. Can be removed once the next distributed release with a fix is out.
> Raise bokeh's log level on serve

- panel/tests/widgets/test_slider.py
- panel/widgets/slider.py
> Fix for Issue #661: IntSlider value should start at the `start` keyword value not 0 

- panel/io/server.py
- panel/io/state.py
tests still missing, they will be added with fec6324.
> Add state repr and server kill command

- examples/reference/widgets/Audio.ipynb
- panel/tests/widgets/test_misc.py
- panel/widgets/misc.py
Fixes the issue : https://github.com/pyviz/panel/issues/351
> Audio widget uses numpy array and sample_rate  as input

- examples/reference/widgets/AutocompleteInput.ipynb
- panel/widgets/select.py
This is to match the bokeh model which exposes this option.
> Adding min_characters to AutocompleteInput

- examples/user_guide/Pipelines.ipynb
- panel/pipeline.py
- panel/tests/test_pipeline.py
> Various improvements for Pipeline

- examples/user_guide/Links.ipynb
- panel/links.py
- panel/tests/test_links.py
- panel/viewable.py
- panel/widgets/button.py
While jslink is very convenient for linking two objects it is also limited because it only exposes the source and target object, doesn't allow providing just a callback on the source and is not really designed around providing custom code.
This PR introduces a ``.jscallback`` method which can be used to add arbitrary JS callbacks, e.g. this example takes the values of the two slider and triggers an alert:
```python
a = pn.widgets.Button(name='Add')
slider1 = pn.widgets.IntSlider()
slider2 = pn.widgets.IntSlider()
a.jscallback(clicks='alert(slider1.value+slider2.value)', args={'slider1': slider1, 'slider2': slider2})
pn.Row(a, slider1, slider2)
```
Cc: @xavArtley I know you were playing around with adding `args` to links but I think this generalizes this more.
> Added jscallback method to Viewable objects

- MANIFEST.in
- examples/user_guide/Templates.ipynb
- panel/_templates/nb_template.html
- panel/io/notebook.py
- panel/template.py
- panel/viewable.py
This makes it possible to render custom Templates inside the notebook to see what they look like and to achieve more complex layouts.
> Add ability to render Template inside notebook

- examples/user_guide/Pipelines.ipynb
Main changes:
- The first section was written as if there was only one output, but the code had two; looks like the markdown wasn't updated when the code was
- Removed stray `, ready_parameter='ready', auto_advance=True` in early example; looks like something meant for the last example
- Clarified hierarchical arrangement of `.layout`
- Cleaned up descriptions and narrative flow
I opened some issues found while reviewing this (#731, #732, #733, #734). When those are fixed, the text in this notebook will need to be updated accordingly, so this PR should probably be merged before addressing any of those (or updated each time).  
One additional issue is that I wasn't sure why `.init()` needed to be called or precisely when it should be called; isn't there some way that it can be called …
> Made Pipelines user guide consistent and clearer

- panel/layout.py
Closes #546 
Inheriting classes define this attribute individually.
> Remove object attribute from Panel class

- panel/tests/test_param.py
- panel/tests/widgets/test_select.py
- panel/widgets/select.py
Related to https://github.com/pyviz/panel/issues/718
```python
pn.extension()
sel = pn.widgets.Select(value='val1', options={'lab1': 'val1', 'lab2': 'val2'})
sel.jscallback(value="""console.log(source.value); console.log(...source.options)""")
sel
```
With this PR on js side the change of the select value gives
> Select behavior

- examples/reference/panes/DataFrame.ipynb
- panel/pane/__init__.py
- panel/pane/markup.py
- panel/tests/pane/test_markup.py
- panel/tests/util.py
- setup.py
Renders pandas, dask and streamz DataFrames and Series.
Streamz objects update:
> Add DataFrame pane for pandas, dask and streamz

- examples/user_guide/Links.ipynb
- panel/links.py
- panel/tests/test_links.py
- panel/viewable.py
Fixes https://github.com/pyviz/panel/issues/592
> Add bi-directional jslink

- panel/layout.py
Closes #514 .
Removed the 'warn' mode to keep only 'error' and 'override'.
'override' behavior now correctly removes the pre-existing Panel.
WIP since the object deletion feels like a kludge and an additional latent bug was noticed during 'error' behavior resulting from line 937-945.
https://github.com/kleavor/panel/blob/a5dff2e30cc08eee713d18ff6ac06d2f20e65c25/panel/layout.py#L937-L945
The if-statement on `overlap` only evaluates to true if the location of the new Panel object exactly matches the location of the conflicting Panel object. In the case of the example provided in the Issue, neither of the new panels matches the "Initial" Panel exactly, and the new object is still added despite erroring, since the error is not raised until the end of the method.
Behavior can be observed in a …
> Correct GridSpec override behavior

- panel/layout.py
https://github.com/pyviz/panel/issues/502
Seems to work for init, modifying state, adding new item, popping item, and working with non-widgets. 
```
pn.extension()
wdgtbox = pn.WidgetBox(
pn.widgets.Button(name='hi'),
pn.widgets.Button(name='yo'),
disabled=False
)
wdgtbox
wdgtbox = pn.WidgetBox(
pn.widgets.Button(name='Hi'),
pn.widgets.Button(name='Yo'),
disabled=True
)
wdgtbox
wdgtbox.append('Irrelevant text')
wdgtbox.append(pn.widgets.Button(name='Hello'))
wdgtbox.pop(-1)
wdgtbox.disabled = False
```
I didn't use `isinstance(obj. Widget)` due to an import error (circular?)
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-32094dc94d29> in …
```
> Add disabled widgetbox

- examples/reference/panes/Streamz.ipynb
- panel/links.py
- panel/pane/__init__.py
- panel/pane/base.py
- panel/pane/streamz.py
- panel/param.py
- panel/tests/test_io.py
- panel/tests/test_param.py
- panel/tests/test_viewable.py
- panel/tests/util.py
Factors out components from ParamMethod class into a ReplacementPane abstract baseclass which is then used as the basis for a streamz.Stream class which allows streaming all kinds of objects in addition to the objects DataFrame like streamz objects supported by the DataFrame pane.
> Add Streamz pane with ReplacementPane base class

- panel/models/vega.py
- panel/models/vega.ts
- panel/pane/vega.py
> Various Vega pane fixes

- pyproject.toml
- setup.py
I came here just to add python 3.7 to the list. However, I noticed a few other things at the same time. So close to the release, you might want to stick to the python 3.7 change only and make the others after the release - let me know if so and I'll re-do this PR.
Other changes:
* pyproject.toml was a bit out of date vs. `extras_require['build']`.
* Removed older python 3 versions - I looked at bokeh's list, assuming it's likley the same for panel (?).
* While I was looking at bokeh, I noticed it had a lot more relevant trove classifiers - pyviz's trove classifiers still only ever talk about science...and don't mention visualization. (At the same time, no idea if anyone uses these classifiers now.)
> Update packaging metadata

- panel/template.py
In order for pre-processing to work correctly on Templates we need to create a fake root that is shared by all sub-objects. Previously this fake root was not added to the `state._views` which is a global index of all roots, which ends up causing issues when updating a root.
Cc: @dharhas this should fix the issues you've been seeing
> Fixed handling of state._views for Templates

- examples/user_guide/Templates.ipynb
- panel/template.py
> Add ability to define Template variables

- panel/widgets/select.py
Fixes https://github.com/holoviz/panel/issues/808
Cc: @xavArtley I've tried to retain the previous behavior when the stringified values are unique but switch back to the guaranteed to be unique labels otherwise.
> Ensure that JS-side Select values are unique

- doc/developer_guide/index.rst
Without the quotes, the output of `conda install -c pyviz pyctdev` will presumably be ending up in the file `0.5.0`. E.g. see #741.
(Not sure why conda wouldn't just install the latest; I can't test that.)
> Developer instructions: fix pyctdev version specification.

- panel/io/__init__.py
- panel/io/server.py
- panel/pane/base.py
- panel/pane/holoviews.py
- panel/viewable.py
- panel/widgets/base.py
This PR ensures that when even on the server events are dispatched immediately. This is achieved by adding an `unlock` context manager which dispatches all ModelChangedEvents triggered in the context body to all sockets on current sessions. I have to do significantly more testing to figure out if this is actually safe.
Fixes https://github.com/holoviz/panel/issues/778
> Unlock Document and dispatch events if we have lock

- panel/models/html.ts
Attempt at caching layout solver state for HTML model.
@MarcSkovMadsen would you mind trying this PR out? It should give a huge performance speedup for the layout solver but I don't yet know if it has unintended consequences. You'll have to check out the PR and then build the models with `pip install -e .` or `python setup.py develop`
> Attempt optimizing layout solver

- panel/_styles/dataframe.css
- panel/config.py
- panel/viewable.py
This pr allow to set the default sizing_mode behavior when panel extension is loaded
It follows discussion https://github.com/holoviz/panel/issues/823
Howver, it does not fix the issue wich is specific to the pandas Dataframe
> Set sizing_mode behavior at panel extension load

- examples/reference/panes/Markdown.ipynb
- panel/_styles/codehilite.css
- panel/_styles/markdown.css
- panel/pane/markup.py
- panel/tests/pane/test_base.py
- panel/tests/pane/test_markup.py
- panel/util.py
Implements https://github.com/holoviz/panel/issues/828
Implements https://github.com/holoviz/panel/issues/391
```
pn.pane.Markdown("""
Lorem ipsum dolor sit amet, vis suscipit expetendis ut, laoreet instructior at vel, nullam efficiantur sit ex. Ei graeco quaeque omittam vis, qui no bonorum gloriatur. Ut sed aliquam convenire, enim nihil efficiendi eu sea. Ne affert eripuit minimum vis, te vel docendi interesset, vix ea quot albucius gloriatur.
Lorem ipsum dolor sit amet, vis suscipit expetendis ut, laoreet instructior at vel, nullam efficiantur sit ex. Ei graeco quaeque omittam vis, qui no bonorum gloriatur. Ut sed aliquam convenire, enim nihil efficiendi eu sea. Ne affert eripuit minimum vis, te vel docendi interesset, vix ea quot albucius gloriatur.
In the words of Abraham Lincoln:
> …
```
> Improve Markdown handling

- panel/pane/holoviews.py
Ensures that HoloViews bokeh axes of different types (categorical, datetime, numeric) are not linked.
> Do not link HoloViews axes with different types

- panel/layout.py
- panel/pane/__init__.py
- panel/pane/base.py
- panel/pane/holoviews.py
The HoloViews pane has a center option which controls whether the contents are centered. The problem with it is that it shouldn't center if the contents are responsive because that ends up leaving gaps. Previously I had a bunch of logic which tried to determine centering from the options set on the HoloViews element. That logic is brittle and potentially expensive because it has to pre-evaluate any dynamic content. Instead of doing that this PR introduces the capability to restart rendering in the middle of an ongoing render.
When a `RerenderError` is raised the layout will catch that error and restart the rendering pipeline. In doing so it will reuse any components in the layout that have already been rendered and clean up any components which have been dropped.  This allows the …
> Allow re-rendering in the middle of render

- panel/pane/vega.py
Fixes https://github.com/holoviz/panel/issues/947
> Enable automatic responsive sizing for Vega pane

- doc/developer_guide/index.rst
- setup.py
Fixes https://github.com/holoviz/panel/issues/866
Fixes https://github.com/holoviz/panel/issues/945
> Updated env and developer docs

- panel/cli.py
Provides help for both pyct and bokeh commands on the CLI and exposes other bokeh commands in addition to serve.
> Provide help for pyct and bokeh commands on CLI

- examples/reference/panes/JSON.ipynb
- panel/_styles/json.css
- panel/models/__init__.py
- panel/models/declaration.d.ts
- panel/models/html.ts
- panel/models/index.ts
- panel/models/json.ts
- panel/models/markup.py
- panel/models/markup.ts
- panel/package.json
- panel/pane/__init__.py
- panel/pane/base.py
- panel/pane/markup.py
- panel/tests/pane/test_markup.py
- panel/tests/test_interact.py
- panel/tests/test_io.py
- panel/tests/test_layout.py
Implements https://github.com/holoviz/panel/issues/936
> Add JSON model and Pane

- panel/tests/widgets/test_input.py
- panel/widgets/input.py
fixes #955 
The value of the `filename` property of the `FileInput` always remained
`None` (also after uploading a file).
I could add a test [here](https://github.com/holoviz/panel/blob/master/panel/tests/widgets/test_input.py#L63), if you let me know what the filename I should be testing for here.
> let FileInput widget set filename

- panel/tests/widgets/test_input.py
- panel/widgets/input.py
Fixes https://github.com/holoviz/panel/issues/858
> Static text bug fix

- panel/pane/base.py
- panel/tests/test_io.py
- panel/tests/test_param.py
Some of our "reactive" APIs like `interact` or `depends` use an internal optimization which tries to avoid replacing models entirely instead reusing them so they can be updated. The problem with that is that if a user supplies an object it will be reused in itself is problematic but also causes issues when that object is later reused (because no change will be detected). Therefore we have to be more careful about this optimization, the two cases we can use the optimization therefore are:
1) The object was created internally, i.e. the user has to reference to the object and therefore will never reuse it.
2) We can safely make a clone of the object (i.e. there are no custom watchers or links installed on the object)
Fixes https://github.com/holoviz/panel/issues/838
Fixes …
> Ensure that ReplacementPane does not modify user objects

- panel/param.py
- panel/util.py
Fixes https://github.com/holoviz/panel/issues/630
> Fix multi-level expand Param subobject

- panel/layout.py
- panel/pane/base.py
- panel/tests/test_layout.py
Fixes https://github.com/holoviz/panel/issues/622
> Replacement pane apply layout

- panel/io/server.py
- panel/pane/holoviews.py
- panel/template.py
- panel/tests/test_template.py
In https://github.com/holoviz/panel/pull/826 I made some fixes to root handling but because I did some confusing things with a shared root a) plots were rendered too many times and b) you could not link axes across roots.
@timothydmorton @dharhas This one is worth testing on the LSST dashboard. I'm not sure you need to be able to link axes across multiple roots but if you wanted to you can do it again. It should also speed things up a little bit since it no longer renders plots multiple times.
> Fixed HoloViews axis linking across Template roots

- panel/cli.py
Aside: I'd like to add at least a basic test of the cli (e.g. as is done for holoviz; https://github.com/holoviz/holoviz/blob/master/tox.ini#L36), but I think that should be part of a larger effort to get better at testing from the user's point of view. (E.g. does conda install panel currently work? And then does `panel install-examples` or whatever work? And then do the examples run? Etc. This topic is on the pyctdev "roadmap".)
> CLI fixups: fix handling of no args; restore pyct commands (were being ignored).

- panel/io/save.py
- panel/pane/base.py
- panel/pane/image.py
- panel/pane/media.py
- panel/pane/vtk/vtk.py
- panel/util.py
Fixes https://github.com/holoviz/panel/issues/985
> Use safe version of os.path.isfile

- panel/util.py
Discovered while trying to update param API usage in https://github.com/holoviz/holoviews/pull/4201. There may be others so don't merge the PR just yet...
> Fixed usage of old param API in util

- panel/config.py
- panel/links.py
- panel/pane/holoviews.py
- panel/widgets/base.py
Further updates to param usage in panel. Please don't merge yet as there may be more that I find as I fix the warnings found by the holoviews tests!
> Additional fixes to param API usage

- panel/io/embed.py
- setup.py
Remove hard limit of max_states when saving embeded files and turn it into a warning while adding a progress bar and enable stopping on keyboard interrupt to avoid long comuptations that cannot be stopped.
> Add progress bar to embed save code

- panel/io/embed.py
- panel/pane/holoviews.py
@Jacob-Barhak Want to try this out, basically just do this with your hv objects:
```python
pn.pane.HoloViews(holomap, rerender=True).save('test.html', embed=True)
```
> Add rerender option for HoloViews pane

- panel/_templates/autoload_panel_js.js
- panel/compiler.py
- panel/io/notebook.py
- panel/models/ace.py
- panel/models/deckgl.py
- panel/models/katex.py
- panel/models/mathjax.py
- panel/models/plotly.py
- panel/models/vega.py
- panel/models/vtk.py
This adds a mechanism by which the dynamic loading code can check if a Javascript component has already been loaded and will then avoid loading it again. This avoids issues in JupyterLab where loading the same module twice can have side-effects, specifically the DeckGL dependency has issues when loaded twice as it seems to unload the JSON loader dependency causing certain examples two fail if two JupyterLab tabs are both running DeckGL examples.
> Ensure JS dependencies are skipped if already satisfied

- panel/__init__.py
- panel/config.py
- panel/pane/vtk/vtk.py
- panel/tests/pane/test_base.py
- panel/tests/test_layout.py
- panel/tests/test_viewable.py
- panel/tests/util.py
- panel/tests/widgets/test_base.py
- panel/widgets/select.py
Replaces the `param` docstring signature with a ``__signature__`` attribute, which should allow for tab-completion in newer versions of IPython. The new signature is applied on extension load as long as `pn.config.apply_signature` is set.
Additionally this enforces strict rules on what `Pane`, `Widget`, and `Panel` component signatures must look like during testing. This ensures no new components are added without considering how the signature code affects them.
> Implemented __signature__ for Viewable objects

- doc/about.rst
- doc/index.rst
Changes:
I'm fine with leaving out mention of Anaconda as that can be found on holoviz.org. @jbednar One thing I do like that I have removed is this sentence:
> Panel is completely open source, available under a BSD license freely for both commercial and non-commercial use.
It is nice to start with a general description of what the library is. I would be in favor of adding a sentence like this to all the About pages for all the HoloViz libraries. What do you think?
> Updates to About page

- panel/compiler.py
- panel/models/ace.py
- panel/models/vtk.py
The requirejs dependency specification was not sufficient to correctly express Ace dependencies resulting in breakage in the classic notebook.
> Fixes for specifying requirejs dependencies

- doc/conf.py
- panel/config.py
- panel/io/embed.py
- panel/io/notebook.py
- panel/pane/holoviews.py
Reverts https://github.com/holoviz/panel/pull/1021
Just to recap some of the conversation/explanation from that PR:
>Just to explain both the issues you are having with HoloViews and what this workaround is meant to achieve. Embedding in Panel (and previously the HoloMap support in HoloViews) work by collecting all the widgets in an app that have a discrete set of values and then taking their cross product to come up with the state space. The embedding code then iterates over that state space and records the events that are generated as each change is applied. This works well for simple cases but can exhibit issues with more complex cases when combined with HoloViews. Specifically HoloViews tries to compute the minimal set of events to go from one state to the next. Imagine you have …
> Safe embed [doc-build]

- panel/tests/widgets/test_file_selector.py
Correction of `test_file_selector.py` which failed on windows due to  the os separator
> os separator correction in test file selector

- examples/reference/panes/VTKVolume.ipynb
No display because affected to `vol`
> [DOC] remove pane affectation to display it

- setup.py
fix #1063
panel 0.8.0 uses CalendarDateRange from param, which was introduced in
param 1.9.2
> bump param dependency

- setup.py
I guess this is what was intended (i.e. increasing the run time version rather than the build time one).
The build dep version could presumably be lower, but it probably doesn't matter too much.
> Fix param dependency update from #1064.

- panel/io/save.py
- panel/io/server.py
- panel/io/state.py
- panel/util.py
> Use Div model for png export to avoid issues with HTML model

- tox.ini
```
$ doit list
[...]
test_deprecations      Unit tests, but DeprecationWarnings and FutureWarnings are errors
[...]
```
```
$ doit test_deprecations
.  test_deprecations
=========================================================================== test session starts ===========================================================================
platform linux -- Python 3.7.3, pytest-5.3.2, py-1.8.0, pluggy-0.13.1 -- /home/sefkw/mc3/envs/miscdev37/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.7.3', 'Platform': 'Linux-5.3.0-7625-generic-x86_64-with-debian-buster-sid', 'Packages': {'pytest': '5.3.2', 'py': '1.8.0', 'pluggy': '0.13.1'}, 'Plugins': {'cov': '2.5.1', 'html': '2.0.0', 'metadata': '1.8.0', 'hypothesis': '3.56.10', 'nbval': '0.9.3', 'nbsmoke': '0.4.1'}}
rootdir: …
```
> Add test_deprecations to test suite.

- panel/io/save.py
Do this not only for `.png` export but for all others aswell (`.html`) to allow workflows that use `phantomjs` to render a `pdf` from the created `html`
> Swap HTML with DIV

- panel/viewable.py
keyword arguments show and title are now passed to the get_server.
> fix viewable show keyword arguments

- panel/viewable.py
Right now, a notebook can have `.servable('Title')`, but it has to have `.show(title='Title')` with the keyword specified. I very often switch between .show and .servable when debugging, and this difference makes doing so awkward.  Note that if someone has previously used "port" as a positional argument, this change will not be backwards compatible. So I can understand if it's decided not to merge this, but I thought it was worth proposing before the number of Panel users got so high that this behavior could never be changed.
> Made signature of show() match that of servable()

- panel/widgets/slider.py
Fixes https://github.com/holoviz/panel/issues/1134
> Ensure discrete slider respects layout opts

- doc/index.rst
(And promote it to be before github issues.)
> Link to discourse rather than gitter.

- panel/pane/holoviews.py
- panel/widgets/slider.py
In the last release I made an unfortunate change to DiscreteSlider margins. Additionally this PR hides widgets when there is only a single HoloMap frame.
> Minor fixes for HoloViews widgets

- panel/io/save.py
The [bokeh.io.export.export.export_png](https://github.com/bokeh/bokeh/blob/12a3c0b7fbf36700b542acdefad15a518391d582/bokeh/io/export.py#L58) function has been updated, and now `filename` needs to be passes as a keyword argument. 
* This PR updates the filename parameter passed to the function to reflect the update of the `export_png` signature.
> Update signature of bokeh.io.export.export_png

- panel/io/server.py
- panel/io/state.py
- panel/viewable.py
As described in #1148 we override the bokeh Websocket handlers asynchronous locking mechanisms to allow synchronous functions to trigger updates on the frontend immediately instead of blocking until they finish, e.g.:
```python
import time
button = pn.widgets.Button(name='Run')
progress = pn.widgets.Progress(value=0)
def update_progress(event):
for i in range(100):
time.sleep(0.01)
progress.value = i
button.on_click(update_progress)
pn.Row(button, progress).show()
```
If we didn't do this, this example wouldn't update the progress bar until the callback finishes. However in implementing this we are not respecting the Websocket handlers write lock. This PR ensures checks whether a write lock is enabled and if so locks the synchronous events out. This ensures most …
> Respect write-locks in synchronous Websocket events

- panel/tests/widgets/test_input.py
- panel/widgets/input.py
See https://github.com/bokeh/bokeh/pull/9509 , date is in ISO format.
> Compatibility with Bokeh 2 DatePicker

- panel/_templates/nb_template.html
- panel/io/model.py
- panel/io/notebook.py
- panel/io/state.py
- panel/layout.py
- panel/models/comm_manager.py
- panel/models/comm_manager.ts
- panel/models/index.ts
- panel/template.py
- panel/tests/test_layout.py
- panel/tests/test_reactive.py
- panel/tests/widgets/test_ace.py
- panel/tests/widgets/test_base.py
- panel/tests/widgets/test_button.py
- panel/tests/widgets/test_input.py
- panel/tests/widgets/test_player.py
- panel/tests/widgets/test_select.py
- panel/tests/widgets/test_slider.py
- panel/viewable.py
- panel/widgets/button.py
In the past to make communication work in notebook backends we had to attach callbacks to all bokeh properties we wanted to monitor. This was extremely inefficient because each of these callbacks is ~100 lines of JS code and a large app might have hundreds or even thousands of properties. In this PR we introduce a CommManager model, this model is added to the `Document.roots` when rendering in a notebook and registers a Document.on_change callback which will dispatch **all** the protocol messages that bokeh supports to Python. This means that it will behave identically to the server, simplifying codepaths and ensuring that bokeh models stay synced at all times.
Benefits:
- We support all bokeh protocol messages
- Simplifies codepaths (no more difference between comm and server codepaths) …
> Add CommManager model to handle notebook comms

- panel/models/vega.ts
Fixes bug where Vega data containing a singular data object would not get rendered and raise an error.
> Handle singular data object in Vega model

- panel/io/save.py
- panel/io/state.py
- panel/util.py
No longer needed and messed up HTML exports in certain scenarios.
> Removed escape workaround for png exports of HTML models

- panel/layout.py
Fixes https://github.com/holoviz/panel/issues/1188
> Fix bug closing Tabs

- doc/releases.rst
- panel/io/server.py
Allows serving flask app using pn.serve, e.g.:
```python
from flask import Flask
flask_app = Flask(__name__)
@flask_app.route('/app')
def hello_world():
return 'Hello, World!'
def panel_app():
return "# This Panel app runs alongside flask, access the flask app at [here](./flask/app)"
pn.serve({'/flask': flask_app, 'panel': panel_app}, port=5001)
```
This will serve the panel app on `localhost:5001/panel` and the flask app on `localhost:5001/flask/app`.
> Allow serving Flask apps

- panel/io/state.py
- panel/layout.py
- panel/pane/base.py
- panel/template.py
- panel/viewable.py
- panel/widgets/base.py
Panel was built around the idea that everything has a single root model which contains all the other models. Templates came along and broke that assumption, because it allows you to insert multiple roots at different points of an Jinja template.
To deal with that we create a fake root model, which makes things like cross-root linking of axes and JS links across roots work. However the rest of the code was not aware this thing was a fake, so it was creating duplicate models for it and keeping them all updated. So bad news is, that’s a horrific bug, good news is everything that was using templates is about to get 2x faster.
> Do not process events related to fake Template root

- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/1195
> Fixed DataFrame widget datetime formatting

- doc/developer_guide/index.rst
- panel/package-lock.json
Closes https://github.com/holoviz/panel/issues/739
> Update guidance about package-lock.json

- panel/io/save.py
- panel/template.py
Partially addresses https://github.com/holoviz/panel/issues/1066
This does not yet support embedding which is what the original issue requested. It does however lay the groundwork for that.
> Implement Template.save

- MANIFEST.in
This should fix the conda-forge package. Looking at the history of `MANIFEST.in`, this should have failed before, so something else must have changed as well, either in panel or on conda-forge.
fixes #1233
> Include panel/index.ts in package data

- panel/models/vtk.py
- panel/models/vtk/vtk_colorbar.ts
- panel/models/vtk/vtk_layout.ts
- panel/pane/vtk/vtk.py
> [VTK] Add colorbar on vtk renderer

- panel/tests/widgets/test_misc.py
- panel/widgets/misc.py
Hi!
I've started to work on fixing #1236, to try to better understand the code I started with adding some more tests and error handling.
As I found a way to update the ``filename`` parameter from the callback as side-effect (this is what I intended to do in #1236), I've decided to submit this first batch of work as a PR.
I plan to submit another PR in the next days, trying to fix completely #1236.
(I was also hindered by these ``Model 'panel.models.widgets.FileDownload' does not exist`` errors while trying to launch a Bokeh server, error that is probably related to the recent problems around that, I'll try to update my setup and see how it goes).
> FileDownload widget: Allow callback to update filename

- examples/user_guide/Deploy_and_Export.ipynb
- panel/io/embed.py
- panel/io/notebook.py
- panel/io/save.py
- panel/tests/io/test_embed.py
- panel/viewable.py
- panel/widgets/base.py
- panel/widgets/button.py
- panel/widgets/input.py
- panel/widgets/player.py
- panel/widgets/select.py
- panel/widgets/slider.py
Fixes https://github.com/holoviz/panel/issues/1198
Simple example:
```python
slider = pn.widgets.FloatSlider(name='A')
@pn.depends(slider)
def fn(value):
return value + 1
pn.Row(slider, fn).embed(states={slider: [0.1, 0.7, 1]})
```
> Add ability to define explicit embed states

- panel/param.py
`ParamFunction` was needlessly creating multiple watch callbacks.
> Batch ParamFunction events

- panel/param.py
Following the discussions in #1128, I discovered that providing the `widgets` dict currently did not allow specifying it for `param.Number`:
```
import param 
pn.extension()
class T(param.Parameterized):
a = param.Number(default=None)
t = T(a=1e-3)
pn.Pane(t.param, widgets={
'a': pn.widgets.LiteralInput()
}) # falls back to Spinner no matter what
```
The reason was that `param.Number` was handled as a special case and actually overriden once again if no `bounds` are provided.
This PR simply adds another quick check and forces panel to roll with the user-supplied `widgets`, if provided, even for `param.Number`.
> Do not override widget class if already specified by user

- examples/reference/widgets/FileDownload.ipynb
- examples/user_guide/Widgets.ipynb
- panel/models/file_download.ts
- panel/models/widgets.py
- panel/tests/widgets/test_misc.py
- panel/widgets/misc.py
Fixes #1299 
The intent of this PR is to fix various bugs with the FileDownload widget. I had to clearly define the behaviour of the widget, that to me follows three cases:
1. embed=True --> The widget is a link that looks like a button (right click to "Save as..." is possible)
2. auto=False --> There are two steps, first the widget is a button, after it's clicked it's a link (right click possible)
3. auto=True --> The widget is a button (right click to "Save as..." isn't possible).
To get there I had to make the following changes:
* On the python side: the biggest change is the new ``_transfers`` model attribute. It took me a long time before I dared to touch the python side but I found out it was the only solution that worked and allowed to fix all the bugs. When the widget is a button, …
> Improve the FileDownload widget

- examples/reference/layouts/WidgetBox.ipynb
The ``disabled`` property added to the ``WidgetBox`` widget by https://github.com/holoviz/panel/pull/532 wasn't documented in the reference example, fixes that.
> Add missing property in WidgetBox docs

- examples/reference/widgets/FileInput.ipynb
Fixes #519 
Remove from the reference docs of the `FileInput` widget any mention to the `name` parameter to make clear that it has no effect whatsoever on the display of the widget.
> Remove name property in docs of FileInput

- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
Fixes #821 
I've had to validate the dataframe inside `_manual_update` because this method was called before the `_validate` callback I've added.
> Improve error message for dataframe with duplicate column names

- panel/layout/tabs.py
The server seemingly sometimes sends messages that are misinterpreted as Tab close events, this ensures these events are ignored.
> Fix bug in closed Tabs handling

- examples/reference/panes/Param.ipynb
- examples/user_guide/Param.ipynb
- panel/param.py
- panel/tests/test_param.py
Fixes #1332 
I also fixed two non related bugs occurring when `.object` would be updated with `None` or with parameters `.param`.
> Add a name parameter to the Param pane

- panel/param.py
- panel/tests/test_param.py
Fixes #1331 
The panel widget `Toggle` was not synced like the other widgets in a Param pane:
https://github.com/holoviz/panel/blob/b73ec774734ee7b88ebaf7749707309caeba66b2/panel/param.py#L378-L379
This special handling originated from #15 and was probably implemented this way because the widget that is created when one needs to expand a subparameter pane is a `Toggle`. I believe that now widgets created in a pane are given by `_ordered_params()` which do not expose that `Toggle` widget. So it's just fine to remove that special handling.
I also took advantage of this PR to fix a typo and improve the coverage of the param action test.
> Fix handling of the Toggle widget in a Param pane

- panel/layout/base.py
- panel/tests/layout/test_base.py
Fixes #1329 
Which was caused by a tiny bug in the `clone` method.
> Fix a bug in the clone method of the layouts

- examples/user_guide/Param.ipynb
- panel/tests/widgets/test_base.py
- panel/widgets/base.py
Simplifies the creation of a widget linked to and created from a particular parameter.
```python
import param
class A(param.Parameterized):
value = param.Number()
a = A()
pn.widgets.FloatSlider.from_param(a.param.value, start=0, end=3.14)
```
@maximlt @MarcSkovMadsen Any thoughts on this? It's **a** solution to something I think you both brought up before. If you like the idea maybe we should also consider a shorter method name than `from_parameter`, suggestions welcome.
> Add Widget.from_param classmethod

- panel/models/player.ts
> Player visual indicator of button pressed

- examples/gallery/demos/VTKSlicer.ipynb
- examples/gallery/dynamic/dynamic_ui.ipynb
- examples/user_guide/Customization.ipynb
- panel/_styles/widgets.css
- panel/layout/base.py
Because it overwrites the style of ipywidgets.
https://github.com/jupyter-widgets/ipywidgets/blob/3bd75276370271e43ca5aa38d59a1848dfb65fb7/packages/controls/css/widgets-base.css#L99
Because of this code, running `holoviews.notebook_extension()` overwrites existing css that changes an `ipywidget` from:
to
The annoying thing is that this change persists over kernel restarts *and* clearing of the notebook.
> rename widget-box -> panel-widget-box

- panel/pane/vega.py
- panel/tests/pane/test_vega.py
Fixes https://github.com/holoviz/panel/issues/1323
> Handle Vega geometry types in data

- panel/template/base.py
Certain components do not render their models immediately instead preferring to do so lazily. The Template however expects all models to be available on initial render. This PR ensures that components that have not yet been instantiated are simply skipped avoiding any resultant errors.
> Ensure non-existent models in Template do not cause errors

- examples/reference/widgets/DataFrame.ipynb
- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
This PR improves the `DataFrame` widget in a two ways relating to support for DataFrame indexes:
1. It fixes a bug editing DataFrames with a non-default index name
2. It adds support for displaying hierarchical multi-indexed dataframes with aggregators
As an example here is a three-level DataFrame aggregated over the indexes:
```python
from bokeh.sampledata.population import data as population_data 
pop_df = population_data[population_data.Year == 2020].set_index(['Location', 'Sex', 'AgeGrp'])[['Value']]
pn.widgets.DataFrame(value=pop_df, hierarchical=True, aggregators={'Sex': 'sum', 'Location': 'sum'}, height=400) 
```
> Add support for hierarchical multi-indexed DataFrame

- panel/io/ipywidget.py
- panel/io/resources.py
- panel/pane/ipywidget.py
Previously we had supported using ipywidgets in the notebook (using the regular Jupyter CommManager) and on the server using ipywidgets_bokeh. I had however overlooked the case where you start a server inside the notebook, e.g. when using `.show()`. This PR provides a custom IPyKernel to be used in such scenarios, when rendering a plot with `.show()` the kernel on each Comm is updated to point to this custom kernel allowing communication on the server even when it has been launched inside a notebook.
> Improvements for ipywidgets support

- panel/pane/vtk/synchronizable_serializer.py
- panel/pane/vtk/vtk.py
- panel/tests/pane/test_vtk.py
Supersedes: #1402
fix: #1401
fix: #1398
> [VTK] Various fix

- panel/viewable.py
So there appear to have been two garbage collection issues, 1) the `state._views` dict was not cleaned up leaving references to the `Document` and b) the Location models were not correctly cleaned up again leaving potential references to a `Document`. 
Fixes https://github.com/holoviz/panel/issues/1399
> Ensure Document and Location models are garbage collected

- examples/reference/widgets/Ace.ipynb
- panel/models/ace.py
- panel/models/ace.ts
- panel/widgets/ace.py
The print margin often overlaps with other components so this PR allows disabling it.
> Add print_margin and filename option to Ace widget

- examples/user_guide/Deploy_and_Export.ipynb
- examples/user_guide/Overview.ipynb
- panel/io/location.py
- panel/io/server.py
- panel/io/state.py
- panel/reactive.py
* Adds a `state.busy` parameter which is toggled whenever an event is received and being processed. This will enable visual busy indicators.
* Adds `onload` callbacks which are triggered once a session has been loaded in the browser.
Partially addresses https://github.com/holoviz/panel/issues/1362
> Add state.busy and onload callback

- examples/user_guide/Deploy_and_Export.ipynb
- panel/__main__.py
- panel/command/__init__.py
- panel/command/serve.py
- panel/io/server.py
- panel/tests/test_cli.py
- panel/tests/test_server.py
- setup.py
This PR allows serving static files by providing a dictionary mapping from route to paths to `pn.serve` or `panel serve` on the command line.
On the commandline the syntax looks like this:
```bash
panel serve some_app.py --static-dirs custom_static="./examples"
``` 
while in Python it's specified as:
```python
pn.serve(some_pn_obj, static_dirs={'custom_static': './examples'})
```
In both cases all contents of './examples' will now be served on `http(s)://hostname/custom_static/` (note that the `/static` endpoint is reserved for bokeh's static files).
Implement https://github.com/holoviz/panel/issues/1118
Cc: @MarcSkovMadsen @lvankouwen Any chance you could give this a spin and see if it meets your requirements?
> Add support for serving static files

- examples/reference/panes/Alert.ipynb
- panel/_styles/alerts.css
- panel/pane/__init__.py
- panel/pane/alert.py
- panel/tests/pane/test_alert.py
One of the things i use a lot and see other users using in their analytics app are [Bootstrap inspired Alerts](https://getbootstrap.com/docs/4.0/components/alerts/). 
So I would like to contribute one.
The contributed code is **ready for review** by @philippjfr . 
I've chosen
- To implement one `Alert` with an `alert_type` parameter instead of a collection of `PrimaryAlert`, ..`InfoAlert`, ..., `DarkAlert` to keep the api in line with `Button`.
- To add an alert.css file instead of styling inline. That will enable easier custom styling.
- Not to implement a custom Bokeh model supporting the `alert_type`. Let me know if that is needed.
- To include it in `pn.pane` instead of `pn.widget` or `pn.components.bootstrap`. Those would be alternatives.
- To make the 'stretch_width` by default. I …
> Alert pane: Allows providing contextual feedback messages for typical user actions

- panel/models/html.ts
- panel/models/layout.ts
- panel/models/plotly.ts
- panel/models/vtk/util.ts
- panel/package-lock.json
- panel/package.json
- setup.py
There was a regression because bokeh added a `invalidate_cache` method on the internal layout class which we override for the Markup models.
> Fixed compatibility with Bokeh 2.1

- panel/models/deckgl.ts
- panel/models/plotly.ts
In bokeh 2.1 arrays with more than 1 dimension now have a proper shape attribute.
> Fixed handling of ColumnDataSource array shapes for bokeh 2.1

- panel/models/json.ts
- panel/pane/markup.py
- panel/tests/pane/test_markup.py
Fix https://github.com/holoviz/panel/issues/1415
> Fix JSON pane depth and rerendering

- panel/param.py
- panel/widgets/input.py
Fixes https://github.com/holoviz/panel/issues/1271
> Fix param mapping for param.CalendarDate and DatePicker

- panel/config.py
Fixes https://github.com/holoviz/panel/issues/1316
> Warn if extension could not be loaded

- panel/pipeline.py
Fixes https://github.com/holoviz/panel/issues/1276
> Ensure Pipeline graph does not share axes with other plots

- panel/param.py
- panel/tests/test_param.py
Fixes https://github.com/holoviz/panel/issues/1327
> Ensure param callbacks initialized

- panel/io/server.py
> Accept MethodType as panel.serve parameter

- panel/models/vtk/util.ts
- panel/models/vtk/vtkfollower.ts
- panel/pane/vtk/synchronizable_deserializer.py
- panel/pane/vtk/synchronizable_serializer.py
- panel/tests/pane/test_vtk.py
Implement and fix #1412
I had to port https://github.com/Kitware/vtk-js/pull/1511 into panel vtk models because until https://github.com/Kitware/vtk-js/issues/1493 is solved I can't update vtk-js version
> [VTK] add vtkFollower

- README.md
Hi! 
I noticed that Matplotlib link was broken in readme.md. I updated it!
> Matplotlib Link in Readme.md is broken, it is updated.

- panel/auth.py
- panel/command/serve.py
- panel/config.py
Sometimes we want to explicitly provide a OAuth redirect URI.
> Add support for explicit OAuth redirect URI

- examples/reference/panes/Matplotlib.ipynb
- panel/io/notebook.py
- panel/pane/ace.py
- panel/pane/base.py
- panel/pane/deckgl.py
- panel/pane/ipywidget.py
- panel/pane/markup.py
- panel/pane/plot.py
- panel/pane/plotly.py
- panel/pane/vega.py
- panel/pane/vtk/vtk.py
- setup.py
Adds support for interactive Matplotlib plots based on ipympl.
> Add support for interactive mode on Matplotlib

- panel/command/serve.py
- panel/depends.py
- panel/dist/post_require.js
- panel/dist/pre_require.js
- panel/io/resources.py
- panel/io/server.py
- panel/layout/accordion.py
- panel/layout/card.py
- panel/layout/grid.py
- panel/template/bootstrap/bootstrap.html
- panel/template/golden/golden.html
- panel/template/material/material.html
Some unfortunate workarounds and other miscellaneous fixes. Would like to find a better solution to handling requirejs but for now we add some workarounds that ensure requirejs does not load with the require/define utilities provided by Ace. Also fixes a few other issues.
> Fix issues with requirejs and templates

- panel/auth.py
The OAuth requests should include a random state cookie which ensures the request is not tampered with.
> Generate random state cookie

- panel/io/resources.py
- panel/io/server.py
- panel/template/base.py
- panel/tests/test_server.py
Previously we added the Template CSS to the global list of CSS to be served. This meant that this CSS would pollute the notebook, cause issues when switching templates since the CSS would persist and cause issues when multiple pages being served used different templates or themes.
This PR replaces the default bokeh `DocHandler` with a `PanelDocHandler` which in turn replaces bokeh `Resources` with `PanelResources`. This gives us more control over the CSS and JS files being served up.
> Serve template CSS files per Document

- panel/auth.py
- panel/io/resources.py
Some cleanup of the code and error handling for the various OAuth providers.
> Improved error logging for OAuth handlers

- .travis.yml
- examples/reference/panes/Matplotlib.ipynb
- panel/pane/holoviews.py
- panel/pane/plot.py
- panel/tests/pane/test_holoviews.py
Previously the ranges were not merged correctly and simply inherited from the first plot.
> Ensure HoloViews plot ranges are merged correctly

- .travis.yml
- examples/reference/indicators/BooleanStatus.ipynb
- examples/reference/indicators/LoadingSpinner.ipynb
- panel/_styles/widgets.css
- panel/io/state.py
- panel/template/base.py
- panel/template/bootstrap/bootstrap.css
- panel/template/bootstrap/bootstrap.html
- panel/template/golden/golden.css
- panel/template/golden/golden.html
- panel/template/material/material.css
- panel/template/material/material.html
- panel/template/vanilla/vanilla.css
- panel/template/vanilla/vanilla.html
- panel/tests/test_template.py
- panel/viewable.py
- panel/widgets/indicators.py
- tox.ini
Adds two boolean indicators which can be used independently or in one of the default templates.
Here we can see the indicator on the right of the template header.
> Add busy/loading indicators and enable on Template

- panel/layout/base.py
- panel/tests/layout/test_base.py
Passing `objects` as a keyword was not previously supported.
> Ensure ListPanel objects can be passed as keyword

- panel/callbacks.py
Using bokeh's curdoc() function means the periodic callbacks cannot easily be used with `pn.serve`.
> Ensure callbacks use pn.state.curdoc

- examples/reference/widgets/DataFrame.ipynb
- panel/widgets/tables.py
Exposes some of the new features of the bokeh DataTable that will land in Bokeh 2.2. Including `autosize_mode`, `frozen_rows` and `frozen_cols` options.
> Add new features to DataTable

- panel/io/location.py
- panel/viewable.py
The Location component lookup was broken in certain scenarios causing errors.
> Fix adding and deleting Location component

- examples/user_guide/Overview.ipynb
- panel/io/state.py
- panel/tests/io/test_state.py
The `state.as_cached` utility allows caching data across sessions by providing a key, a function and optionally a set of keyword arguments which will be memoized.
> Add state.as_cached function

- panel/io/location.py
- panel/tests/io/test_location.py
Previous unsync would always operate on all the parameters of a Parameterized, now you can partially unsync just a subset of parameters.
> Allow partially unsyncing parameterized from the Location

- examples/reference/widgets/MenuButton.ipynb
- panel/widgets/__init__.py
- panel/widgets/button.py
Wraps the Dropdown widget in bokeh, which generates a Menu which allows listening to the selected item.
> Add MenuButton widget

- examples/user_guide/Deploy_and_Export.ipynb
- panel/io/callbacks.py
- panel/io/embed.py
- panel/reactive.py
- panel/tests/test_links.py
Implements suggestions in https://github.com/holoviz/panel/issues/579
> Improve PeriodicCallback

- panel/io/embed.py
- panel/tests/io/test_embed.py
Fixes https://github.com/holoviz/panel/issues/806
Fixes https://github.com/holoviz/panel/issues/1083
> Link widgets with same name during embed

- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/1534
> Ensure DataFrame with no index is editable

- panel/widgets/select.py
Updated select.py to support case-insensitive AutocompletionInput, which was added to bokeh in v 2.1.0 (https://github.com/bokeh/bokeh/issues/9922).
> Case-insensitive autocompletion

- examples/reference/indicators/BooleanStatus.ipynb
- examples/reference/indicators/Dial.ipynb
- examples/reference/indicators/Gauge.ipynb
- examples/reference/indicators/LoadingSpinner.ipynb
- examples/reference/indicators/Number.ipynb
- examples/reference/indicators/Progress.ipynb
- panel/tests/test_docs.py
- panel/tests/widgets/test_base.py
- panel/tests/widgets/test_indicators.py
- panel/widgets/__init__.py
- panel/widgets/indicators.py
- panel/widgets/misc.py
Adds a number of `ValueIndicator` which indicate some numeric value, useful for BI dashboard:
- Number
- Dial
- Gauge
> Add a number of ValueIndicators

- panel/param.py
- panel/tests/test_param.py
This should fix https://github.com/holoviz/panel/issues/1581
I've added a test and a one line fix. For me all tests pass.
But I simply don't understand the logic of the function I've changed. Are we sure that all combinations of events wil work?
> fixed issue 1581

- setup.py
I guess you meant `nbsmoke` in the comment? (Although I bet `nbval` has exactly the same problem. And I would like to replace `nbsmoke` with `nbval`. Maybe that's why you wrote nbval? :) )
> Unpin pytest now nbsmoke 0.5 is released

- panel/io/server.py
When scaling Panel behind a load balancer it can occur that the request for the Panel.js extension arrives on a server which does has not yet loaded a session and therefore isn't aware of the extension. Here we simply make sure that the extension is registered as soon as Panel is imported.
> Ensure panel.js is served before session is started

- doc/releases.rst
The 0.9.6 release has the error, so the 0.9.7 versions fixes it, if I am not mistaken.
> Update releases.rst (typo)

- examples/reference/widgets/AutocompleteInput.ipynb
- panel/package-lock.json
- panel/widgets/select.py
- setup.py
fixes #685
bokeh 2.3.0 introduces a new `restrict` keyword (default: True).
Setting it to False allows users to enter values that are not present in
the list of completions.
> AutocompleteInput: allow user-defined values

- panel/models/vtk/vtkfollower.ts
- panel/pane/vtk/synchronizable_serializer.py
- panel/pane/vtk/vtk.py
A vtk dataset can contain several data arrays but only one is used to color the mesh, the "active scalars".
Until now only this array was serialized, it allow to minimize the size of the serialized scene.
However by allowing the serialization of all data arrays and using some custom javascript functions we could make some temporal 3d visualization easier.
This PR add a parameter `serialize_all_data_arrays` to allow this
Here is a comparison between both options:
> add option to serialize all vtkDataset arrays

- examples/reference/templates/Bootstrap.ipynb
- examples/reference/templates/GoldenLayout.ipynb
- examples/reference/templates/Material.ipynb
- examples/reference/templates/Vanilla.ipynb
- panel/pane/image.py
- panel/template/base.py
- panel/template/bootstrap/bootstrap.css
- panel/template/bootstrap/bootstrap.html
- panel/template/golden/golden.css
- panel/template/golden/golden.html
- panel/template/material/material.css
- panel/template/material/material.html
- panel/template/vanilla/vanilla.css
- panel/template/vanilla/vanilla.html
Adds ability to add logo to template directly rather than using Panel objects, which were difficult to align correctly.
> Add logo option for BaseTemplates

- examples/user_guide/Param.ipynb
- panel/param.py
Fixes https://github.com/holoviz/panel/issues/1574
> Use widget_type for Param widget override

- panel/io/server.py
- panel/viewable.py
There were some issues with Templates registering the session multiple times.
> Handle session_info correctly in Templates

- panel/io/model.py
- panel/layout/tabs.py
- panel/reactive.py
- panel/tests/layout/test_tabs.py
- panel/tests/test_reactive.py
The problem is that bokeh model changes were simply being dropped instead of being pushed through the comm so this ensures that if there are outstanding held events once we get to the end of a callback triggered by a change on the frontend those changes are pushed.
- Fixes https://github.com/holoviz/panel/issues/1618
> Ensure Bokeh model changes are always pushed

- panel/models/file_download.ts
- panel/widgets/misc.py
- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/1598
> Fixed bugs with None default on String params

- panel/param.py
- panel/tests/test_param.py
Fixes https://github.com/holoviz/panel/issues/1551
> Handle explicit triggering in Param pane

- examples/reference/indicators/BooleanStatus.ipynb
- examples/reference/indicators/Dial.ipynb
- examples/reference/indicators/Gauge.ipynb
- examples/reference/indicators/LoadingSpinner.ipynb
- examples/reference/indicators/Number.ipynb
- examples/reference/indicators/Progress.ipynb
- panel/__init__.py
- panel/models/progress.ts
Allows using `pn.indicators` instead of `pn.widgets.indicators` and updates docs to reflect this.
> Expose Indicators at top-level

- examples/reference/panes/VTKVolume.ipynb
- panel/models/vtk.py
- panel/models/vtk/vtkvolume.ts
- panel/pane/vtk/vtk.py
implements https://github.com/holoviz/panel/issues/1630
by default I let it to true 
Customizing the controller widget is doable but it should be more a vtk.js request since I use directly the VolumeController class defined in vtkjs and there are not options to customize it (https://kitware.github.io/vtk-js/api/Interaction_UI_VolumeController.html)
> [VTKVolume] add option to expand the controller

- panel/viewable.py
If a session was established but never rendered it wouldn't count as live but still subtract from the live count.
> Fix counting of live sessions in session_info

- examples/user_guide/Django_Apps.ipynb
- setup.py
To be able to run the Django and panel together, [channels](https://channels.readthedocs.io/en/latest/) is needed. 
A reason why it was not added together with Django at first, is that it was not on conda-forge before April this year.
I have also updated the documentation for the Django Apps page.
> Add channels to extra dependencies

- .travis.yml
- doc/developer_guide/index.rst
- panel/compiler.py
- panel/config.py
- pyproject.toml
Fixes https://github.com/holoviz/panel/issues/1653
> Fixes and doc updates for bundling machinery

- panel/io/location.py
Ensures parameter types other than the real basics can be synced with the `Location` components query parameters.
> Use param serializer for synced URL parameters

- panel/template/__init__.py
- panel/template/material/__init__.py
- panel/template/material/material.css
- panel/template/material/material.html
- panel/template/theme.py
- panel/tests/template/test_manual.py
I have tested the Material Template and see some issues that I would like to fix
- The header items overflow the header on the right
- The header has no box shadow (as the Vanilla template has)
- There are a lot of scrollbars.
- A little bit more padding/ margin is need.
- Cannot set the main max-width. 
- Add a little bit of gray to the sidebar.
I will develop the fixes ASAP. Will change the Material Template to behave as the Vanilla Template.
> Material Template Fixes

- panel/template/material/material.css
- panel/template/material/material.html
- panel/template/vanilla/vanilla.css
- panel/template/vanilla/vanilla.html
So far I've
- Vanilla Template apply `main_max_width`.
- Set `max-with: 100%` for img. It's a hazzle using images in Markdown without this.
Such that this looks nice
> Template Fixes

- panel/io/notebook.py
> Fix resource setting in notebook

- panel/template/material/dark.css
- panel/template/vanilla/vanilla.css
> CSS tweaks

- examples/reference/panes/ECharts.ipynb
- panel/pane/echarts.py
- panel/tests/pane/test_echart.py
- panel/tests/pane/test_echarts.py
Finalizes the request for Echarts **and** Pyecharts https://github.com/holoviz/panel/issues/1133.
I believe it's important to support pyecharts as this is **THE** Python wrapper for ECharts and it's highly popular with ~10.000 stars on Github.
I've now added support for Pyecharts. I've tried to see how other plotting panes support dictionary specification and python wrapper specification.
I've added a test for ECharts and a manual test for pyecharts. I've tried to define the manual test for pyecharts such that its not disturbing the normal test suite, but can be run manually on demand.
I've added a comment to the ECharts notebook about suppport for pyecharts. But I've not provided an example as I was not sure you would like to add that dependency. But there is a simple example in the …
> Add support for Pyecharts

- panel/pane/base.py
- panel/param.py
- panel/template/base.py
- panel/viewable.py
Fixes https://github.com/holoviz/panel/issues/1700
> Only run preprocessors once on Templates

- panel/interact.py
- panel/pane/base.py
Inplace updating can cause a variety of issues, which were solved for ReplacementPane types a while ago. This factors out this logic so it can be used by `interact(ive)`.
> Ensure interact(ive) does not update objects inplace

- panel/pane/image.py
- panel/tests/pane/test_image.py
Attempt to fix #1711 by forcing attribute with read to set seek(0). 
I can't think of a good reason not to start the read at 0, but if there is this PR can be closed.
> Add seek(0) to pane.image

- examples/gallery/simple/deckgl_game_of_life.ipynb
- examples/gallery/simple/random_number_generator.ipynb
- examples/reference/panes/Streamz.ipynb
Fixes #1717 
And I also updated pd.datetime.now() to datetime.now() from Streamz.ipynb because it is deprecated. 
`FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.`
> Updated documentation to pn.state.add_periodic_callback

- examples/reference/panes/Alert.ipynb
- panel/pane/alert.py
- panel/tests/pane/test_alert.py
This is a fix of #1728.
The manual test `python -m panel serve 'panel\pane\alert.py' --dev` is shown below. 
I've verified there are no exceptions in the console. I don't know how to setup an a automated test of this.
> Fixes Alert c.f. #1728

- panel/pane/alert.py
- panel/pane/markup.py
- panel/tests/pane/test_alert.py
- panel/tests/util.py
Fixes https://github.com/holoviz/panel/issues/1725
Fixes https://github.com/holoviz/panel/issues/1728
> Fix changing of alert_type on Alert pane

- examples/reference/widgets/DatetimeRangeInput.ipynb
- panel/tests/widgets/test_input.py
- panel/widgets/__init__.py
- panel/widgets/input.py
We didn't have any widget that would let you enter a range of datetimes so this adds a simple composite widget consisting of two `DatetimeInput` widgets:
> Add DatetimeRangeInput widget

- panel/template/bootstrap/bootstrap.css
- panel/template/bootstrap/bootstrap.html
- panel/template/react/react.css
- panel/template/vanilla/vanilla.css
In https://github.com/holoviz/panel/issues/1742 I noted some template issues. This PR fixes the issues I see when using the `test_manual.py` app to test. This is mainly main height fixes. And then the Bootstrap Template did not support the `main_max_width` parameter.
I have checked both in Chrome and Firefox.
I could not fix the Bootstrap sidebar at `300px` so I did not change that.
I will not do more now. I think this is the most important to fix.
> Template Fixes - Mostly sidebar or main heights

- panel/layout/card.py
fix: https://github.com/holoviz/panel/issues/1750
> [Card] Linkage fix

- panel/layout/grid.py
- panel/template/base.py
- panel/template/react/__init__.py
- panel/tests/test_template.py
Fixes https://github.com/holoviz/panel/issues/1741
> Ensure grid templates support overriding items

- panel/config.py
- panel/viewable.py
It seems like VSCode does not yet like `_repr_mimebundle_` so we add an explicit `pn.config.comms = 'vscode'` that adds special handling to display ipywidgets output in VSCode. In practice I suspect that VSCode will have to fix this issue soon because ipywidgets 8.0 (currently in alpha) switches from `_ipython_display_` to `_repr_mimebundle_`.
> Add support for VSCode

- panel/pane/holoviews.py
- panel/template/base.py
Fixes https://github.com/holoviz/panel/issues/1764
> Apply Template theme to HoloViews plots

- panel/compiler.py
- panel/models/ace.py
Certain extensions (like Ace) require various extraneous files which aren't captured by simply bundling the direct dependencies. This allows bundling the contents of a tarfile.
> Allow bundling contents of tarfiles

- panel/widgets/indicators.py
- panel/widgets/input.py
- Ensures that Dial does not error on None/NaN value
- Ensures that DatetimeRange initializes on start-end range
> Minor widget and indicator fixes

- README.md
- doc/index.rst
- The "Command line" environment previously listed for Panel actually only covers server usage, so this PR changes it to say "Editor + Server" instead.
- What about exporting static HTML? Seems like that ought to be in the list, but I don't know how to tell Panel users how to do it. I myself only do it using nbconvert, but presumably there's a more direct way not involving Jupyter?
- I also put in a section about what to do if your desired environment is not on this list. That may be too much detail, so please pare it down if you think it should say less.
- Presumably these changes, once finalized, should also be reflected into the readme.
> Updated environments docs

- panel/template/base.py
- panel/viewable.py
https://github.com/holoviz/panel/issues/1776
```
import hvplot.xarray
import xarray as xr
pn.extension()
ds = xr.tutorial.open_dataset('air_temperature')
pane = pn.panel(ds.hvplot('lon', 'lat'))
pane.save('test.html', embed=True, progress=True)
```
> Add progress=True

- panel/models/plotly.ts
should fix https://github.com/holoviz/panel/issues/1770
Based on @jonmmease comment I wrapped ploty plot inside a div with height and width set to 100%
I had to call PlotlyPlots.resize on the plotly plot creation for the first resize to work
```python
import plotly.express as px
data = pd.DataFrame([
('Monday', 7), ('Tuesday', 4), ('Wednesday', 9), ('Thursday', 4),
('Friday', 4), ('Saturday', 4), ('Sunay', 4)], columns=['Day', 'Orders']
)
fig = px.line(data, x="Day", y="Orders")
fig.update_traces(mode="lines+markers", marker=dict(size=10), line=dict(width=4))
fig.layout.autosize = True
responsive = pn.pane.Plotly(fig, config={'responsive': True})
pn.Column('# A responsive plot', responsive, sizing_mode='stretch_both').show()
```
> Plotly reactive height

- panel/io/location.py
Fixes #1784
Cc: @Hoxbro Sorry for closing your PR but using param serialization correctly is non-obvious so this was going to result in a quicker turnaround.
> Fix Location sync serialization

- examples/user_guide/Interact.ipynb
- panel/depends.py
- panel/interact.py
- panel/tests/test_interact.py
Supersede #1400 
The goal of this PR is to discuss the option to add a argument to `pn.depends` , `pn.interact` and `pn.bind` which throttles the slider widgets as mention in #1259. 
This is a work in progress and await input from @philippjfr. 
For testing purpose I use this script:
``` python
from datetime import datetime, date
pn.extension()
slider_dict = {
"DateSlider": dict(start=date(2018, 9, 1), end=date(2018, 9, 10)),
"DateRangeSlider": dict(
start=date(2018, 9, 1),
end=date(2018, 9, 10),
value=(date(2018, 9, 2), date(2018, 9, 4)),
),
"DiscreteSlider": dict(
options=[0.1, 1, 10, 100],
value=1,
),
"FloatSlider": dict(start=1, end=10, value=5),
"IntSlider": dict(start=1, end=10, value=5),
"IntRangeSlider": dict(start=1, end=10, value=(2, 5)),
"RangeSlider": …
```
> Add a throttled argument to depends, interact and bind

- examples/reference/panes/Param.ipynb
- panel/param.py
- panel/tests/test_param.py
The reason for this PR it is hard to incorporate `value_throttled` for sliders into a parametrized class. 
This will add the possibility to add a `throttled` argument to pn.param `widgets` argument. So the following is possible:
``` python
import param
class A(param.Parameterized):
value_ = param.Range(
default=(100, 250),
bounds=(0, 250),
)
value_throttled_ = param.Range(
default=(100, 250),
bounds=(0, 250),
)
def __init__(self, **params):
super().__init__(**params)
widgets = {
"value_": pn.widgets.IntRangeSlider,
"value_throttled_": {
"type": pn.widgets.IntRangeSlider,
"throttled": True
},
}
self.controls = pn.Param(self, widgets=widgets)
@param.depends("controls")
def calculation(self):
return self.value_, self.value_throttled_
a = A()
pn.Column(a.controls, …
```
> Add throttled argument to pn.param widgets parameter

- panel/models/file_download.ts
Fixes #1510 and #1820
There seems to have been two problems: The first problem is that Button do not have a `value` property and therefore give the `"Uncaught TypeError: t is undefined"` as mentioned in #1510 and [here](https://github.com/bokeh/bokeh/issues/10345#issuecomment-664407341). 
The second problem was that the change in `disabled` was not connected to the anchor element. 
This is my first time trying to write code in TypeScript, so I think it would be very good if someone with more experience in TypeScript can take a look at it and test that I haven't done something wrong or if there is something which can be done better.
An example of the fix in action can be seen below:
``` python
from io import StringIO
import param
class Download(param.Parameterized): …
```
> Fixing enabling and disabling FileDownload

- panel/command/serve.py
- panel/io/resources.py
- panel/io/state.py
- panel/template/base.py
Fixes https://github.com/holoviz/panel/issues/1821
> Respect Resources.root_url

- .github/workflows/docs.yaml
This should fix the 'right click to download' links in the new interactivity warning.
> Fixes for new nbsite interactivity warning

- panel/layout/base.py
- panel/layout/grid.py
Preprocessors in certain cases can trigger further events which lead to additional preprocessors being called. Since preprocessing happens at the root-level we can simply skip preprocessing until the layout that originally triggered the model update is done updating, ensuring that preprocessing is only run once.
> Avoid recursive preprocessing

- panel/widgets/indicators.py
Currently defining `max` when creating the instance does not change the upper `value` bound. Which leads to a ValueError.
Simply calling the method `_update_value_bounds` in `__init__` fixes the problem.
> Bug fix: make max as upper bound for value

- panel/pane/echarts.py
- panel/tests/pane/test_echart.py
Fixes https://github.com/holoviz/panel/issues/1874
> ECharts depends on sliders fix

- panel/template/base.py
- panel/util.py
While #1821  was partially resolved thanks to #1830 , the template resources were still not loading due to the same path issues. This PR aims to resolve those. Testing in a jupyter_server_proxy env and jupyterlab without proxy seems to work for the changes proposed. 
This allows the following example to work:
```python
pn.extension()
react = pn.template.ReactTemplate(title='React Template')
pn.config.sizing_mode = 'stretch_both'
xs = np.linspace(0, np.pi)
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = pn.widgets.FloatSlider(name="Phase", start=0, end=np.pi)
@pn.depends(freq=freq, phase=phase)
def sine(freq, phase):
return hv.Curve((xs, np.sin(xs*freq+phase))).opts(
responsive=True, …
```
> fix local bundled paths for template resources

- panel/pane/__init__.py
- panel/pane/holoviews.py
- panel/tests/pane/test_base.py
- panel/tests/test_docs.py
Fixes https://github.com/holoviz/panel/issues/1824
> Add hvPlot Interactive pane

- doc/index.rst
> Update website JupyterLab instructions

- panel/io/server.py
- panel/io/state.py
Panel has supported recording information about user sessions for a while. In doing so it recorded three events, 'started', 'rendered' and 'ended'. However the 'started' event was really recording the time after the session had already been created and fully initialized. This adds a fourth key called `'launched'`, which records when the initial request arrives but before the dashboard script has been executed.
This means that we can separately compute execution time (server-side) and time to render since initial request (client-side).
> Distinguish between session creation and execution in session info

- panel/widgets/button.py
When the MenuButton is in split mode and the Button is pressed (not a menu item) the 'event.item' property does not exist in bokeh.event.ButtonClick. I propose to split with a check if it is MenuItemClick, and output as default, or ButtonClick, and output the button name, on 'clicked' parameter
> Fix MenuButton in split mode

- panel/widgets/input.py
Update input.py to add 'multiple' parameter to FileInput
paramenter filename can be a string or a list
parameter mime_type can be a string or a list
_process_property_change accounts for either a string or a list as input for 'msg'
> Multiple files in FileInput

- panel/template/golden/golden.html
- panel/template/material/material.html
- panel/template/react/react.html
- panel/template/vanilla/vanilla.html
Fixes https://github.com/holoviz/panel/issues/1872
> Ensure template header_color and header_background are applied

- examples/reference/widgets/FileInput.ipynb
- examples/reference/widgets/MenuButton.ipynb
- panel/widgets/input.py
Updates `FileInput` docs to explain `multiple` parameter (added in #1911) and the behavior when clicking the button on a `MenuButton` in `split` mode (fixed in #1915).
> Add docs for recent widget changes

- panel/template/base.py
Ensures the template preprocessor is applied to Template roots on initialization.
> Correctly set up preprocessor on Template root

- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
The tabulator wasn't updating the configuration which meant that it wasn't rendering the new data.
> Ensure Tabulator configuration is updated when data changes

- panel/models/tabulator.ts
This caused the CSS theme to be reloaded unneccessarily.
> Ensure Tabulator.theme_url matches in Python and JS

- panel/param.py
- panel/tests/test_param.py
Fixes https://github.com/holoviz/panel/issues/1951
> Switch Param pane widget type when bounds (un)defined

- panel/io/resources.py
Fixes https://github.com/holoviz/panel/issues/1949
> Fix inline resources when saving

- panel/io/location.py
- panel/tests/io/test_location.py
Ensures that if an invalid URL parameter is passed in it does not error and allows user to provide an `on_error` callback function.
> Handle errors when syncing URL parameters

- examples/user_guide/APIs.ipynb
> Document pn.bind in API user guide

- doc/index.rst
- examples/getting_started/Introduction.ipynb
Fixes https://github.com/holoviz/panel/issues/1924
I've added the line below
I cannot remove Python 2.7 mention as the section below is not included in the notebook or Panel repository.
> Add link to installation instructions to getting started guide

- jupyter-config/jupyter_notebook_config.d/panel-client-jupyter.json
- jupyter-config/notebook.d/panel-client-jupyter.json
- panel/__init__.py
- panel/io/__init__.py
- panel/io/jupyter_server_extension.py
- panel/io/notebook.py
- setup.py
In a Bokeh server context we serve the `panel/dist` directory on an endpoint, which makes it possible to load all bundled resources from there, while in the notebook we have to rely on either inlining the resources or loading it from CDN. This PR adds a server extension to Panel, which serves the `panel/dist` directory under a `/panel_dist/` endpoint in Jupyter.
> Add Jupyter server extension to serve files

- panel/models/deckgl.ts
These events were causing serialization errors.
> Skip serializing undefined hover locations in DeckGL pane

- panel/models/vtk/util.ts
- panel/pane/vtk/synchronizable_deserializer.py
- panel/pane/vtk/synchronizable_serializer.py
- panel/pane/vtk/vtk.py
fix fix: https://github.com/holoviz/panel/issues/2001
> [VTK] Implement Glyph3Dmapper serialization  - Round 2

- panel/template/fast/base.py
When testing Panel 0.11.0rc3 I see an unintended behaviour from the FastListTemplate. When setting the theme via a string it sets `theme_toggle` to False. This was never intended. And it will make it difficult for my users of awesome-panel.org and at work to switch the theme.
So I removed the line of code.
> Remove change of theme_toggle

- panel/links.py
- panel/param.py
This means that parameter widgets generated from a Parameterized are jslinked to any reactive methods that depend on those parameters. This means the loading indicator is enabled as soon the widget is changed. 
One good use case is the Gapminder demo which uses a Param based approach and is now automatically jslinked:
> Add preprocessor to link parameter widgets with loading indicators

- panel/io/reload.py
I'm using `panel serve` with the `--auto` flag on awesome-panel locally. When I edit the awesome-panel package (an external package which is installed via `pip install -e`) I get the below error 
```python
File "c:\repos\private\awesome-panel\.venv\lib\site-packages\tornado\ioloop.py", line 905, in _run
return self.callback()
File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\callbacks.py", line 70, in _periodic_callback
self.callback()
File "c:\repos\private\awesome-panel\.venv\lib\site-packages\panel\io\reload.py", line 140, in _reload_on_update
module = sys.modules[module_name]
KeyError: 'awesome_panel'
```
This provides a fix.
> Panel 0.11.0rc4: Auto Reload- Should not get a module_name not in sys.modules

- panel/pane/base.py
- panel/pipeline.py
- panel/viewable.py
Provides a `Viewer` baseclass which can be used to make custom components viewable (i.e. provide `.servable`, `.show` and `_repr_mimebundle_` methods. A user just has to implement ``__panel__``.
Closes https://github.com/holoviz/panel/issues/1979
Fixes https://github.com/holoviz/panel/issues/1981
Fixes  https://github.com/holoviz/panel/issues/1980
> Provide Viewer baseclass

- examples/user_guide/Customization.ipynb
- panel/viewable.py
Somehow missed this entirely, the align property in bokeh has always supported providing a `(horizontal, vertical)` alignment tuple. This merely exposes this ability in Panel.
> Allow setting horizontal and vertical alignment separately

- panel/depends.py
- panel/tests/test_depends.py
Allows binding another dynamic function:
```python
slider = pn.widgets.IntSlider(value=2, start=0, end=10)
slider2 = pn.widgets.IntSlider(value=4, start=0, end=10)
slider3 = pn.widgets.IntSlider(value=2, start=0, end=10)
def add(a, b):
return a + b
def divide(a, b):
return a / b
bound = pn.bind(divide, pn.bind(add, slider, slider2), slider3)
assert bound() == 3
```
> Allow bind to extract dependencies and evaluate other dynamic functions

- panel/widgets/input.py
- panel/widgets/slider.py
Fixes #2082 
**Todo**
@nghenzi can you double check if this fixes all the sliders problems?
@philippjfr  I have taken the liberty to remove `value_throttled` from `__repr__` to avoid confusion.  <s>I will do the todo later today, but you can take over the PR if you need to release 0.11.1 before that and want to include this.</s>
> Fix value_throttled in pn.depends decorator

- panel/models/reactive_html.ts
Fixes https://github.com/holoviz/panel/issues/2095
> Make ReactiveHTML JS model inherit from HTMLBox

- panel/pane/media.py
- panel/tests/pane/test_media.py
Fixes #2105
The object parameter is not found when running `self._process_param_change(self._init_params())` in `pn.pane.media._MediaBase` because it inherits from `PaneBase` which sets `_rerender_params = ['object']` and ignores it in `self._synced_params`.
The solution I have done is to add it to props afterwards if it is not None. Another way could be to remove it from `_rerender_params` but I have a feeling this will properly break something.
> Fix missing video in pn.pane.Video

- panel/template/bootstrap/bootstrap.html
- panel/template/fast/grid/fast_grid_template.html
- panel/template/fast/list/fast_list_template.html
- panel/template/golden/golden.html
- panel/template/material/material.html
- panel/template/react/react.html
- panel/template/vanilla/vanilla.html
Fixes a template that looks like 
If this could be a part of Panel 0.11.2 it would be much appreciated :-)
> Add missing end tag in Templates

- panel/template/fast/base.py
I was updating my site to Panel 0.11.1 and suddenly the menu looks like shown below.
I investigate and realize its bootstrap css that sets the header size. WTF?
I investigate and find out it because the css of the ReactTemplate is used in the FastGridTemplate and it contains bootstrap. Oh no.
If this could be a part of a 0.11.2 release it would be highly appreciated.
> Remove bootstrap css from FastGridTemplate

- panel/layout/base.py
Makes the inheritance hierarchy a little nicer allowing other components to inherit `NamedListLike` behavior without explicitly subclassing the `NamedListPanel` class, which also includes a lot of functionality related to rendering child models.
> Factor out NamedListLike baseclass

- panel/tests/widgets/test_misc.py
- panel/widgets/indicators.py
Fixes #2080
By setting the value to -1 the progress bar is empty. 
```python
progress1 = pn.widgets.indicators.Progress(value=-1, active=False)
progress2 = pn.widgets.indicators.Progress(value=-1, active=True)
progress3 = pn.widgets.indicators.Progress(value=0, active=False)
progress4 = pn.widgets.indicators.Progress(value=0, active=True)
progress = pn.Column(progress1, progress2, progress3, progress4)
progress.servable()
```
https://user-images.githubusercontent.com/19758978/111211562-d5b38000-85ce-11eb-9da4-e0ec5c179216.mp4
> Add empty progress bar

- panel/reactive.py
Could not reset the selection in a callback since the `_updating` check prevented changes.
> Fix updating of selection property

- panel/models/perspective.py
- panel/models/perspective.ts
- panel/pane/perspective.py
Ensures that Perspective handles datetime and other dtypes correctly and also handles pandas (multi-)indexes and column pivots.
Fixes https://github.com/holoviz/panel/issues/2124
```python
data = pd.DataFrame({
"int": np.arange(100),
"float": [i * 1.5 for i in range(100)],
"bool": [True for i in range(100)],
"date": [date.today() for i in range(100)],
"datetime": [datetime.now() for i in range(100)],
"string": [chr(64+i) for i in range(100)]
})
pn.pane.Perspective(
data, sizing_mode='stretch_width', height=400
)
```
> Serialize Perspective schema

- jupyter-config/jupyter_notebook_config.d/panel-client-jupyter.json
- panel/io/jupyter_server_extension.py
- panel/pane/idom.py
- pyproject.toml
NOTE: The version of IDOM for which these changes would apply has not been released yet.
@philippjfr thoughts on using [`packaging`](https://pypi.org/project/packaging/) to do a runtime check to ensure the installed version of IDOM is compatible?
I also had a bit of difficulty getting the panel Jupyter server extension to work:
```
$ jupyter serverextension list
config dir: /home/ryan/Code/rmorshea/panel/venv/etc/jupyter
jupyterlab  enabled 
- Validating...
jupyterlab 3.0.11 OK
panel  enabled 
- Validating...
X is panel importable?
config dir: /usr/local/etc/jupyter
jupyterlab  enabled 
- Validating...
jupyterlab 3.0.11 OK
```
> configure IDOM_CLIENT_IMPORT_SOURCE_URL

- panel/tests/conftest.py
- panel/tests/widgets/test_file_selector.py
Replaced all instances of ```@pytest.yield_fixture``` which is deprecated with ```@pytest.fixture``` in this PR.
Fixes Issue #2142
> Fix Issue #2142: Use of pytest.yield_fixture is deprecated

- panel/models/player.ts
- panel/models/widgets.py
Fixes #2140 
If default parameters is not set, it sees 0 as Null. Default values are the same as the widgets.
> Fixes widget player loop when start is 0

- panel/models/json.ts
- panel/pane/markup.py
- panel/tests/pane/test_markup.py
Fixes #1798
Trying to use `literal_eval` for the `object` and then `json.dumps`. This PR also makes it possible to be more flexible with the `object`. 
The only thing I'm not completely sure about is if overlook something with the removal of `.replace(/(\r\n|\n|\r)/gm, "")`. 
```python
json1 = pn.pane.JSON(object={"test": "can't show this"})
json2 = pn.pane.JSON(object=["can't show this"])
json3 = pn.pane.JSON(object="can't show this")
json4 = pn.pane.JSON(object="can show this")
json5 = pn.pane.JSON(object='{"b": 3}')
json6 = pn.pane.JSON(object="{'b': 3}")
pn.Column(json1, json2, json3, json4, json5, json6).servable()
```
| Without the PR | With the PR (`literal_eval`)|With the PR (`json.loads`)
|--------|-------|-------|
|![2021-04-04 …
> Updated json pane to accept single quote

- panel/layout/grid.py
The `GridSpec` override logic matched overlaps for each cell which meant that the same item could be recorded for deletion multiple times which could fail. We now deduplicate the matches using a `set` operation and to be sure made the deletion robust to a `KeyError`.
Fixes https://github.com/holoviz/panel/issues/2106
> Ensure GridSpec override handles duplicate matches

- pyproject.toml
Fixes https://github.com/holoviz/panel/issues/1995
> Specify pip build backend

- panel/command/serve.py
- panel/io/resources.py
- panel/io/server.py
- panel/io/state.py
- panel/template/base.py
- panel/tests/test_server.py
Handles relative paths to static resources in all cases including:
1. Bokeh CSS and JS files
2. Panel CSS and JS files
3. Panel model JS and CSS dependencies  
4. Template CSS and JS files
5. User defined CSS and JS files
> Improve handling of server prefix

- panel/models/tabulator.ts
Fixes https://github.com/holoviz/panel/issues/2157
> Fix Tabulator ajax call on empty data

- panel/template/base.py
Ensures the bokeh theme is applied to HoloViews plots even when they are not added on initialization.
> Fix apply of bokeh_theme in BasicTemplate

- examples/reference/panes/Bokeh.ipynb
Updated the Bokeh pane reference notebook to include information about themes.
Based on my testing, and seemingly unrelated to these changes, the last cell of the notebook does not render anything using the master branch of panel and bokeh 2.3.1, but does work in an environment with panel 0.10.3 and bokeh 2.2.3.
> Bokeh theme reference

- panel/widgets/slider.py
Fixes #2204
The error in #2204 was related to a missing `edit_constant` and the possibility of multiple events in `_sync_value`, which should now be fixed for the three editable sliders.
When looking / testing the editable sliders I could not get `value_throttled` to work with the `_input_widget`. To fix this, I changed the communication from `jscallback` to `param.watch`. Furthermore, I don't completely understand why in the current design it is possible to exceed the limit of the bounds with the _input_widget like
| Current | This PR |
| ----| ----|
|![before](https://user-images.githubusercontent.com/19758978/115147393-0a49aa00-a05b-11eb-91f5-978323f6af98.gif)| ![after](https://user-images.githubusercontent.com/19758978/115147398-0d449a80-a05b-11eb-9501-eef50b9c42a9.gif)|
I would …
> Fix of value_throttled in editable sliders

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
- panel/widgets/tables.py
The old table had a more intuitive selection behavior which used Ctrl/Meta keys to toggle selection of multiple rows and the shift key for range selection. The Tabulator has a default behavior where clicking on rows simply toggles selection on and off. This changes the Tabulator selection behavior to be consistent with the old behavior but also allowing users to toggle the previous behavior by setting `selectable='toggle'`.
Fixes https://github.com/holoviz/panel/issues/2089
> Improve and standardize selection behavior of Tabulator

- examples/reference/layouts/FlexBox.ipynb
- panel/__init__.py
- panel/layout/__init__.py
- panel/layout/flex.py
- panel/layout/flexbox.html
- panel/reactive.py
- setup.py
Adds a `FlexBox` layout container which is the first ReactiveHTML based layout component added to panel. Exposes the power of CSS flex boxes in panel, which unlike our other containers responsively wrap depending on the size of the contents and the container.
> Add FlexBox layout

- panel/models/tabulator.ts
- panel/widgets/tables.py
Currently resetting a selection in a server side callback does not work.
> Fix server-side Tabulator selection changes

- panel/models/vtk.py
- panel/models/vtk/util.ts
- panel/models/vtk/vtklayout.ts
- panel/pane/vtk/enums.py
- panel/pane/vtk/synchronizable_serializer.py
- panel/pane/vtk/vtk.py
```python
plotter = pv.Plotter(shape=(2, 2))
plotter.subplot(0, 0)
plotter.add_text("Render Window 0", font_size=30, position="upper_edge")
plotter.add_text("Upper_Left", font_size=20, position="upper_left", color=(1,1,1))
plotter.add_text("Upper_Right", font_size=20, position="upper_right", color="green")
plotter.add_text("Lower_Left", font_size=20, position="lower_left", color="blue")
plotter.add_text("Lower_Right", font_size=20, position="lower_right", color="red")
plotter.add_mesh(examples.load_globe())
plotter.subplot(0, 1)
plotter.add_text("Upper_Edge", font_size=20, position="upper_edge")
plotter.add_text("Lower_Edge", font_size=20, position="lower_edge", font="courier")
plotter.add_text("Left_Edge", font_size=20, position="left_edge", font="times")
plotter.add_text("Right_Edge", …
```
> Add support for vtkCornerAnnotations

- panel/models/tabulator.ts
- panel/widgets/tables.py
Patches ajax requests handling during initialization of the Tabulator so no request is **ever** sent and ensures Tabulator initialized with None works when paginated.
> Improve request handling for remote pagination on Tabulator

- panel/param.py
- panel/tests/test_param.py
As the title says, (re)setting the precedence to None triggered an error. It now correctly renders the widget.
> Allow setting Param precedence to None

- examples/user_guide/Custom_Components.ipynb
- panel/models/reactive_html.py
- panel/reactive.py
- panel/tests/test_reactive.py
Allows making use of loop variables instead of the more cumbersome indexing syntax, e.g. this:
```python
class Select(ReactiveHTML):
options = param.List(doc="Options to choose from.")
value = param.String(doc="Current selected option")
_template = """
<select id="select" value="${value}">
{% for obj in options %}
<option id="option-{{ loop.index0 }}">${objects[{{ loop.index0 }}]}</option>
{% endfor %}
</select>
"""
```
Can now be written as:
```python
class Select(ReactiveHTML):
options = param.List(doc="Options to choose from.")
value = param.String(doc="Current selected option")
_template = """
<select id="select" value="${value}">
{% for obj in options %}
<option id="option">${obj}</option>
{% endfor %}
</select>
"""
```
> Allow using loop variables in ReactiveHTML templates

- panel/models/tabulator.ts
By default Tabulator uses `.` as the nested field separator, which means that any columns containing periods will be treated as a nested field. Since we do not support nested fields anyway we simply disable this.
> Disable nested field separators on Tabulator

- panel/config.py
Adding a parameter called kwargs to any Panel component currently errors when loading the extension because it will clash with the additional VAR_KEYWORD that is added to the signature.
> Allow kwargs parameter name in signature

- panel/reactive.py
The `controls` methods provides widgets to control a component but cannot be easily customized. This allows passing through kwargs to the Param pane which generates the controls.
> Expose Reactive.controls kwargs

- README.md
If you want users to use the `master` branch for Panel on Binder you need this change.
> Change branch of binder link

- doc/developer_guide/index.rst
Addresses #2318
Adds a section called *Useful Links* to help developers navigate to relevant resources.
> Add useful links to developer docs

- README.md
Not sure what the intended link was but it isn't working right now so I'm proposing what I think was supposed to be the target...
> Fixed broken link in gh-actions badge

- panel/models/reactive_html.py
- panel/reactive.py
> Improve validation for ReactiveHTML validation

- panel/dist/css/card.css
- panel/layout/card.py
- panel/models/card.ts
The Card css was somewhat brittle and I did not much like the old +/- indicators for uncollapsed/collapsed states respectively. This PR changes the styling to use arrows as indicators instead and makes the CSS less brittle:
> Simplified styling of Card layout

- panel/param.py
In certain cases a parameter might trigger a change which either was defined dynamically or was not rendered as a widget. These changes should not break the Param pane.
> Fix for Param pane updates to unknown parameter

- panel/config.py
- panel/tests/conftest.py
- panel/tests/test_config.py
The `config` object was already quite complicated because it had to handle these fallback conditions (in order):
- Getting an explicitly overridden value
- Getting the value from a environment variable
- Getting the default value
This PR additionally adds a `_session_config` dictionary which is used to store explicitly overridden config values. Instead of complicating all the property logic further this PR adds `__getattribute__` and `__setattr__` implementations which catch attempts to get and set explicit overrides. The properties therefore only have to implement lookups to get the value from the env variable or the default.
Fixes https://github.com/holoviz/panel/issues/2350
> Refactored config to hold per session state

- panel/compiler.py
- panel/io/resources.py
Allows a `ReactiveHTML` component to declare `__css__` and `__javascript__` like ordinary Bokeh models, which can be bundled and loaded as part of the resource bundle.
> Allow bundling and loading JS and CSS for ReactiveHTML components

- examples/reference/layouts/GridStack.ipynb
- panel/config.py
- panel/layout/grid.py
- panel/layout/gridstack.py
- panel/models/reactive_html.py
- panel/reactive.py
A `GridStack` layout is largely equivalent to a `GridSpec` however it also has the ability to interactively resize and drag around individual components in the grid.
> Implement GridStack layout

- panel/template/fast/css/fast_root.css
Fixes https://github.com/holoviz/panel/issues/2369
```python
slider = pn.widgets.FloatSlider(value=2, start=0, end=10, step=0.1)
pn.template.FastListTemplate(site="Panel", title="FloatSliderFix", sidebar=[slider]).servable()
```
> add slider horizontal bar back

- panel/models/reactive_html.py
- panel/models/reactive_html.ts
- panel/reactive.py
Children which are declared as literals are now synced via the `DataModel` and no longer trigger a full rerender.
> Improve rendering of ReactiveHTML literal children

- panel/template/bootstrap/bootstrap.css
Sidebar would simply get cut off if it was too large.
> Fix sidebar scrolling in BootstrapTemplate

- examples/user_guide/Custom_Components.ipynb
- panel/io/resources.py
- panel/models/reactive_html.ts
- Deduplicate ReactiveHTML resources
- Add example using external resources
> Improved handling of ReactiveHTML resources

- panel/models/reactive_html.py
`ReactiveHTML` can now serialize `param.DataFrame` and `param.Array` types efficiently.
> Support serialization of binary types on ReactiveHTML

- panel/models/reactive_html.ts
`ReactiveHTML` now no longer applies the position and sizing computed by the bokeh layout manager instead relying on pure CSS layouts.
> Switch to unmanaged layout in ReactiveHTML

- examples/user_guide/Overview.ipynb
- examples/user_guide/Templates.ipynb
- panel/config.py
- panel/io/server.py
- panel/io/state.py
- panel/template/__init__.py
- panel/template/base.py
- panel/viewable.py
Allows setting a global template via `pn.config` and adding to the template via `.servable`. This will be particularly handy for notebooks where you construct and view individual components while also allowing you to place them in the appropriate places in the template.
```python
pn.extension(
theme='dark',
template='material',
sizing_mode='stretch_width'
)
xs = np.linspace(0, np.pi)
def sine(freq, phase):
return hv.Curve((xs, np.sin(xs*freq+phase))).opts(
responsive=True, min_height=400, title="Sine")
def cosine(freq, phase):
return hv.Curve((xs, np.cos(xs*freq+phase))).opts(
responsive=True, min_height=400, title="Cosine")
freq = pn.widgets.FloatSlider(name="Frequency", start=0, end=10, value=2)
phase = …
```
> Add ability to configure global template

- panel/models/reactive_html.ts
- panel/reactive.py
- Do not compute managed layout unless your parent is a managed layout
- Do not set managed layout position unless your parent is a managed layout
- Error if any tag in the template is unclosed
> Ensure ReactiveHTML correctly interfaces with managed layouts

- panel/template/fast/css/fast_root.css
- panel/template/fast/grid/fast_grid_template.css
- panel/template/fast/list/fast_list_template.css
- panel/template/theme/dark.css
Fixes https://github.com/holoviz/panel/issues/2416 by setting a reasonable height for the horizontal scrollbar.
```python
spacer = pn.Spacer(background="#FFEEFF", height=500, width=2500, sizing_mode="fixed")
scroll_container = pn.Row(spacer, scroll=True)
pn.template.FastListTemplate(title="Scroll Issue",main=[scroll_container]).servable()
```
> fix vertical scrollbar in fast templates

- panel/pane/plotly.py
- panel/tests/pane/test_plotly.py
Uses JS callbacks to ensure that Plotly panes displayed inside Tabs are hidden when the tab they are in is not active. This ensures that interactivity on the plots still works even when they are overlapping.
Fixes #804
> Ensure Plotly interactivity works when Plotly panes are displayed in tabs

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
- panel/reactive.py
- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
- Adds `selectable='checkbox-single'` option to disable (de)select-all in the header
- Add `selectable_rows` parameter which accepts a function which should return the indexes of the selectable rows given a DataFrame.
> Add ability to make only certain Tabulator rows selectable

- panel/template/fast/css/fast_panel.css
Fixes #2379 as well as unreported height and margin issue discovered during testing.
```python
d = pn.Card(pn.widgets.FloatSlider(name='Slider'),'#Hola')
e = pn.Card(pn.widgets.FloatSlider(name='Slider'),'#Hola', header="Text")
f = pn.Card(pn.widgets.FloatSlider(name='Slider'),'#Hola', header="# Text")
tmpl = pn.template.FastListTemplate(
theme=pn.template.DarkTheme,
main=[d,e,f]
)
tmpl.servable()
```
> Fix Card Header in Fast Templates

- panel/viewable.py
Fixes https://github.com/holoviz/panel/issues/1059
> Improve config.sizing_mode behavior

- panel/io/save.py
- panel/tests/io/test_save.py
Fixes https://github.com/holoviz/panel/issues/2367
> Ensure external resources are configured correctly on save

- panel/links.py
- panel/models/reactive_html.py
- panel/reactive.py
The `ReactiveHTML` implementation also included the ability to generate a `DataModel` for a `Parameterized` object. Since we already implemented this, we should also provide for the ability to set up bi-directional linking between Parameterized objects and other components. By adding a helper function called `create_linked_datamodel` which creates a Bokeh DataModel and links it to the provided Parameterized object we can easily support this usecase.
> Support jslinking Parameterized class

- panel/config.py
- panel/io/server.py
- panel/tests/test_server.py
While I recently added support for per-session state on `pn.config` this didn't fully work for the resource related parameters such as `css_files`, `js_files` etc. because a) they are mutable so they need to create entries on access and b) while the session handler is running `state.curdoc` was not set to the correct value.
> Ensure config per session state works for resources

- panel/widgets/tables.py
Ensures that an error in the styler doesn't break the Tabulator entirely
> Ensure Tabulator styler doesn't break

- panel/widgets/slider.py
Thanks @jbednar for catching this.
> Fix RangeSlider value_start/value_end readonly

- panel/template/base.py
Turns out template preprocessing was broken because the fake children were never actually inserted on the root.
Fixes https://github.com/holoviz/panel/issues/2473
> Fix Template preprocessors

- examples/reference/layouts/Tabs.ipynb
- panel/param.py
Fixes https://github.com/holoviz/panel/issues/1933
> Demonstrate lazy tabs

- examples/reference/panes/JPG.ipynb
Wikipedia was restricting access to the old examples somehow
> Fix JPG example

- panel/config.py
Recent changes to config meant that the resources defined in a notebook would not carry over when launching a server using `.show` and `pn.serve`.
> Ensure server launched from notebook inherits config

- panel/template/fast/css/fast_panel.css
Fixes #2487 
Now looks like
when running the script
> Improve codehilite look and feel in Fast Templates

- panel/models/videostream.ts
Fixes https://discourse.holoviz.org/t/videostream-does-not-show-video-after-setting-paused-to-false/2525.
I.e. you can pause and the un-pause again.
https://user-images.githubusercontent.com/42288570/124864463-3705c180-dfb9-11eb-927e-021ebd0d43d7.mp4
```python
import time
pn.extension()
video = pn.widgets.VideoStream(timeout=100, paused=False)
pn.Column(video, video.param.paused).servable()
```
> fix videostream unpause

- panel/pane/perspective.py
I noticed at work that when I drag a column to the "Filter" it raises errors.
I can see its because the fix applied to the `_process_property_change` in #2300 needs to be applied to the `_process_param_change` method as well.
Because of #2518 I'm not able to show the behaviour before and after this fix is applied
@philippjfr . Is it possible to get this in Panel 0.12?
> Fix Perspective Filter Errors

- panel/io/location.py
The serialised value was never actually captured, which would invariably lead to JSON serialisation errors for any value other than a simple string
> Fix broken serialisation in panel.io.location

- panel/layout/tabs.py
- panel/links.py
- panel/models/reactive_html.py
- panel/models/reactive_html.ts
- panel/reactive.py
- panel/tests/layout/test_tabs.py
- panel/tests/test_reactive.py
- panel/tests/test_server.py
This means that ReactiveHTML objects can now declare parameters of type `ClassSelector(class_=Parameterized)` which are automatically reflected as DataModels on the JS side and automatically synced.
> Allow nested parameterized objects on ReactiveHTML

- panel/models/tabulator.ts
Scroll automatically to the selected rows when the selection is updated,
just like the DataFrame widget.
Closes #2485
> Scroll on Tabulator selection

- panel/io/reload.py
When autoreload detects a modified file it clears out the `sys.modules` and then reloads just the session that detected the changed file. Subsequent sessions that try to detect the changed file will then no longer find the changed module in the `sys.modules` (meaning they can't detect a change), or they will find that the already restarted sessions has already repopulated `sys.modules`  and delete that newly loaded module (which will potentially break the already restarted session). In the new setup whenever **any** session detects that a module was changed it immediately halts the watchers on other threads and then reloads **all** sessions.
This has the potential to fail for sessions that do not have a frontend connected (since the reload mechanism is triggered by refreshing the browser …
> Fix race condition in autoreload

- panel/template/fast/grid/fast_grid_template.html
- panel/template/fast/list/fast_list_template.html
This addresses #2184 
You can test manually via `python script.py` the below 
```python
SITE="Awesome Panel"
TITLE="Fast Panel App"
LOGO="https://panel.holoviz.org/_static/logo_stacked.png"
SIDEBAR=["## Settings"]
MAIN=["## Hello Main"]
ROUTES = {
"111": pn.template.FastListTemplate(logo=LOGO, site=SITE,title=TITLE, sidebar=SIDEBAR, main=MAIN),
"110": pn.template.FastListTemplate(logo=LOGO, site=SITE, sidebar=SIDEBAR, main=MAIN),
"101": pn.template.FastListTemplate(logo=LOGO,title=TITLE, sidebar=SIDEBAR, main=MAIN),
"011": pn.template.FastListTemplate(site=SITE, title=TITLE, sidebar=SIDEBAR, main=MAIN),
"100": pn.template.FastListTemplate(logo=LOGO, sidebar=SIDEBAR, main=MAIN),
"010": pn.template.FastListTemplate(site=SITE, sidebar=SIDEBAR, main=MAIN),
"001": …
```
> fix #2184: logo issue

- panel/io/notebook.py
Fixes #2571
@philippjfr . If you want to support `None` exports values. C.f. https://github.com/holoviz/panel/issues/2571#issuecomment-886083634 then I or you would have to change line 93 below and maybe more
But this fix is ok for me.
> support packages in config of _autoload_js cf. #2571

- panel/template/fast/grid/fast_grid_template.html
- panel/template/react/react.html
Fixes #2579
In the below video the LocalStorage contains a persisted layout. As you can see it's now only used when `save_layout=True`.
https://user-images.githubusercontent.com/42288570/127118887-4d22ce74-cd07-46e1-be8a-e2d7995c49ab.mp4
FYI. @nghenzi and @syamajala I've also added this change to the `ReactTemplate`. Please review if you can find the time. Thanks.
> FastGridTemplate: Don't use persisted layout if save_layout=False

- panel/layout/flex.py
Fixes some issues with the FlexBox container not resizing when the flex box reflows.
> Invalidate FlexBox parent layout after resize

- panel/compiler.py
Various debuggers and browser consoles look for sourcemap files which were previously not bundled. This raised errors in the JS console which would be distracting and cause users to think there was something wrong. During the bundling step we now simply try to make a request to the CDN to check if there's a `.map` file that we should bundle alongside the CSS and JS files.
> Bundle .map files during build

- panel/template/fast/grid/fast_grid_template.html
- panel/template/react/react.html
Fixes #2576
Technically I reset the layout of the component/ models by refreshing the page. I don't know if it is possible just to trigger a full relayout using bokeh layout engine?
https://user-images.githubusercontent.com/42288570/127115347-02e3ef7a-e897-48c2-b5b8-ad4f088a200f.mp4
FYI. @nghenzi and @syamajala. I've also updated this for the `ReactTemplate`. Please take a look if you can find the time.
> Reset Models/ Components when resetting layout (#2576)

- panel/command/serve.py
Makes sure that if there are memory spikes when warming up a session they are cleaned up immediately and don't accumulate until we are done warming up.
> Ensure each session is cleaned up after it is warm

- panel/template/fast/css/fast_root.css
Implements https://github.com/holoviz/panel/issues/2604
If you run the script in #2604 you get the nice active "ML Explainability" visually identified as active
> Add CSS for active item of menu in Fast Template #2604

- panel/template/fast/css/fast_bokeh_slickgrid.css
Fixes #2613, I.e. gives the index column the right background color in Fast Templates when using dark theme
Still looks fine in default theme
```python
pn.extension()
from holoviews import opts, streams
from holoviews.plotting.links import DataLink
hv.extension('bokeh')
curve = hv.Curve(np.random.randn(10).cumsum()).opts(responsive=True, line_width=6)
table = hv.Table(curve).opts(editable=True)
component=pn.pane.HoloViews(table, height=500, sizing_mode="stretch_both")
pn.template.FastListTemplate(title="Table", main=[component]).servable()
```
> fix slick grid index column background in Fast Templates

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/2619
> Implement hierarchical aggregation for Tabulator

- binder/postBuild
- panel/io/jupyter_server_extension.py
I would like to enable jupyterlab preview on binder.
When it works it should be available at https://mybinder.org/v2/gh/holoviz/panel/jupyterlab-preview-on-binder?urlpath=lab/tree/examples
> Enable jupyterlab preview on binder

- panel/reactive.py
Fixes #2631. Probably also needed for #2597 to work in practice.
I don't know if
- There are any side effects. For example is it always good to `_apply_update` if  `self._models.items()` has changed?
- It would be more efficient to use `.copy` instead of `list`? But according to https://www.geeksforgeeks.org/python-cloning-copying-list/ list seems like an efficient solution. And using `list` is also what is mostly recommended here https://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error.
> Fix #2631 - handle RuntimeError: dictionary changed size during iteration

- panel/param.py
- panel/tests/test_param.py
Instead of simply disabling the parameters this option allows you to hide it.
> Add option to hide constant parameters

- panel/config.py
In some cases the `config.{js/css}_files` were not given distinct containers per session. This fix ensures the containers are copied before they are set on config.
> Ensure sessions get distinct files in config

- panel/widgets/indicators.py
In some circumstances the Trend indicator `.data` was overwritten with the model.
> Fix bug when updating Trend data

- panel/io/model.py
- panel/io/server.py
- panel/pane/plot.py
- panel/reactive.py
- panel/viewable.py
Should remove this once we explicitly require >=2.4.
> Fix compatibility with bokeh 2.4 DocumentCallbackManager

- panel/models/reactive_html.ts
Fixes https://github.com/holoviz/panel/issues/2681
> Unescape child literal HTML in ReactiveHTML

- panel/io/reload.py
Fixes errors like
```bash
KeyError: 'analytics_workspace.mail'
2021-08-31 13:15:55,562 Error thrown from periodic callback:
2021-08-31 13:15:55,562 Traceback (most recent call last):
File "c:\repos\analytics-workspace\aw-lib\.venv\lib\site-packages\tornado\gen.py", line 526, in callback
result_list.append(f.result())
File "c:\repos\analytics-workspace\aw-lib\.venv\lib\site-packages\bokeh\server\session.py", line 67, in _needs_document_lock_wrapper
result = func(self, *args, **kwargs)
File "c:\repos\analytics-workspace\aw-lib\.venv\lib\site-packages\bokeh\server\session.py", line 195, in with_document_locked
return func(*args, **kwargs)
File "c:\repos\analytics-workspace\aw-lib\.venv\lib\site-packages\bokeh\document\document.py", line 1212, in wrapper
return …
```
> Fix keyerror when reloading

- panel/models/plotly.ts
Fixes https://github.com/holoviz/panel/issues/1514
I've implemented the fix and tested that it works
https://user-images.githubusercontent.com/42288570/131785863-c23d5c29-0eea-4292-b594-e38965f58220.mp4
> Make Plotly pane resize when window resizes

- panel/tests/widgets/test_slider.py
- panel/widgets/base.py
> Editable sliders' `name` can be changed

- panel/io/callbacks.py
- panel/util.py
Small fix for periodic callbacks which don't have a `__name__` attribute.
> Ensure PeriodicCallback robustly logs the function name

- panel/io/admin.py
When running multiple processes or running in a load balanced setup not all requests may arrive on the same server. This ensures that the timeline graph is robust to that.
> Ensure admin timeline is robust to load balance setup

- panel/pane/plotly.py
- panel/tests/pane/test_plotly.py
> fix-plotly-mapbox-relayout

- panel/reactive.py
- panel/tests/test_reactive.py
Fixes https://github.com/holoviz/panel/issues/2715
> Support assignment operators in ReactiveHTML scripts

- panel/io/callbacks.py
Fixes  https://github.com/holoviz/panel/issues/2736
> Fix support for async functions on pn.state.add_periodic_callback

- panel/io/server.py
- panel/tests/test_server.py
Fixes https://github.com/holoviz/panel/issues/2726
Patch bokeh to get `.show()` to work again, this is possibly due to https://github.com/bokeh/bokeh/pull/11531.
> Patch bokeh create_static_handler

- doc/developer_guide/index.rst
I don't know exactly which python version we support. But at least we don't support python 2.7 anymore. I figured we support the ones that we test so it 3.7, 3.8, 3.9.
I saw this because I'm reinstalling panel. Cannot `panel serve`. Something about missing `doc` `_callbacks` again.
> Correct supported python versions

- panel/tests/test_util.py
- panel/util.py
> Added check for bool in parse_query

- panel/pane/__init__.py
- panel/pane/image.py
- panel/template/base.py
- panel/tests/pane/test_image.py
- panel/tests/test_docs.py
Added a `ICO` class to `pane.image` and `pathlib` conversion to pane.image and favicon in templates.
> Adding ICO and pathlib support for image

- panel/pane/base.py
- panel/tests/test_viewable.py
Resolves #2768
I don't know if there should be a more advanced unit test involving calling `pn.serve`.
> pn.viewable.Viewer can now be used with pn.serve

- .github/workflows/docs.yaml
- doc/conf.py
This sphinx extension adds a button for easily copying code snippets: https://sphinx-copybutton.readthedocs.io/en/latest/.
@philippjfr would you like me to try to build the site locally?
> Add sphinx-copybutton to the docs build

- panel/io/save.py
- panel/tests/io/test_save.py
Fixes https://github.com/holoviz/panel/issues/2790
> Resolve issues with inline resources on save

- panel/models/plotly.ts
The `Plotly.resize` function has some issues in that it throttles so we use `Plotly.relayout` instead. Additionally since the `after_layout` call often occurs before the plot has finished rendering we need to make sure that the bokeh layout engine does not overrride the explicit sizes set by us so we reapply those sizes with `set_size` in `after_layout`. The PR also cleans up some code and converts the `plot` and `render` methods into async methods simplifying some of the code.
> Improve Plotly responsive sizing behavior

- panel/pane/vega.py
This fix the following bug with data passed to `pn.pane.Vega`.
```py
dataset = [{"id": 1}, {"id":2, "parent": 1}, {"id": 3, "parent": 1}]
```
The sample dataset that work in Vega examples works in Panel.
Panel app will crash with `KeyError`.
The list of keys are extracted from the first item in the dataset only. (`["id"]` when it should be `["id", "parent"]`),
This has to assume that all items in the dataset has the exact same fields, which is not always the case.
Therefore, when iterating through the 2nd and 3rd item, it cannot find `data["parent"]` to append the value to and  throw `KeyError`.
Iterate through all items and compute the list of unique keys first.
> fix(vega): allow data item to miss optional field

- examples/reference/widgets/Tabulator.ipynb
- panel/widgets/tables.py
It works exactly as `text_align`, by accepting either a string or a dictionary. I didn't see any option to do that for the Bokeh table, so it's just implemented for the Tabulator widget.
Also didn't find any other way to set the header alignment with the current implementation, but happy to close this PR if there's already a way!
> Add a header_align parameter to the Tabulator widget

- examples/user_guide/Param.ipynb
- panel/param.py
- panel/tests/test_param.py
Fixes https://github.com/holoviz/panel/issues/1460
I did not integrate `AutoCompleteInput` into the *Select* model as suggested in the issue since its model is actually halfway through a text input (the value doesn't have to be one of the options with `restrict=False`) and a select widget.
> Allow to set AutoCompleteInput in a Param pane

- panel/models/terminal.py
- panel/models/terminal.ts
- panel/widgets/terminal.py
Syncs the terminal ncols and nrows and applies them to the subprocess tty ensuring that the pseudo-terminal respects the actual size. Also overhauls the way keystrokes are captured avoiding issues with repeat keys.
> Improve Terminal keystroke and size handling

- panel/widgets/terminal.py
Thanks @philippjfr for the recent fixes to the Terminal widget! And here is another one...
When the subprocess output is in ASCII range, the unicode characters are one byte which means you can read any length of bytes from the file descriptor and decode. When you are out the range, the characters can be two bytes long. This resulted in unicode decode errors for any subprocess using more of UTF8 than just ASCII.
This PR fixes this by trying to decode and reading an extra byte on failure and trying to decode that (and one more time). I no longer get any decode errors without needing to use 'ignore' to drop bytes that can't be decoded.
> Fixed UTF-8 decoding in Terminal widget

- examples/reference/panes/Vega.ipynb
- panel/models/vega.py
- panel/models/vega.ts
- panel/pane/vega.py
Should consider which other VegaEmbed options to expose or whether to simply let users provide a config dictionary. 
Implements https://github.com/holoviz/panel/issues/2821
> Add support for configuring Vega output

- panel/models/tabulator.ts
On scroll we have to update styles since Tabulator employs progressive rendering (i.e. cells are only rendered when they are in view plus some offset).
Fixes https://github.com/holoviz/panel/issues/2851
> Update Tabulator styles on scroll

- doc/_templates/layout.html
The pydata_sphinx_theme removed the `prev_next` macro was removed in favor of an `include`.
> Update pydata template for compatibility

- panel/layout/tabs.py
- panel/models/plotly.py
- panel/models/plotly.ts
- panel/pane/plotly.py
- panel/tests/pane/test_plotly.py
Use visibility CSS property to hide Plotly outputs in hidden tabs ensuring that it still participates in the layout.
> Fix handling of Plotly pane in Tabs

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
In many applications it is important to know which specific cell was updated, e.g. so you can make an atomic update to a database without having to sync the entire table.
> Implement Tabulator.on_edit callbacks

- examples/reference/panes/DataFrame.ipynb
- panel/pane/markup.py
- panel/tests/pane/test_markup.py
Adds the functionality requested in https://github.com/holoviz/panel/issues/2889
For example you can create an example like
```python
source = pd.DataFrame({
"country": ["DE", "DK", "DE", "DK"],
"date": ["2021-10-01", "2021-10-01","2021-10-02", "2021-10-02"],
"value": [1,2,3,4]
})
target = source.copy()
target["value"]="<a href='?country=" + target["country"] + "&date=" + target["date"] + "'>" + target["value"].astype(str) + "</a>"
target = target.pivot(index="country", columns="date", values="value").reset_index()
target.columns.name=""
table = pn.pane.DataFrame(target, escape=False, index=False)
table.servable()
```
https://user-images.githubusercontent.com/42288570/140637284-00513b3f-2a84-4296-9233-627cdfd5 …
> Adds escape parameter to DataFrame pane to enable using html markup

- panel/param.py
- panel/tests/test_param.py
- panel/widgets/select.py
I took care of allowing an `AutocompleteInput` widget to be created from a Parameter in https://github.com/holoviz/panel/pull/2874 but missed allowing to update its options/completions.
In this PR I also reset the widget's value to `''` if the current one is not in the new options/completions.
> Allow to update the completions options from a parameter

- panel/template/fast/theme.py
Fixes fix #2896.
The `ColorBar` is now readible when using the Fast dark themed templates. 
I need this for an example for the `scikit-image` docs.
```python
from skimage import data, filters
pn.extension()
image = data.coins()
edges = filters.sobel(image)*256
bounds = (-1, -1, 1, 1)
after_img = hv.Image(edges, bounds=bounds).apply.opts(
cmap="binary_r", responsive=True, title="After", active_tools=["box_zoom"], tools=["hover"], colorbar=True
)
layout=pn.panel(after_img, height=800, aspect_ratio=1)
pn.template.FastListTemplate(
site="Panel and Scikit-Image",
main=[layout],
header_background="#292929",
theme="dark",
).servable()
```
> fix #2896: Colorbar background for dark theme

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
Tabulator 5.0 is a major upgrade to the tabulator.js library which applied some major refactoring and improves performance. Since we are still very actively improving the Tabulator widget in Panel and don't want to invest in developing features on top of an old version and also want to leverage the latest in performance and features it is best to track tabulator.js as closely as possible.
Closes https://github.com/holoviz/panel/issues/2832
> Upgrade Tabulator to 5.x

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.ts
- panel/reactive.py
- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
Builds on #2898 (i.e. should be rebased once that is merged)
> Implement DateEditor and DatetimeEditor for Tabulator

- panel/models/tabulator.ts
- panel/widgets/tables.py
> Cleaned up and refactored Tabulator

- panel/io/state.py
- panel/layout/tabs.py
- panel/package-lock.json
- panel/package.json
Previously Tabs set to dynamic would re-render bokeh models every time a particular panel switched from hidden to shown state. There's no good reason not to just cache even the hidden rendered models.
> Tabs cache dynamic contents

- panel/config.py
- panel/io/resources.py
Since the loading indicator scales with the size of the object it's being rendered on we really need to be able to set a maximum height because you don't want a loading indicator to fill half your screen.
> Allow setting a maximum height for the loading indicator

- panel/template/material/material.css
Previous changes to the Card header caused some weirdness rendering the card header in the `MaterialTemplate`.
> Fixes for Card rendering in MaterialTemplate

- panel/pane/holoviews.py
- panel/pane/plot.py
Fixes https://github.com/holoviz/holoviews/issues/5121
> Ensure HoloViews matplotlib output uses tight layout

- panel/io/notebook.py
- panel/io/resources.py
- panel/io/save.py
- panel/io/server.py
Since the release of Bokeh 2.4 we are now always shipping the 1.8 MB MathJax bundle, whether that's on the server, in the notebook or in an exported file. 
To avoid this we now have the policy on both server and saved file exports that we only load the MathJax bundle if either:
- Some component is actually making use of the Bokeh mathjax support in the initially rendered app
- A user explicitly requests mathjax support with `pn.extension('mathjax')`
This will cause a slight regression because users that added a plot with mathjax handling after the initial render in a server context will now have to explicitly enable the mathjax support. Nonetheless I really would like to get this out in 0.12.5 because the 1.8 MB additional bundle loaded for everyone is a much larger issue.
In the notebook …
> Ensure loading of MathJax bundle is optional

- examples/reference/widgets/Select.ipynb
- panel/tests/widgets/test_select.py
- panel/widgets/select.py
The Select widget of Bokeh supports option groups (optgroup) that allow to visually group the elements of a dropdown menu.  The options of a Bokeh Select widget are grouped when they're declared in a dictionary, the keys of the dictionary being the groups labels. Panel already allows users to declare the options of its Select widget with a dictionary (the keys becoming the labels, and the values the values). Because of that this functionality is exposed in Panel by adding a `groups` parameter to the Select widget that is `None` by default (i.e. no groups) and accepts a dictionary that defines how the options should be grouped.
*When options is a list*
*When options is a dict*
*Error raised when the values of groups don't match exactly with the options*
> Add a groups (aka optgroup) parameter to Select

- panel/models/tabulator.ts
Temporary fix for https://github.com/holoviz/panel/issues/2924
> Fix sizing of Tabulator embedded in ReactiveHTML layout

- panel/models/tabulator.ts
The Tabulator checkbox option was not syncing the current selection.
> Fix Tabulator checkbox selection

- panel/models/card.ts
Computation of the positioning requires robust detection of the collapsible icon. This PR ensures that this happens even if `collapsible=False` or the icon is hidden.
> Ensure Card collapsible icon offset is computed robustly

- panel/io/reload.py
Fixes issues with autoreload, where `panel.models` would be reloaded causing errors because there may only be one version of a Bokeh model.
> Autoreload should not reload panel modules

- panel/io/server.py
Ensures that asynchronous callbacks have access to `pn.state.curdoc`.
> Ensure curdoc is available to async callbacks

- panel/models/tabulator.ts
The approach I tried for detecting newly added rows in Tabulator was incorrect for a number of reasons so for now we simply update all the data.
> Revert broken optimization in Tabulator streaming implementation

- examples/reference/layouts/Card.ipynb
- panel/layout/card.py
- panel/models/card.ts
- panel/models/layout.py
Sometimes you still want to place things in cards but don't actually need a header.
> Add hide_header option for Card

- panel/auth.py
Adds support for:
-  `PANEL_OAUTH_TOKEN_URL`
- `PANEL_OAUTH_AUTHORIZE_URL`
- `PANEL_OAUTH_USER_URL`
- `PANEL_OAUTH_SCOPE`
- `PANEL_USER_KEY`
> Make GenericOAuthProvider configurable via env vars

- panel/pane/holoviews.py
HoloViews patches `HoloViews._panes['plotly']` with a custom function which caused issues since we assumed it was an actual Pane type.
> Fix regression rendering HoloViews plotly backend

- panel/param.py
Allows an approach like this:
```python
import aiohttp
widget = pn.widgets.IntSlider(start=0, end=10)
async def get_img(index):
async with aiohttp.ClientSession() as session:
async with session.get(f"https://picsum.photos/800/300?image={index}") as resp:
return pn.pane.JPG(await resp.read())
pn.Column(widget, pn.bind(get_img, widget))
```
> Support async functions on ParamMethod/ParamFunction

- examples/reference/panes/Vega.ipynb
- panel/io/__init__.py
- panel/io/callbacks.py
- panel/models/vega.py
- panel/models/vega.ts
- panel/pane/vega.py
- panel/tests/pane/test_base.py
Implements https://github.com/holoviz/panel/issues/2365
> Implement support for Vega events

- panel/reactive.py
- panel/tests/test_reactive.py
Ensure that ReactiveHTML children are always cleaned up correctly.
> Improve handling of ReactiveHTML cleanup

- panel/pane/markup.py
Fixes https://github.com/holoviz/panel/issues/2977
> Ensure empty Str pane has same height as non-empty

- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/2972
> Ensure Tabulator supports grouping on numeric columns

- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
- setup.py
Fixes https://github.com/holoviz/panel/issues/2988
> Fix Tabulator with multi-index and pagination

- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/2956
> Allow index as column name in table widgets

- panel/widgets/tables.py
If no height is set on the table frozen_rows are never rendered. Hopefully this is eventually fixed upstream in Tabulator but for now we simply compute a height like we did in previous versions.
> Temporary fix for frozen_rows not rendering in Tabulator

- panel/template/base.py
The `TemplateActions` component added to all templates had a margin and therefore took up unnecessary height.
> Ensure TemplateActions component does not have height

- CHANGELOG.md
- doc/releases.md
- panel/io/resources.py
- panel/models/ace.ts
- panel/pane/holoviews.py
- panel/pane/markup.py
- panel/reactive.py
- panel/template/base.py
- panel/tests/test_reactive.py
- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
- setup.py
The 0.12.6 release fixes a major regression introduced in the last release along with a small number of pre-existing bugs. 
Regressions:
- Always load imported bokeh extensions ([#2957](https://github.com/holoviz/panel/pull/2957))
- Fix regression rendering `HoloViews` plotly backend ([#2961](https://github.com/holoviz/panel/pull/2961))
Bug fixes:
- Do not run `Ace` import on initialization ([#2959](https://github.com/holoviz/panel/pull/2959))
- Improve handling of `ReactiveHTML` cleanup ([#2974](https://github.com/holoviz/panel/pull/2974), [#2993](https://github.com/holoviz/panel/pull/2993))
- Ensure empty `Str` has same height as non-empty ([#2981](https://github.com/holoviz/panel/pull/2981))
- Ensure `Tabulator` supports grouping on numeric columns …
> Branch 0.12.6

- examples/homepage.ipynb
The website becomes quite large with all the data embedded so we try JSON embedding instead.
> Use JSON embedding on homepage

- panel/models/tabulator.py
Since Tabulator 5.0 the theme CSS for bootstrap, materialize are no longer nested into sub-directories.
> Ensure Tabulator theme CSS is loaded from correct place

- doc/index.rst
Attempt to get the table of content in the left side bar on the home page. Trying that because it's the only difference I could spot with `holoviews`.
> Add home to TOC of the home page

- panel/models/tabulator.ts
Without this the Tabulator can end up overlapping with another component. This ensures that renderComplete events are triggered and inform the parent table of any layout invalidations.
> Resize layout after expanding Tabulator row

- doc/conf.py
- doc/generate_modules.py
- panel/models/vtk.py
- panel/pane/vtk/vtk.py
- panel/tests/pane/test_vtk.py
- panel/widgets/file_selector.py
The default encoding on Python 3 is `"utf-8"` so we can remove the coding cookies from python modules in the package.
> Remove "utf-8" coding cookies from modules

- panel/config.py
- panel/interact.py
- panel/pane/holoviews.py
- panel/pane/vtk/synchronizable_serializer.py
- panel/param.py
- panel/tests/layout/test_base.py
- panel/tests/pane/test_base.py
- panel/tests/pane/test_image.py
- panel/tests/test_viewable.py
- panel/tests/util.py
- panel/tests/widgets/test_select.py
- panel/util.py
- panel/widgets/input.py
- panel/widgets/select.py
- panel/widgets/slider.py
This PR removes the usage of `sys.version_info` and derivatives in the codebase to handle Python < 3 code. The derivatives are - 
- `@py3_only` decorator used to mark tests that are meant to be run on Python > 2.
- `as_unicode` and `unicode_repr` utility functions
- `unicode` alias to `str` on Python 3
These changes can be done now that the package supports only Python >= 3.6
> Remove usage of "sys.version_info" to handle Python 2 code

- panel/models/layout.ts
Fixes #2971 
Only cache layout if the width and height is finite.
> Ensure CachedVariadicBox only caches layout for finite height and width

- doc/getting_started/index.rst
And also remove a reference to Python 2.7 and a link to Travis.
> Remove redundant and confusing JupyterLab install instructions

- panel/template/fast/css/fast_bokeh.css
Fixes #3003
You can verify via
```python
import panel.widgets as pnw
horizontal = pnw.FloatSlider(name='Horizontal', value=0, step=0.05, start=0, end=1)
vertical = pnw.FloatSlider(name='Vertical', value=0, step=0.05, start=0, end=1, orientation='vertical')
template = pn.template.FastListTemplate(
title="FastListTemplate",
main=[horizontal, vertical]).servable()
```
> Fix Fast Vertical Slider CSS

- examples/reference/widgets/FileInput.ipynb
Fixes https://github.com/holoviz/panel/issues/1559
I'd be happy if someone who understands a little better than me the infrastructure on top of which Panel relies (bokeh/tornado) could check what I wrote.
> Add docs about the file size limits of the FileInput widget

- doc/FAQ.rst
PR motivated by https://discourse.holoviz.org/t/what-does-the-render-with-panel-jupyter-lab-button-do/3039/5
> DOC: add note on enabling panel widget on Jupyter Lab

- panel/pane/holoviews.py
- panel/param.py
- panel/tests/pane/test_vega.py
- panel/tests/test_pipeline.py
- panel/tests/test_template.py
- panel/tests/util.py
- panel/tests/widgets/test_tables.py
- panel/util.py
- `from collections import Callable` -> `from collections.abc import Callable`
- `from distutils.version import LooseVersion` -> `from packaging.version import Version`
> Updates for Python 3.10 deprecations

- panel/models/progress.ts
- panel/models/speech_to_text.ts
- panel/models/vtk/vtkaxes.ts
Starting in bokeh 3.0 the old property definitions will no longer be supported.
> Update remaining bokeh property definitions

- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/3060
The JS callback set on the TextInput widget wasn't being initially triggered so the Tabulator `filename` property still had its original default value (`'table.csv`). I found no way to either trigger the JS callback or set the `filename` Tabulator property (it's not exposed to Panel users, it's just a property of the model). Instead I've removed that JS callback entirely and have set `filename` in the button JS callback.
> Respect the default filename set by `download_menu`

- examples/reference/widgets/CheckButtonGroup.ipynb
- examples/reference/widgets/RadioButtonGroup.ipynb
- panel/widgets/select.py
This PR simply exposes a Bokeh property not exposed by Panel.
Is the CSS of some templates to adapt for this kind of change or is this good to go?
> Expose the `orientation` parameter of the button group widgets

- panel/command/serve.py
- panel/config.py
- panel/io/server.py
- panel/io/state.py
- panel/tests/test_server.py
This allows `pn.state.onload` callbacks to take advantage of the threading support that was recently added.
> Allow onload callbacks to be threaded

- panel/models/tabulator.ts
Tabulator parses any raw string as HTML after we already performed the parsing. Therefore we just return the parsed HTML DOM node directly.
> Avoid parsing HTML twice during Tabulator formatting

- panel/links.py
Fixes https://github.com/holoviz/panel/issues/3058
```python
```
While this fixes the issue linked I'm not sure it's a good long term solution:
* It might well be a bug in Bokeh
* The only two properties that have `_default_help` set are `Color` and `Alpha` (`Alpha` causes no problem since it has no Parameter type associated). But if a mapped property (e.g. `String`) gets its `_default_help` set then we'll likely encounter the same error.
> Allow to convert a Color Parameter with `allow_None=True` to a Bokeh property

- examples/reference/panes/Audio.ipynb
- examples/reference/panes/Video.ipynb
- panel/models/audio.ts
- panel/models/video.ts
- panel/models/widgets.py
- panel/pane/media.py
- panel/tests/pane/test_media.py
Addresses #2978
Adding `autoplay` will make it much, much faster to evaluate several audio or video files. Or a situation where the audio or video file is output from some model that you are exploring.
I decided to add `muted` now I was working on this one.
[x] - Implement
[x] - Setup automated tests
[x] - Test manually
[x] - Document in reference examples
https://user-images.githubusercontent.com/42288570/147641002-6fa51a17-70eb-4ac0-9df1-a4937577ef0d.mp4
(left is Firefox, right is Edge. Note how Edge, which is chromium based, requires the user to click play once before autoplay will be allowed.)
```python
audio_options = ["http://ccrma.stanford.edu/~jos/mp3/pno-cs.mp3", …
```
> Adds autoplay and muted to media

- panel/layout/tabs.py
The logic for reusing previously rendered models in `Tabs` dynamic mode was wrong. Here we ensure the rendered model is correctly reused.
As a side effect this also happens to fix https://github.com/holoviz/panel/issues/2865
> Fix Tabs reuse of rendered model in dynamic mode

- .github/workflows/test.yaml
Github has [improved its Git protocol security](https://github.blog/2021-09-01-improving-git-protocol-security-github/) which means that usage of `git://` has been disabled. This broke the CI on Windows.
> Use https instead of the git:// protocol to clone in GHA

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
The upgrade to 5.0.x was premature since at least as of right now the performance is **significantly** worse.
Hopefully these issues will eventually be addressed and we'll be able to upgrade again.
> Downgrade Tabulator to 4.9.3

- panel/_templates/auth_error.html
- panel/auth.py
- panel/command/serve.py
- panel/io/resources.py
Avoids redirect loop when the auth provider errors out or denies access. The Auth error template can be customized using the `--oauth-error-template`CLI argument but by default an access denied error will look something like this:
.
> Handle authentification errors

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
- panel/widgets/tables.py
If you want to trigger custom actions by clicking on a table cell you may declare a set of `buttons` that are rendered in columns after all the data columns. To respond to button clicks you can register a callback using the `on_button_click` method:
> Implement Tabulator buttons

- panel/models/layout.ts
Reverts holoviz/panel#3024
Sadly have to revert, while this fix is correct it is having severe consequences for some production applications which we cannot easily work around.
> Revert "Ensure CachedVariadicBox only caches layout for finite height and width"

- panel/io/django.py
adds missing argument in call to `autoload_js_script`
fixes #3099
> add document argument to django.py autoload_js_script call

- panel/layout/flexbox.html
> FIX #3121: align-items missing from flexbox render template

- panel/io/django.py
@sdc50 Before this PR Django wasn't working at all for me since it couldn't load some resources. Did you have similar issues?
> Fix Django resource handling

- .github/workflows/test.yaml
- pyproject.toml
Attempt at fixing builds on OSX which are currently failing.
> Try to switch to setuptools

- panel/widgets/base.py
Implements a mechanism by which `Panel` types can override the properties on their children and utilizes that mechanism to override the alignment of Widgets in a Row to be 'end' ensuring that they line up nicely.
Does not handle GridBox alignments yet.
Supersedes https://github.com/holoviz/panel/pull/1376
> Set alignment of Widgets to ('start', 'end')

- panel/models/tabulator.ts
Tabulator was not calling relayout when rendering after a theme change.
> Fix layout of Tabulator with non-default theme

- panel/io/save.py
- panel/viewable.py
Fixes #3005 
https://user-images.githubusercontent.com/19758978/151700567-3a338759-4d8a-4064-a5a3-a1bcf5e7e448.mp4
<details>
<summary> Code </summary>
``` python
from io import BytesIO
import hvplot.pandas
import param
ACCENT_COLOR = "#0072B5"
class Explorer(param.Parameterized):
df = pd.DataFrame({"y": range(10)})
def __init__(self, **params):
super().__init__(**params)
self.plot = pn.Column(
self.df.hvplot().opts(color=ACCENT_COLOR, line_width=6, responsive=True),
self.df.hvplot().opts(color=ACCENT_COLOR, line_width=6, responsive=True),
)
self.save_to_png = pn.widgets.FileDownload(
filename="timeseries.png",
label="Download .png",
button_type="primary",
callback=self.download_column,
)
def …
```
> Expose save_png in save

- panel/pane/markup.py
- panel/widgets/tables.py
Fixes https://github.com/holoviz/panel/issues/2695
> Add support for rendering pandas styler objects

- panel/widgets/input.py
This fix works because the Spinner widget cannot render infinite values anyway. So this successfully avoids the error. A change in bokeh would be needed to actually support rendering (and entering) positive/negative infinity values in the widget.
Fixes https://github.com/holoviz/panel/issues/1998
> Fix issue serializing Spinner widgets with negative infinity value

- panel/__init__.py
Fixes #3135
I wanted to add all missing files to `__init__` but got `ImportError: cannot import name 'panel_extension' from partially initialized module 'panel.config' (most likely due to a circular import) (/home/shh/Development/holoviz/panel/panel/config.py)`or similar. So settled with adding the files for the two import I miss the most `pn.viewable.Viewer` and `pn.reactive.ReactiveHTML`. 
I used this code to be able to find missing imports:
``` python
import re
from pathlib import Path
def find_missing_import(file):
file = Path(file)
matches = re.findall(r"\w+", file.read_text())
missing = []
for f in sorted(file.parent.glob("*.py")):
f = f.name[:-3]
if f[0] != "_" and f not in matches:
missing.append(f)
return missing
files = Path("panel").rglob("__init__.py")
for file in files:
if …
```
> Added reactive and viewable to init

- examples/gallery/apis/stocks_altair.ipynb
- examples/gallery/apis/stocks_hvplot.ipynb
- examples/gallery/apis/stocks_matplotlib.ipynb
- examples/gallery/apis/stocks_plotly.ipynb
- examples/gallery/param/download_upload_csv.ipynb
- examples/reference/widgets/Tabulator.ipynb
- Fixes https://github.com/holoviz/panel/issues/2916 by noting Tabulator download functionality does not work with `pagination='remote'`
- Load tabulator extension where needed
- Update API notebooks in gallery to use `pn.bind` and global template.
> Various updates for documentation

- panel/models/reactive_html.ts
Previously ReactiveHTML would in some cases invalidate the layout of a root that was not yet done initializing which would cause errors because you cannot compute sizes of child views that have not yet been rendered. This is a particular issue for `pn.Tabs` which compute their sizes for each tab separately. We therefore do not invalidate the layout unless the root is finished rendering.
> ReactiveHTML should not invalidate layout of non-initialized roots

- panel/io/jupyter_server_extension.py
Jupyter sends path relative to the root_dir which can be different from the cwd. This commit fixes the lab extension for panel preview to account for root_dir.
Reference: #3170
> Support jupyter server root_dir with lab extension

- panel/param.py
Only makes the attribute public for now, the suggestions in https://github.com/holoviz/panel/issues/1348 are still valid and that issue will stay open.
Supersedes https://github.com/holoviz/panel/pull/1322
Fixes #620
> Make Param._mapping public

- panel/viewable.py
Fixes #3136
I hope this was what was meant with using `ParamMethod`.
> Viewer now updates when using depends on `__panel__`

- panel/models/tabulator.py
- panel/models/tabulator.ts
- panel/tests/widgets/test_tables.py
- panel/widgets/tables.py
Previously we were resetting the `styles` property on the model and keeping a local copy on the view. The problem with this is that the same model can be rendered again at a later stage and if when it was deleted the `styles` had been reset then it would render without the styles the second time. Therefore we take the simpler approach of including a random id in the styles so that even when the style hasn't changed it will still trigger updates.
> Redesign Tabulator styles handling

- panel/param.py
- panel/tests/test_param.py
Ensures param.Date and param.CalendarDate are correctly mapped to date widgets rather than `LiteralInput`.
> Do no override param.Date and param.CalendarDate mapping

- panel/models/tabulator.ts
When additional data is added and the height is not fixed we need to relayout after an update in the data.
> Trigger relayout when Tabulator data changes

- panel/widgets/base.py
Unfortunately have to revert this since the behavior is undesirable in some scenarios.
Reverts holoviz/panel#1504
> Revert "Set alignment of Widgets to ('start', 'end')"

- panel/models/tabulator.ts
Buttons can be any width so we let Tabulator auto-compute the width.
> Do not set fixed button width on Tabulator

- panel/io/state.py
- panel/tests/conftest.py
- panel/tests/io/test_state.py
Now that we have the ability to set `--num-threads` I expect many more users will leverage threads to speed up their application. However not all functionality in Panel was written with thread-safety in mind. This PR ensures that `pn.state.as_cached` maintains thread locks for each cache key ensuring that if multiple threads are trying to access the same cache key at the same time only one of the executes the function that is being cached on.
Additionally this PR also adds a TTL (time-to-live) for cache items allowing users to declare when a cached value expires and has to be refreshed.
> Add thread safety and TTL to pn.state.as_cached

- panel/tests/widgets/test_base.py
- panel/widgets/base.py
Fixes https://github.com/holoviz/panel/issues/3187
> Fix Widget.from_param when precedence is negative

- panel/io/resources.py
Setting an max-height meant that the entire loading overlay had a max-height of 400px when the desired effect was to set a max-height only for the loading animation.
Fixes https://github.com/holoviz/panel/issues/3204
> Fix handling of loading_max_height

- panel/__init__.py
One of the first steps into addressing https://github.com/holoviz/panel/issues/3131
I've added a docstring to the panel module. This will help the user a lot when working in VS Code. 
I believe it will also help in Jupyter (when using `?panel`) and in autogenerated Sphinx documentation.
I can use the feedback from this review when/ if I add more documentation.
Please note I've
- Used Markdown
- Added urls for easy navigation
- Added two "core" examples with gifs
- Added emojis
I believe the will leave a good first impression and be very helpful whenever you work with Panel.
I added added a full featured docstring just to demonstrate what is possible. It might be better (?) to simplify and just include the intro section with the short text and hyperlink? …
> Add docstring to panel module

- panel/io/ipywidget.py
the offset should be in bytes, not elements. See also https://github.com/bokeh/ipywidgets_bokeh/issues/46#issuecomment-1046292704
> fix: wrong offset when memoryview format is non-byte

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.ts
Previously we exposed sorters only so that remote pagination could correctly send the appropriate data but for consistency and ensuring that sorting persists when updating data we now always sync it bi-directionally.
> Bidirectionally sync Tabulator.sorters

- panel/io/state.py
I don't think this fixes any issues. Though, it fixes an annoyance I have had for some time...
This PR check for any query parameters in `baseurl` and adds it to `location.search` if possible. This means that the query parameter will load the first time and not have to load twice. This can be seen in the following examples where the before examples first shows 0 and then the query value, where the after examples shows the query value instantly. 
https://user-images.githubusercontent.com/19758978/155851312-91b37c15-507f-4aa4-a9e4-18fa70622eee.mp4
https://user-images.githubusercontent.com/19758978/155851313-64d754c3-fb54-4cd1-9c35-bec12e256f1e.mp4
<details>
<summary>Code  </summary>
``` python
import time
import param
class ButtonClick(pn.viewable.Viewer):
def …
```
> Check if there are any query parameters in `baseurl` and adds it to `location.search` if possible

- panel/models/reactive_html.ts
JS `undefined` values cannot be serialized.
> Filter out undefined values from ReactiveHTML DOMEvents

- panel/models/plotly.py
Turns out that Plotly decided to stop maintaining the latest bundle on their CDN so we have to bump to an explicit version.
Fixes https://github.com/holoviz/panel/issues/3226
> Bump plotly.js version

- panel/io/state.py
When a document has been destroyed the session_context is not longer accessible but it may still be accessed.
@MarcSkovMadsen Could you test?
Fixes https://github.com/holoviz/panel/issues/3225
> Guard pn.state.curdoc access

- panel/widgets/tables.py
As the title says, we shouldn't collapse rows simply because a cell was edited.
> Do not reset expanded property on edit

- panel/auth.py
Added a (very simple) additional authentication class that uses Azure AD's v2.0 oauth endpoint. This one uses the standard openid, email, and profile scopes instead of Azure-specific ones.
In particular, I couldn't get the default azuread auth to work with accounts that require MFA.
Azure's own docs suggest using V2.0 for all new applications:
https://docs.microsoft.com/en-us/azure/active-directory/azuread-dev/v1-overview
> add azure oauth v2.0 endpoint support

- panel/io/state.py
- panel/reactive.py
- panel/tests/pane/test_image.py
There were some issues with bokeh events not correctly checking for an unblocked comm and therefore not dispatching events in a timely manner.
> Fix event dispatch

- CODE_OF_CONDUCT.md
Requested in #2891
You can see the latest version of the PR here https://github.com/holoviz/panel/blob/code-of-conduct/CODE_OF_CONDUCT.md.
[![image](https://user-images.githubusercontent.com/42288570/140635800-c34ac550-2dfb-4386-ad0c-9e1bc9e11e12.png)](https://github.com/holoviz/panel/blob/code-of-conduct/CODE_OF_CONDUCT.md)
- [] Identify and appoint community leaders responsible for (enforcing) the code of conduct.
- [] Take the time to discuss enforcement with trusted members of the community. 
- [] Thoroughly read the Enforcement Guidelines section of the document and adapt if necessary
- [] Assign *code of conduct* email.
- [] Add a link to this document in the [HoloViz Discourse FAQ](https://discourse.holoviz.org/faq)
> Adds a code of conduct

- examples/reference/widgets/Tabulator.ipynb
- panel/models/tabulator.py
- panel/models/tabulator.ts
- panel/widgets/tables.py
For some use cases you need to know which exact cell was clicked on so we add a `on_click` callback. We also deprecate the `on_button_click` callback which was only introduced recently.
> Add Tabulator.on_click callback

- panel/models/reactive_html.ts
- panel/reactive.py
- panel/tests/test_reactive.py
- Handle inline script callbacks for DOM nodes created in jinja loops
- Update nodes and attributes to watch when re-evaluating template on looped parameter changes
> Improve support for jinja2 loops in ReactiveHTML

- panel/__init__.py
- panel/config.py
- panel/io/__init__.py
- panel/io/document.py
- panel/io/notebook.py
- panel/io/pyodide.py
- panel/io/server.py
- panel/io/state.py
- panel/param.py
- panel/reactive.py
- panel/viewable.py
This PR makes it so that in a pyiodide context the `panel.io.server` module and all tornado based imports are not run. Additionally this sets the default comm to be `'ipywidgets'` so that all Panel objects are rendered using the `jupyter_bokeh.BokehModel` ipywidget wrapper that also works in jupyterlite.
> Remove all tornado imports

- examples/gallery/components/CanvasDraw.ipynb
- examples/gallery/components/LeafletHeatMap.ipynb
I just checked out the index page on Binder and I can see the new gallery examples are in the index but do not display anything. Will try to solve
- [] MaterialUI
> Wrap new gallery examples into apps

- examples/user_guide/Custom_Components.ipynb
- panel/config.py
- panel/io/resources.py
- panel/layout/__init__.py
- panel/layout/gridstack.py
- panel/reactive.py
Currently any ReactiveHTML component that is imported when the panel extension is run or a server app is served for the first time will be loaded and all its JS/CSS dependencies will be embedded in the page. This isn't really a nice way to handle this problem because it creates a tension between offering helpful namespaces that include all components and reducing the number of external JS/CSS that are included in the page. To get around this we introduce the concept of a `ReactiveHTML._extension_name`. This, if declared, tells Panel not to load the dependencies for this component unless it has been explicitly loaded with `pn.extension(<extension_name>)`. This replicates the behavior we have long implemented for regular Bokeh models with dependencies we do not want to include by default …
> Add ability to require explicit load of ReactiveHTML extension

- binder/postBuild
- binder/requirements.txt
- examples/gallery/viz/GraphViz.ipynb
- examples/gallery/viz/NetworkX.ipynb
- setup.py
Addresses https://github.com/holoviz/panel/issues/89 by adding GraphViz and NetworkX gallery examples.
I've added a new `viz` folder. The vision would be to add examples for all the *viz tools you know and love* that are not already covered by the User Guide and Reference Guides. The purpose is to 1) Demonstrate the power of Panel 2) To make it very easy for users to get started with the tool they know and love. 
An example could be seaborn. And you might say "but there is already a Matplotlib reference guide". But I don't think that is enough. Some users might not know or think of that if Matplotlib is supported then Seaborn is as well. Furthermore there is a bit of friction to figure out how to get the Figure object in Seaborn etc. I also have code with styling for `default` and `dark` …
> Gallery Examples for Graphviz and NetworkX

- panel/io/server.py
- panel/io/state.py
Currently bokeh will call gc.collect() on every `Document.destroy()`. If you are cleaning up multiple sessions simultaneously this is excessive and can in fact lock up the server for multiple seconds. Here we override `Document.destroy` and schedule a separate task that effectively throttles gc.collect calls.
> Ensure gc.collect is not excessively called

- panel/depends.py
Partially fixes https://github.com/holoviz/panel/issues/3262
> Handle async functions in bind

- panel/config.py
Combined with https://github.com/holoviz/pyviz_comms/pull/87 this will avoid multiple execution of the extension in one cell.
> Avoid multiple extension execution

- doc/generate_modules.py
- panel/command/serve.py
- panel/io/jupyter_server_extension.py
- panel/io/reload.py
- panel/io/server.py
- panel/param.py
- panel/util.py
- panel/widgets/file_selector.py
I noticed I couldn't get the Panel widget in jupyter lab to work in a non-base conda environment.
With the output in my terminal:
The error is because `~` is present in the path and when `os.path.abspath` is used it gives a wrong result.
``` python
path = "~/hello_there.mp4"
a_path = os.path.abspath(path)
ae_path = os.path.abspath(os.path.expanduser(path))
path, a_path, ae_path
```
The `abspath` command is called from [bokeh](https://github.com/bokeh/bokeh/blob/560a57e166a1f54319df57127502d48ee4ecc72e/bokeh/command/util.py#L117) and a fix should be implemented there too.
> Added fullpath to jupyter_server_extension

- panel/models/reactive_html.ts
If you had both a method and a parameter reference in a ReactiveHTML component that started with the same string it would fail to expand the parameter reference in the template and cause errors.
> Ensure ReactiveHTML template variables only escapes exact matches

- panel/models/tabulator.ts
When updating row selection, scroll in the widget so that the selected
row is centered. This fixes the current behavior that leaves the
selected row just passed the end of the viewed range.
The original intended behavior was to place the selected row at the top
of the viewed range, but due to a Tabulator bug, we needed to request
"bottom" for that. Now that Tabulator seems to be fixed, use "center" so
that hopefully this issue will not come back.
Signed-off-by: Douglas Raillard <douglas.raillard@arm.com>
> Scroll to center selected Tabulator row

- panel/io/resources.py
- panel/tests/test_server.py
Fixes https://github.com/holoviz/panel/issues/2643
> Ensure css_files are referenced from correct relative path

- panel/models/tabulator.ts
Fixes https://github.com/holoviz/panel/issues/2697
I'm not quite sure how to test `.download()`.
> Align download property default values
