holoviz/panel

panel/panels.py

Previously, MatplotlibPanel and RGGPlotPanel had separate implementations for rendering PNGs into something Viewable.  This PR pulls that functionality into a new shared base class PNGPanel that makes those classes much simpler (Matplotlib support is now essentially just one call).  
PNGPanel isn't an abstract class, though; it directly renders anything with a `_repr_png_` method, which means that it supports PIL/Pillow objects, Datashader objects, and probably quite a lot of other objects that are designed to display themselves as PNGs in Jupyter.   
PNGPanel computes its size directly from the PNG, which means that it no longer needs an MPL-specific call and Datashader plots no longer need to specify their size (as it's in the PNG already).  So we can now do:
```
import numpy as np, …
```

Added PNGPanel as a base class and for _repr_png_

---

panel/param.py
panel/viewable.py
panel/widgets.py

Widget improvements

---

panel/layout.py
panel/param.py
panel/tests/conftest.py
panel/tests/fixtures.py
panel/tests/test_dummy.py
panel/tests/test_reactive.py
panel/tests/test_widgets.py
panel/viewable.py
panel/widgets.py

Various cleanup, fixes and tests for core classes and widgets.

Cleanup and tests

---

examples/user_guide/Layouts.ipynb
examples/user_guide/Param.ipynb
examples/user_guide/Widgets.ipynb
panel/__init__.py
panel/layout.py
panel/panes.py
panel/param.py
panel/tests/test_layout.py
panel/tests/test_param.py
panel/util.py
panel/viewable.py
tox.ini

Renamed and refactored core classes

---

panel/models/plotly.ts
panel/plotly.py
panel/tests/test_plotly.py
setup.py

Adds a PlotlyPlot bokeh model which renders plotly figures efficiently. Any arrays inside the plotly figure are extracted and added to a ColumnDataSource enabling binary transport of large arrays during plot updates.

Add a PlotlyPanel

---

panel/viewable.py

Ensures that server sessions are cleaned up correctly relying my PR in bokeh to support ``on_session_destroyed`` lifecycle hooks directly on the Document.

Added cleanup for server sessions

---

panel/param.py
panel/tests/test_param.py

Params pane now supports .param Parameters object

---

panel/models/plotly.ts
panel/pane.py

Includes small fixes for plotly and holoviews Panes.

Small fixes for plotting panes

---

examples/user_guide/Interact.ipynb
panel/__init__.py
panel/interact.py
panel/tests/test_interact.py
panel/tests/test_widgets.py
panel/widgets.py

Made a start on a ``interact`` implementation copying the API from ipywidgets. Large amounts of the implementation are copied directly from ipywidgets.
To do:

Add an implementation of interact

---

panel/viewable.py

Allows creating Panels which transparently display in a notebook and can be deployed using `bokeh serve`.

Added Viewable.servable method

---

panel/param.py
panel/viewable.py
panel/widgets.py

Matches changes that were made in param master

Applied rename to param Change.attribute

---

panel/models/plotly.ts

Fixes flicker and other rendering issues in PlotlyPlot model.

Fixed rendering bug in PlotlyPlot

---

panel/interact.py
panel/layout.py
panel/pane.py
panel/util.py
panel/viewable.py
panel/widgets.py

Instead of listening to one parameter at a time this PR batches parameter changes.

Make use of batched watch calls

---

panel/tests/test_widgets.py
panel/widgets.py

Fixed and improved LiteralInput and DatetimeInput widget validation

---

doc/FAQ.rst
doc/Roadmap.rst

Added a draft roadmap and cleaned up FAQ slightly.

Added Roadmap

---

panel/layout.py
panel/param.py
panel/viewable.py
panel/widgets.py

In param we decided to rename Change objects to Event objects and this PR reflects this naming change by renaming variables.

Renamed changes to events

---

panel/tests/test_widgets.py
panel/util.py
panel/widgets.py

Adds two new widgets ``ToggleButtons`` and ``RadioButtons``. The signature for both is equivalent to ``MultiSelect``.

Add RadioButtons and ToggleButtons

---

.travis.yml
dodo.py
tox.ini

Unlike for geoviews, no need for awkward conda+pip combination.

Simplify pip package builds

---

panel/cli.py
setup.py

This PR aims to address #99. I'll be extending this PR with some experimental functionality with another PR based off this one.

Implementation of panel console script

---

examples/user_guide/Layouts.ipynb
panel/layout.py

Allow getting and setting Tabs.active

---

panel/holoviews.py

Ensure older versions of HoloViews are supported

---

panel/tests/test_widgets.py
panel/widgets.py

- Closes https://github.com/pyviz/panel/issues/118

RangeSlider dynamically changes to IntRangeSlider

---

panel/models/plotly.ts
panel/models/vega.ts

Fixed plotly and vega sizing

---

.travis.yml
MANIFEST.in
conda.recipe/meta.yaml
dodo.py
panel/__init__.py
panel/pane.py
panel/plotly.py
panel/tests/test_holoviews.py
panel/tests/test_panes.py
panel/util.py
panel/vega.py
setup.py
tox.ini

This PR customizes setup.py in such a way that it compiles custom bokeh models and stores the compiled code alongside the original code. Additionally it registers a hook with bokeh which loads the cached models during bokeh's compilation step.

Build and load bokeh compiled model cache

---

panel/param.py
panel/tests/test_param.py

Renamed Param expand options

---

panel/interact.py
panel/pane.py
panel/param.py
panel/viewable.py

There were still cases where Exceptions would break a panel irrecoverably.

Consistently clean up state after exceptions

---

panel/widgets.py

@jsignell The PR I promised. I'll merge this pretty much immediately but there's a few more PRs I want to finish off before tagging 0.2.0a7.

Add MultiSelect.size

---

panel/holoviews.py
panel/interact.py
panel/layout.py
panel/pane.py
panel/param.py
panel/plotly.py
panel/tests/test_holoviews.py
panel/tests/test_interact.py
panel/tests/test_layout.py
panel/tests/test_panes.py
panel/tests/test_param.py
panel/tests/test_plotly.py
panel/tests/test_reactive.py
panel/tests/test_vega.py
panel/vega.py
panel/viewable.py
panel/widgets.py

Completely overhauled cleanup code

---

examples/user_guide/Widgets.ipynb
panel/tests/test_widgets.py
panel/widgets.py

Adds a CrossSelector widget which is a lot more usable for large numbers of items than a ``MultiSelect`` widget.

Add CrossSelector widget

---

panel/interact.py

Skip non-recognized kwargs in interact

---

panel/tests/test_widgets.py
panel/widgets.py

Adds a DiscretePlayer class which is analogous to DiscreteSlider, i.e. rather than start and end values it has a options list, which it iterates over.

Add a DiscretePlayer class

---

MANIFEST.in
doc/index.rst
setup.py

Attempt to fix issue where the examples aren't in the package and `panel examples` isn't working.

Possible fixes for example packaging

---

.travis.yml

Correction of travis build failure.
Reference to:
https://github.com/pyviz/datashader/pull/682

Set minimum version of pyctdev

---

panel/holoviews.py
panel/layout.py
panel/tests/test_holoviews.py
panel/viewable.py

Process new links when setting new holoview item in layout

---

.appveyor.yml

Example of build:
https://ci.appveyor.com/project/xavArtley/panel/builds/21457101

Add appveyor build

---

panel/holoviews.py
panel/layout.py
panel/pane.py
panel/param.py
panel/tests/test_layout.py
panel/tests/test_param.py
panel/util.py

- Fixes https://github.com/pyviz/panel/issues/148

Decouple Tab names from object names

---

README.md

New style readme

---

conda.recipe/meta.yaml
setup.py

Getting rid of dependencies for test and nodejs requirement. If nodejs is needed it should be moved to setup.py

Updating meta.yaml to make it pure template

---

README.md

After this comment: https://github.com/pyviz/hvplot/pull/160#issuecomment-462443779

Adding "About PyViz"

---

conda.recipe/meta.yaml

Should fix https://travis-ci.org/pyviz/panel/jobs/493822831

Adding back in requires

---

panel/holoviews.py

Ensure HoloViews pane does not create static sliders

---

panel/holoviews.py
panel/tests/test_holoviews.py
panel/tests/test_widgets.py
panel/widgets.py

Fixes https://github.com/pyviz/panel/issues/246

Fixes for datetime sliders in HoloViews pane

---

doc/index.rst

Updating badges to show the versions available on different channels

Changing the badges on the landing page

---

.appveyor.yml
.travis.yml
setup.py

Clean up build

---

.travis.yml
panel/interact.py
tox.ini

Fixes https://github.com/pyviz/panel/issues/243

Fixed imports in interact

---

panel/interact.py
panel/tests/test_interact.py

Fixes https://github.com/pyviz/panel/issues/183

Add support for interact title

---

examples/user_guide/Widgets.ipynb
panel/param.py
panel/widgets.py

Fixes https://github.com/pyviz/panel/issues/248

Add ColorPicker widget

---

doc/conf.py
doc/developer_guide/index.rst
doc/developer_guide/testing.rst
doc/index.rst

Added basic developer guide

---

panel/viewable.py
panel/widgets/slider.py

Extension of https://github.com/pyviz/panel/pull/288
Ensures that server events are not incorrectly dropped.

Improved server event processing

---

panel/pane/holoviews.py
panel/tests/test_holoviews.py

Other Panes already allow an empty constructor but it seems like I overlooked HoloViews.

Allow constructing empty HoloViews pane

---

panel/models/audio.ts
panel/models/fileinput.ts
panel/models/player.ts
panel/models/plotly.ts
panel/models/vega.ts
setup.py

fixes : https://github.com/pyviz/panel/issues/296

Post bokeh #8740 ts fix

---

panel/widgets/select.py
panel/widgets/tests/test_select.py

Fixes https://github.com/pyviz/panel/issues/319

Fix bugs in CrossSelect

---

panel/io/notebook.py
panel/tests/test_util.py
setup.py

Requires pyviz_comms master and/or latest jupyterlab extension.

Combine HTML and JS in MIME bundle

---

panel/param.py
panel/tests/test_param.py

Fixes https://github.com/pyviz/panel/issues/308

Inlined subobject expand toggle button

---

panel/models/vega.py
panel/models/vega.ts

Optimizes re-rendering of a plots pointing to remote data sources by pre-fetching it.

Make Vega pane pre-fetch remote data

---

examples/reference/panes/VTK.ipynb

Some changes in the reference guide of the VTK panel when using native vtk object
+ remove reference to altair

Minor changes in vtk reference guide [doc-build]

---

panel/viewable.py

Fixes https://github.com/pyviz/panel/issues/356

Fix hv extension load

---

panel/param.py
panel/tests/test_param.py

Fixes  https://github.com/pyviz/panel/issues/169

Add support for param.Number step

---

doc/FAQ.rst
doc/Roadmap.rst

Minimal update to make roadmap accurate as of now.  Many of these items are now mostly done, so could instead be moved off the roadmap, but maybe better to wait until they are announced.

Updated Roadmap

---

panel/config.py

Fixes https://github.com/pyviz/panel/issues/397

Error if CSS supplied as wrong type to extension

---

setup.py

Removed testpath pin and plotly pin.

Removed unnecessary pins

---

examples/reference/layouts/WidgetBox.ipynb
panel/__init__.py
panel/layout.py

Adds WidgetBox which acts just like a Column but with some extra styling and margins.

Add WidgetBox layout

---

panel/param.py
panel/tests/test_param.py

Fixes https://github.com/pyviz/panel/issues/434

Ensure param precedences are always respected

---

panel/pane/vtk.py

 Ensure vtk import is loaded dynamically

---

panel/param.py

Ensure lookup of keyword dependencies is safe

---

panel/param.py
panel/tests/test_param.py

Ensure change parameter label updates widget names

---

examples/user_guide/Param.ipynb

Fixes https://github.com/pyviz/panel/issues/428

Improved documentation for Param pane

---

panel/pipeline.py

Fixes https://github.com/pyviz/panel/issues/213

Ensure pipeline subway map works correctly

---

panel/config.py

Fix https://github.com/pyviz/panel/issues/452

Ensure extension initializes HoloViews comms

---

panel/pane/_vtkjs_serializer.py
panel/pane/vtk.py
panel/pane/vtk/__init__.py
panel/pane/vtk/vtk.py
panel/pane/vtk/vtkjs_serializer.py
panel/tests/pane/test_vtk.py

In reference to https://github.com/pyviz/panel/issues/408
I separate the vtkjs serialization implementation from the pane implementation
I add a method set_serializer which register a custom serializer.
I add a try catch to wait for vtki serializer implementation. If it fails (and it fails for the moment). I register the actual serializer
a serializer expect a vtk render window as input and the vtkjs file binary stream output
I factorized the base64 encoding to send the stream to vtkjs
the _vtk_serializer.py should not be in pane package but I don't know where to put it

Add possibility to set custom vtkjs serializer

---

doc/user_guide/index.rst
examples/user_guide/Templates.ipynb
examples/user_guide/sample_template.html
panel/__init__.py
panel/template.py
panel/viewable.py

This PR adds a high-level Template component which makes it easy to combine multiple panels into a single HTML document.

Add Template component

---

panel/pane/vega.py
panel/tests/pane/test_vega.py
tox.ini

Fixes https://github.com/pyviz/panel/issues/422

Ensure vega InlineDataset is handled

---

panel/models/vega.ts
panel/tests/pane/test_vega.py

Fixes for populating Plotly data from CDS

---

.travis.yml

This should fix the failure in https://travis-ci.org/pyviz/panel/jobs/551102228

Making docs build use python 3.6

---

doc/getting_started/index.rst
setup.py

Adding links to badges

---

examples/reference/widgets/Button.ipynb

Added example on how to use on_click method to trigger function when button is pressed.
I could not find any other working example how to use button in Panel documentation.

Added on_click example for Button widget

---

panel/layout.py
panel/tests/test_layout.py

Fixes https://github.com/pyviz/panel/issues/500

Widget box orientation

---

examples/gallery/apis/stocks_plotly.ipynb
panel/models/plotly.py
panel/models/plotly.ts
panel/pane/plotly.py
panel/tests/pane/test_plotly.py

This PR contains initial work on providing plotly callback support in Panel.
To start with, I added callback properties that match what Dash uses (https://dash.plot.ly/interactive-graphing):
- `relayout_data`
- `restyle_data`
- `click_data`
- `hover_data`
- `clickannotation_data`
- `selected_data`
These properties are successfully updated on the Python side when interacting with a displayed figure. For example:
```python
import plotly.graph_objs as go
pn.extension('plotly')
fig_pane = pn.pane.Plotly(
go.Figure(
data=[go.Scatter(y=[1, 3, 2], mode='markers'),
go.Scatter(y=[3, 2, 4], mode='markers')],
),
)
fig_pane
```
Then perform a box selection and look at the resulting `selected_data` property:
```python
fig_pane.selected_data
```
```
{'points': [{'curveNumber': 0, …
```

plotly callback and in-place update support

---

panel/widgets/select.py

PR to address #499 including button positioning:
Before:
After:

Crossselector layout fix

---

panel/widgets/player.py

This will make it possible to export the HoloViews scrubber widget into static html files

Add support for embedding Player widget

---

examples/reference/layouts/GridBox.ipynb
panel/__init__.py
panel/layout.py

Implements a GridBox model which is list-like and wraps according to the specified number of rows or columns.
Closes #457

Add GridBox layout [doc-build]

---

panel/callbacks.py

Make PeriodicCallback.period dynamically updatable

---

examples/getting_started/Introduction.ipynb

https://panel.pyviz.org/user_guide/Parameters.html yields a 404.

[DOC] Fix broken hyperlink

---

panel/layout.py

[COMPAT] Force dtype for older numpy

---

panel/io/embed.py

Fixes https://github.com/pyviz/panel/issues/651

Ensure embed works on Pane layout

---

examples/reference/widgets/TextAreaInput.ipynb
panel/widgets/input.py

Added the TextAreaInput widget similarly to PasswordInput.

Added TextAreaInput widget

---

examples/reference/widgets/TextAreaInput.ipynb

Removed stray import and made description more accurate.

TextAreaInput reference notebook

---

examples/reference/panes/Markdown.ipynb

The new example shows a markdown hyper link and how to style table borders using various methods and discusses their advantages and disadvantages

Updated Markdown example

---

panel/pane/plotly.py

wrap to_plotly_json and turn datetimes into strings

---

panel/_testing/fixtures.py
panel/util.py
panel/viewable.py

Prepare support for python 3.8

---

examples/user_guide/Param.ipynb

Fix panes link in Parameters user guide docs

---

examples/user_guide/Django_Apps.ipynb

See https://github.com/pyviz/panel/pull/705#discussion_r334467157

Fixing Introduction link to work in both rendered docs as well as notebooks.

---

panel/widgets/misc.py

Inline scipy import

---

examples/user_guide/Pipelines.ipynb
panel/pipeline.py
panel/tests/test_pipeline.py

Various Pipeline fixes

---

panel/pane/media.py

solve https://github.com/pyviz/panel/issues/730

Audio pane check dtype and ndim

---

panel/pane/markup.py
panel/tests/pane/test_markup.py
panel/tests/util.py

Fixes https://github.com/pyviz/panel/issues/597

Ensure Series renders as Series by default

---

doc/FAQ.rst

Fixes https://github.com/pyviz/panel/issues/741
Cc: @jbednar

Document debugging in notebook

---

examples/apps/django2/sliders/bk_sliders.py
examples/user_guide/Django_Apps.ipynb

Changed _get_root to server_doc.
Fixes #445

Fix Django example app

---

examples/user_guide/Deploy_and_Export.ipynb
panel/io/notebook.py
panel/pane/base.py
panel/pane/holoviews.py
panel/tests/test_io.py
panel/tests/test_viewable.py
panel/viewable.py
panel/widgets/base.py
setup.py

Improvements and fixes for ipywidget rendering

---

panel/layout.py

Implements https://github.com/pyviz/panel/issues/663

Add Divider

---

panel/links.py

Fixes https://github.com/pyviz/panel/issues/757

Fixed bug with non-hashable JSCallback args

---

examples/reference/layouts/Column.ipynb
examples/reference/layouts/Row.ipynb
panel/_styles/widgets.css
panel/layout.py

Implements https://github.com/pyviz/panel/issues/383

Make Row/Column scrollable

---

panel/pane/holoviews.py

Fixes https://github.com/pyviz/panel/issues/759

Ensure custom HoloViews widgets are assigned default parameters

---

panel/pane/base.py

Fixes https://github.com/pyviz/panel/issues/413

Handle replacements in GridBox models

---

panel/pipeline.py
panel/tests/test_pipeline.py

Fixes https://github.com/pyviz/panel/issues/734

Make Pipeline graph clickable

---

examples/reference/widgets/DataFrame.ipynb
panel/widgets/tables.py

Fixed DataFrame.fit_columns documentation

---

panel/pane/base.py
panel/pane/image.py

Allows customizing type errors per Pane type.

Added customized Pane type errors

---

panel/widgets/slider.py

Fixes https://github.com/holoviz/panel/issues/805

Ensure sliders get initialized correctly

---

panel/pipeline.py

Fixes https://github.com/pyviz/panel/issues/801

Improved handling of precedences on Pipeline

---

panel/pane/holoviews.py
panel/template.py
panel/tests/test_template.py

Recent changes to root handling caused some issues with axis linking. This also simplifies the creation of roots in a Template.
Cc: @dharhas Please test on LSST (I did some initial testing and it seemed to work)

Improve Template root handling

---

panel/pane/holoviews.py

Fixes https://github.com/holoviz/panel/issues/845

Ensure HoloViews callbacks are reinitialized after linking

---

panel/pane/holoviews.py

Fixes https://github.com/holoviz/panel/issues/845

Ensure callbacks on OverlayPlots are reinitialized

---

panel/pane/vtk/vtk.py

fixes: https://github.com/holoviz/panel/issues/819

VTK link on data correction

---

panel/models/vtk/vtk.ts
panel/models/vtk/vtk_utils.ts
panel/models/vtk/vtkaxes.ts
panel/tests/pane/test_vega.py

Delay VTK namespace imports

---

panel/pane/vega.py

Serialize list of data in Vega spec

---

panel/widgets/slider.py

Fixes https://github.com/holoviz/panel/issues/859

Ensure that integer sliders are actually integers

---

panel/links.py

Fixes https://github.com/holoviz/panel/issues/830

Allow multiple Callbacks on one source

---

panel/pane/base.py
panel/pane/vtk/vtk.py

Ensure that server updates get correct reference to old models

---

panel/pane/vega.py

Fixes #886 
```python
spec = {
"$schema": "https://vega.github.io/schema/vega/v5.json",
"width": 770,
"height": 770,
"padding": 2,
"signals": [
{ "name": "cellSize", "value": 10 },
{ "name": "count", "update": "length(data('nodes'))" },
{ "name": "width", "update": "span(range('position'))" },
{ "name": "height", "update": "width" },
{
"name": "src", "value": {},
"on": [
{"events": "text:mousedown", "update": "datum"},
{"events": "window:mouseup", "update": "{}"}
]
},
{
"name": "dest", "value": -1,
"on": [
{
"events": "[@columns:mousedown, window:mouseup] > window:mousemove",
"update": "src.name && datum !== src ? (0.5 + count * clamp(x(), 0, width) / width) : dest"
},
{
"events": "[@rows:mousedown, window:mouseup] > window:mousemove",
"update": "src.name && datum !== src ? (0.5 + count * …
```

Handle list of Vega data containing URLs

---

panel/pane/image.py
panel/pane/markup.py
panel/tests/pane/test_holoviews.py
panel/tests/pane/test_markup.py
panel/tests/pane/test_plot.py
panel/tests/pane/test_vega.py
panel/tests/test_interact.py
panel/tests/test_param.py

So it turns out I hadn't actually used the optimized HTML model consistently throughout so this PR should provide further speedups but also potential to break things.
@MarcSkovMadsen would you mind trying this out again?

Use optimized HTML model consistently

---

dodo.py
setup.py

(I haven't tested this change.)

Remove outdated test dependencies.

---

panel/pane/holoviews.py
panel/pane/plot.py
panel/tests/pane/test_holoviews.py

Fixes https://github.com/holoviz/panel/issues/902

Ensure that parameters set on HoloViews pane are applied

---

panel/pane/base.py
panel/pane/markup.py
panel/param.py
panel/tests/pane/test_markup.py

Fixes https://github.com/holoviz/panel/issues/848

Made HTML model CSS rules more precise

---

panel/param.py

Fixes https://github.com/holoviz/panel/issues/593

Fixed bugs updating multiple Parameters

---

panel/interact.py

Fixes https://github.com/holoviz/panel/issues/598

Switch interact to using panel function internally

---

panel/models/vega.ts
panel/pane/plot.py
panel/pane/vega.py
panel/tests/pane/test_base.py

Fixes https://github.com/holoviz/panel/issues/920

Vega data fixes

---

panel/widgets/base.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/941

Fix manual widget updates on multiple events

---

examples/reference/panes/Plotly.ipynb
examples/reference/panes/Vega.ipynb
panel/models/ace.ts
panel/models/audio.ts
panel/models/html.ts
panel/models/json.ts
panel/models/katex.ts
panel/models/layout.ts
panel/models/mathjax.ts
panel/models/plotly.py
panel/models/plotly.ts
panel/models/progress.ts
panel/models/util.ts
panel/models/video.ts
panel/models/videostream.ts
panel/models/vtk/vtk.ts
panel/models/vtk/vtkvolume.ts
panel/models/widgets.py
panel/package.json
panel/pane/plotly.py
panel/tests/pane/test_plotly.py

This is a refactor of the layout code and an attempt to drop the lodash dependency from Plotly. Mateusz will likely hate my terrible typing in the util module but it's better than dynamically loading all of lodash and typing the hole thing as `any`. 
Fixes https://github.com/holoviz/panel/issues/822

Refactor Models

---

panel/io/server.py
panel/template.py
panel/viewable.py

Supersedes https://github.com/holoviz/panel/pull/650

Expose title and other kwargs on show

---

panel/pane/base.py
panel/param.py
panel/util.py

Fixes https://github.com/holoviz/panel/issues/898

Fixes for recursive repr

---

panel/widgets/base.py
panel/widgets/select.py

Fixes https://github.com/holoviz/panel/issues/641

Fixed bug in CompositeWidget

---

panel/io/notebook.py
panel/layout.py
panel/tests/pane/test_holoviews.py
panel/tests/test_layout.py
panel/tests/test_reactive.py
panel/tests/test_server.py
panel/viewable.py

Fixes https://github.com/holoviz/panel/issues/621

Ensure that closed tabs update Tabs.objects

---

panel/io/save.py

Fixes https://github.com/holoviz/panel/issues/925

Ensure Panes with multiple items get saved correctly

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/923

Fixed DataFrame widget selection parameter

---

doc/conf.py
doc/index.rst
doc/releases.rst
doc/user_guide/index.rst
examples/getting_started/Introduction.ipynb

Fixes https://github.com/holoviz/panel/issues/510

V0.8 doc improvements rev2

---

examples/reference/panes/VTK.ipynb
examples/reference/panes/VTKVolume.ipynb
panel/models/vtk/vtk.ts
panel/models/vtk/vtk_layout.ts
panel/models/vtk/vtkvolume.ts

fix : https://github.com/holoviz/panel/issues/987

vtk layout proposition

---

examples/reference/layouts/Tabs.ipynb
panel/layout.py
panel/tests/test_layout.py

Makes it possible to load only the currently active tab.

Add support for dynamically populating Tabs

---

examples/reference/panes/VTK.ipynb
examples/reference/panes/VTKVolume.ipynb
panel/models/vtk/vtk.ts
panel/models/vtk/vtk_layout.ts
panel/models/vtk/vtkvolume.ts

Had to reopen due to accidental force push

VTK Layout fixes

---

panel/param.py
panel/widgets/select.py

Fixes https://github.com/holoviz/panel/issues/228

Updated Parameter mappings

---

panel/config.py
panel/interact.py
panel/io/embed.py
panel/layout.py
panel/pane/base.py
panel/pane/holoviews.py
panel/param.py
panel/pipeline.py
panel/tests/pane/test_holoviews.py
panel/tests/test_layout.py
panel/viewable.py

Title describes all the current changes. I'll have a look to see if I can find any more outdated param API usage but current diff is ready to review.

Further param API fixes for set_param method [doc-build]

---

examples/user_guide/Deploy_and_Export.ipynb
panel/cli.py
panel/config.py
panel/interact.py
panel/io/embed.py
panel/io/notebook.py
panel/layout.py
panel/links.py
panel/pane/base.py
panel/pane/holoviews.py
panel/pane/markup.py
panel/pane/plotly.py
panel/pane/vtk/vtk.py
panel/param.py
panel/pipeline.py
panel/template.py
panel/tests/pane/test_holoviews.py
panel/tests/pane/test_plotly.py
panel/tests/pane/test_vega.py
panel/tests/pane/test_vtk.py
panel/tests/test_pipeline.py
panel/tests/test_template.py
panel/tests/util.py
panel/util.py
panel/viewable.py
panel/widgets/input.py
panel/widgets/select.py
panel/widgets/tables.py
setup.cfg
setup.py

This adds a minimal setup derived from bokeh's `setup.cfg`. This PR is a side-effect of PR #1017.

Set up flake8 and clean up bare except and other errors

---

panel/pane/media.py

Fix loading of local audio files

---

panel/pane/image.py

Fixed bug handling stretch_width on images

---

panel/pane/vtk/vtk.py

Small fix making the doc example works again for axes

VTK do not rerender on axes change

---

panel/viewable.py

fix: https://github.com/holoviz/panel/issues/1089

Fix threaded server

---

panel/tests/widgets/test_misc.py
panel/widgets/misc.py

Fixes https://github.com/holoviz/panel/issues/1087

Fixed Progress value bounds bug

---

panel/config.py

Fixes https://github.com/holoviz/panel/issues/1094

Fix bug when hv.extension._loaded is not defined

---

panel/io/server.py
panel/viewable.py

Closes https://github.com/holoviz/panel/issues/1088

Add verbose option for show and serve

---

examples/gallery/demos/VTKSlicer.ipynb

[VTKSlicer]fix bokeh hook function

---

panel/links.py

Ensure jslink does not error in Template

---

examples/reference/widgets/FileDownload.ipynb
examples/reference/widgets/FloatSlider.ipynb
examples/reference/widgets/IntSlider.ipynb
examples/reference/widgets/MultiChoice.ipynb
examples/reference/widgets/RangeSlider.ipynb
panel/widgets/slider.py

Closes #1102
Supersedes https://github.com/holoviz/panel/pull/1103

Allow defining slider format

---

.travis.yml

Fix pyviz -> holoviz in fqdn.

---

doc/index.rst

Fixes https://github.com/holoviz/panel/issues/1162

Clarify instructions to get notebooks

---

panel/io/server.py

Allow serving dynamically created Template instance

---

panel/template.py

Fixes https://github.com/holoviz/panel/issues/1158

Ensure Template can render empty HoloViews pane

---

examples/gallery/param/precedence.ipynb

As discussed on Discourse [here](https://discourse.holoviz.org/t/a-little-app-to-understand-how-precedence-works/378/4), here is the notebook for a Param example that demonstrates how the precedence parameter affects the display of widgets.
(It is my first PR ever so I might have done things completely wrong, let me know if that is the case!)

Add a Param example for precedence

---

panel/io/model.py
panel/tests/test_io.py
panel/viewable.py

Required for handling JSON serialized typed arrays arriving via the CommManager.

Handle typed array messages from CommManager

---

panel/package.json
setup.py

Fixes https://github.com/holoviz/panel/issues/1197

Various updates to setup.py

---

examples/gallery/demos/VTKSlicer.ipynb

Fixes https://github.com/holoviz/panel/issues/1194

Ensure VTKSlicer uses https resources

---

examples/apps/django2/project/settings.py
examples/apps/django_multi_apps/django_multi_apps/settings.py
examples/apps/django_multi_apps/requirements.txt

Also updates the Django apps to load extension from CDN

Fix security vulnerability

---

.travis.yml
doc/api/index.rst
doc/conf.py
doc/generate_modules.py
doc/index.rst

An initial draft, improvements and cross-linking will come later.

Add API docs

---

README.md

Small PR removing the About section from the project's README file.

Removed the about section from the Panel Readme

---

examples/reference/layouts/Accordion.ipynb
examples/reference/layouts/Card.ipynb

Minor clarifications and fixes. It would also be great for the start of these docs to point to a full-fledged running dashboard made out of cards, so that it's clear how to use them together to make a full-page layout.

Updated Card and Accordion docs

---

.travis.yml
doc/_static/nbsite.css
examples/reference/layouts/Accordion.ipynb
examples/reference/layouts/Card.ipynb
panel/_styles/card.css
panel/layout/accordion.py
panel/layout/card.py
panel/models/card.ts
panel/models/layout.py

You can see the current builds here:
https://pyviz-dev.github.io/panel/reference/layouts/Accordion.html
https://pyviz-dev.github.io/panel/reference/layouts/Card.html
@MarcSkovMadsen @jbednar Further styling suggestions would be very welcome. Some questions I have:
* Should Card really have rounded corners? We use them elsewhere but I'm starting to think it looks cleaner without
* Should the Header title font be smaller by default?

Style fixes for Card and Accordion [doc-build]

---

panel/layout/base.py
panel/tests/layout/test_base.py
panel/tests/layout/test_tabs.py

Allows using `+` and `+=` to add items to a `ListLike` Panel.

Implement __add__ and __iadd__ on layouts

---

panel/models/vega.ts

fix: https://github.com/holoviz/panel/issues/1314

Fix vega with empty datasets

---

examples/reference/panes/Matplotlib.ipynb

Fixes https://github.com/holoviz/panel/issues/509
I found VSCode to be quite handy in working with notebooks and diffing them. It helped me to make sure I haven't added any metadata :)

Add matplotlib guidance to reference pane

---

examples/user_guide/Server_Deployment.ipynb

Reference: https://discourse.holoviz.org/t/questions-on-server-deployment-of-panel-app/618/8?u=mycarta

Fixed jupyter-panel-proxy in Mybinder deployment

---

examples/user_guide/Param.ipynb
panel/io/location.py
panel/tests/io/test_location.py

Implements https://github.com/holoviz/panel/issues/1335

Add Location.unsync method

---

panel/reactive.py
panel/tests/test_links.py

Fixes https://github.com/holoviz/panel/issues/1346

Fixed jslink on Bokeh.object

---

panel/models/file_download.ts

fix https://github.com/holoviz/panel/issues/1289

download button fill the space

---

examples/reference/widgets/Player.ipynb
panel/models/player.ts
panel/models/widgets.py
panel/widgets/player.py

implement and fix: https://github.com/holoviz/panel/issues/1333
fix: https://github.com/holoviz/panel/issues/1110 
fix: https://github.com/holoviz/panel/issues/538

Player layout enhancements

---

panel/param.py

Implements https://github.com/holoviz/panel/issues/1352
Cc: @jbednar @maximlt Please review the warning and chime in if you have clarifications.

Add warning if method or function with watch=True is provided

---

panel/param.py

[pn.Param] type not in widgets => widget is not override

---

panel/models/vtk/vtklayout.ts

correction to make jslink camera works when panning

[VTK Fix] Ensure camera change is emit after mouse interaction

---

panel/tests/widgets/test_button.py
panel/widgets/button.py

Fixes https://github.com/holoviz/panel/issues/1366

Handle jscallback on Button clicks property

---

panel/param.py

Fixes https://github.com/holoviz/panel/issues/1264

Do not fall back to Spinner widget for param.Number

---

panel/io/server.py

Fixes https://github.com/holoviz/panel/issues/1405

Fix num_procs with panel.serve

---

panel/models/deckgl.ts
panel/models/plotly.ts

Sometimes the module is not loaded in time and nothing works.

Always fully qualify global JS module

---

panel/models/deckgl.py
panel/pane/deckgl.py

Fixes https://github.com/holoviz/panel/issues/1380

Support recent versions of DeckGL

---

panel/pane/plot.py

Fixes https://github.com/holoviz/panel/issues/1368

Wrap user Bokeh callbacks to support work in notebooks

---

panel/models/layout.ts

Fix layout caching regression in 0.9.6

---

panel/models/vtk/util.ts
panel/models/vtk/vtkrenderwindowinteractor.ts

[VTK] findPokedRenderer correction

---

panel/command/serve.py

this pull request is related to the issue #1491

static_dirs_fix

---

panel/io/location.py
panel/template/base.py
panel/template/bootstrap/bootstrap.html
panel/template/golden/golden.html
panel/template/material/material.html
panel/template/vanilla/vanilla.html
panel/viewable.py

Includes the `Location` component in all the default templates.

Add support for Location on default templates

---

panel/viewable.py

Recently I introduced the concept of instance hooks which allowed an instance to provide hooks whenever the contents of a layout changed. However I didn't actually commit the change that would execute these hooks.

Execute instance hooks

---

examples/reference/panes/Alert.ipynb
examples/reference/panes/Bokeh.ipynb
examples/reference/panes/ECharts.ipynb
examples/reference/panes/IPyWidget.ipynb
examples/reference/panes/VTK.ipynb
examples/reference/panes/VTKJS.ipynb
examples/reference/panes/Vega.ipynb
examples/reference/widgets/FileDownload.ipynb
examples/reference/widgets/MenuButton.ipynb

Various smaller fixes for the reference gallery.
Fixes https://github.com/holoviz/panel/issues/1511

Updated reference gallery [doc-build]

---

doc/index.rst
examples/user_guide/Links.ipynb
panel/pane/deckgl.py

Fixes https://github.com/holoviz/panel/issues/1537
Fixes https://github.com/holoviz/panel/issues/1380
Fixes https://github.com/holoviz/panel/issues/1279

Various documentation fixes for 0.10.0 (rev1)

---

panel/models/comm_manager.ts

Fixes https://github.com/holoviz/panel/issues/1490

Fix for event ordering in CommManager

---

README.md
doc/index.rst

Adds sponsorship acknowledgements for Anaconda and Blackstone.
@sdc50 Does ERDC want acknowledgement here or is that illegal?

Add sponsors to README and website

---

codecov.yml
setup.py

Fixes https://github.com/holoviz/panel/issues/1604

Skip version check if version is None

---

panel/tests/test_server.py
panel/tests/test_template.py
panel/viewable.py

Fixed session_info update on session_destroy

---

panel/widgets/input.py
panel/widgets/slider.py

Fix https://github.com/holoviz/panel/issues/1257

Initialize value throttled and set to constant

---

panel/command/serve.py
panel/io/resources.py
panel/io/server.py
panel/tests/pane/test_markup.py

Fixes https://github.com/holoviz/panel/issues/1587

Ensure require.js fix works in Django

---

examples/reference/indicators/Dial.ipynb
examples/reference/indicators/Number.ipynb
panel/tests/widgets/test_indicators.py
panel/widgets/indicators.py

As the title says, provides support for formatting NaN values on ValueIndicators.

Support custom formatting for None/NaN values on ValueIndicators

---

panel/template/base.py

fix https://github.com/holoviz/panel/issues/1654

fix nb_template in templates

---

panel/template/golden/golden.css
panel/template/golden/golden.html

Fixes some of the worst issues described in https://github.com/holoviz/panel/pull/1659

Fix issues with GoldenTemplate

---

panel/models/vtk/vtkcolorbar.ts
panel/models/vtk/vtklayout.ts

fix: https://github.com/holoviz/panel/issues/1665

Correction of model compilation error

---

panel/template/bootstrap/dark.css
panel/template/golden/dark.css
panel/template/material/dark.css
panel/template/react/dark.css
panel/template/vanilla/dark.css

Based on this issue https://github.com/holoviz/panel/issues/1686 I've darkened the scrollbars. I made them a little bit wider than in the example such that they are easier to "grap" with the mouse.
I think this can be further improved later. But for me it's a very simple quick win.
Ready for review @philippjfr . Simple change, large gain.

Dark Theme Scrollbar Fixes

---

panel/template/golden/golden.html

Correction resize of Golden Template

---

panel/template/react/react.css
panel/template/react/react.html
panel/tests/template/test_manual.py

The react template was not supporting the `site` and `main_max_width` parameters. I added that and solved some visual issues.
FYI. @philippjfr  and @nghenzi . It's ready for review.

React Template Fixes

---

panel/__init__.py
panel/depends.py
panel/tests/test_depends.py

Implements https://github.com/holoviz/panel/issues/1629

Add pn.bind function to bind parameters to a function

---

panel/widgets/slider.py

Allow setting DiscreteSlider orientation

---

panel/pipeline.py

Fixes https://github.com/holoviz/panel/issues/1701

Initialize pipeline only once

---

examples/user_guide/Customization.ipynb
panel/dist/css/widgets.css

Fixes https://github.com/holoviz/panel/issues/855

Fix widget CSS override example

---

panel/depends.py

The `pn.bind` command introduced in #1702 is only tangentially specific to Panel, and should really be implemented at the Param level. To prepare for eventually deleting the Param-general portion of the implementation, refactored pn.bind into a short Panel-specific pre-processor that just substitutes parameters for widgets, mirroring the pn.depends implementation, and a separate version _param_bind to move to Param. This should help people reason about how pn.bind relates to param.bind, which strictly matches how pn.depends relates to param.depends.
Once this merges I'll make a corresponding PR on param, and then once Panel pins that version of param we can remove _param_bind from this codebase.
This PR also includes extensive updates to the docstrings for both functions, though more are …

Refactored bind for move to param

---

panel/tests/test_docs.py
panel/widgets/input.py

Fixes https://github.com/holoviz/panel/issues/1708

Ensure NumberInput declares available params

---

panel/layout/grid.py
panel/tests/layout/test_grid.py

Fixes https://github.com/holoviz/panel/issues/1721

Fixed bug setting fixed GridSpec ncols and nrows

---

panel/widgets/input.py

Fixes https://github.com/holoviz/panel/issues/1722

Fix None serialization on LiteralInput

---

panel/template/base.py
panel/tests/test_template.py

Fix Template insert order

---

panel/io/location.py
panel/io/server.py
panel/io/state.py

Fixes https://github.com/holoviz/panel/issues/1746

Use document_ready only to avoid double onload execution

---

examples/user_guide/Authentication.ipynb

Closes https://github.com/holoviz/panel/issues/1715

Document OAuth redirect URI

---

README.md
doc/index.rst
panel/config.py
panel/viewable.py

Add docs and functionality to work in various notebook environments

---

panel/models/echarts.ts
panel/models/ipywidget.ts

Fix re-rendering of ECharts and ipywidgets in Card

---

panel/command/serve.py

Fixes https://github.com/holoviz/panel/issues/1762

Add better error for invalid encryption key

---

panel/tests/pane/test_vtk.py
setup.py

pyvista test correction

---

setup.py

fix https://github.com/holoviz/panel/issues/1782

Make non blocking code non windows specific

---

panel/pane/image.py

Fixes image not scaling dynamically 

---

panel/models/echarts.py

Fixes https://github.com/holoviz/panel/issues/1785

Add echarts-gl to ECharts dependencies

---

panel/widgets/select.py

Fixes https://github.com/holoviz/panel/issues/1793

Allow non-string options in Checkbox and CheckButton groups

---

panel/pane/holoviews.py

Fixes https://github.com/holoviz/panel/issues/1732

Fix inverted axes on HoloViews plots

---

doc/user_guide/index.rst
examples/user_guide/Async_and_Concurrency.ipynb
panel/io/__init__.py
panel/io/server.py
panel/reactive.py
panel/tests/test_server.py
panel/widgets/button.py

```python
import asyncio
button = pn.widgets.Button(name='Click to launch')
text = pn.widgets.StaticText()
async def on_click(event):
text.value = f'Running {event.new}' # Indicate task is running
await asyncio.sleep(wait) # Simulate long running IO task
text.value = f'Finished {event.new}!' # Indicate task finished
button.on_click(on_click)
pn.Row(button, text).servable()
```
Depends on https://github.com/holoviz/param/pull/449 and Python 3.8+

Allow using asynchronous callbacks

---

panel/pane/echarts.py

DEPENDS ON https://github.com/holoviz/panel/pull/1875. REVIEW THIS FIRST!
Fix for @nghenzi sunburst problem in https://github.com/holoviz/panel/issues/1876
It works because the sunburst is now displayed and has the right dimensions.
```python
from pyecharts.charts import Sunburst
from pyecharts import options as opts
pn.extension('echarts')
data = [
{
"name": "Flora",
"itemStyle": {"color": "#da0d68"},
"children": [
{"name": "Black Tea", "value": 1, "itemStyle": {"color": "#975e6d"}},
{
"name": "Floral",
"itemStyle": {"color": "#e0719c"},
"children": [
{
"name": "Chamomile",
"value": 1,
"itemStyle": {"color": "#f99e1c"},
},
{"name": "Rose", "value": 1, "itemStyle": {"color": "#ef5a78"}},
{"name": "Jasmine", "value": 1, "itemStyle": {"color": "#f7f1bd"}},
],
},
],
},
{ …
```

Echarts sunburst fix

---

panel/models/tabulator.py
panel/models/tabulator.ts
panel/widgets/tables.py

Ensures that sorting works even when remote pagination is enabled.

Support remote pagination sorting on Tabulator

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

The selection needed to be translated between the original and the sorted paginated views.

Remap Tabulator.selection on sorted paginated views

---

panel/models/card.ts

Fixes https://github.com/holoviz/panel/issues/1833
Fixes https://github.com/holoviz/panel/issues/1884

Do not trigger resize on Card collapse

---

examples/reference/widgets/Button.ipynb
panel/param.py
panel/tests/widgets/test_button.py
panel/widgets/button.py
setup.py

Fixes https://github.com/holoviz/panel/issues/1910

Add Button.value Event parameter

---

panel/tests/widgets/test_slider.py
panel/widgets/base.py
panel/widgets/slider.py

Ensure DiscreteSlider label stays linked

---

panel/template/bootstrap/bootstrap.html
panel/template/bootstrap/dark.css
panel/template/golden/dark.css
panel/template/golden/golden.html
panel/template/material/dark.css
panel/template/material/material.html
panel/template/react/dark.css
panel/template/react/react.html
panel/template/vanilla/dark.css
panel/template/vanilla/vanilla.html

- Fixes https://github.com/holoviz/panel/issues/1856
- Fixes https://github.com/holoviz/panel/issues/1855

Improve dark theme

---

examples/gallery/streaming/hardware_automation.ipynb

Here's a streaming example (as suggested by @MarcSkovMadsen) from my post on [discourse.holoviz](https://discourse.holoviz.org/t/how-to-gui-for-hardware-automation-scientific-instrument-control/1445/3). Please let me know what you think.

added harware_automation.ipynb streaming example

---

.github/workflows/docs.yaml
.github/workflows/test.yaml
examples/reference/panes/ECharts.ipynb
setup.py

Adds `pyechart` example discussed in [this issue](https://github.com/holoviz/panel/issues/1874). 
I suspect this will also need `pyechart` added to the ci environment but I'm not sure where exactly to do that.

Update charts example

---

panel/auth.py

Support for https://auth0.com based authentication

new: Add support for Auth0 authentication

---

panel/io/server.py
panel/tests/io/bk_app.py
panel/tests/io/panel_app.py
panel/tests/test_server.py

Adds the suggested functionality of https://github.com/holoviz/panel/issues/1938

Enables serving files and bokeh apps via `panel.serve`

---

doc/index.rst

Fixes https://github.com/holoviz/panel/issues/1936

Remove reference to Python 2.7

---

panel/interact.py
panel/io/notebook.py
panel/layout/grid.py
panel/pane/ace.py
panel/pane/base.py
panel/pane/deckgl.py
panel/pane/plotly.py
panel/param.py
panel/reactive.py
panel/util.py
panel/widgets/ace.py
panel/widgets/base.py
panel/widgets/button.py
panel/widgets/tables.py

Attempt at https://github.com/holoviz/panel/issues/1943

Factor out SyncableData and ReactiveData base classes

---

panel/layout/base.py
panel/layout/grid.py
panel/layout/tabs.py
panel/pane/base.py
panel/pane/media.py
panel/pane/vtk/vtk.py
panel/param.py
panel/reactive.py
panel/viewable.py
panel/widgets/base.py
panel/widgets/indicators.py

Ongoing effort to bring some consistency to the internal APIs

Cleaned up init_params definitions

---

examples/reference/widgets/FileSelector.ipynb
panel/widgets/file_selector.py

Implements https://github.com/holoviz/panel/issues/1961

Add refresh functionality to FileSelector

---

panel/models/tabulator.py

Fixes https://github.com/holoviz/panel/issues/1890

Avoid reloading tabulator.js and causing require.js errors

---

panel/command/serve.py

Allows executing scripts on startup to ensure the caches are warmed up

Add --warm option to panel serve

---

panel/compiler.py
panel/io/resources.py
panel/models/ace.py
panel/models/deckgl.py
panel/models/echarts.py
panel/models/plotly.py
panel/models/vega.py
panel/models/vtk.py
panel/util.py

Ensures that the model resource mode is handled correctly.

Correctly switch resource mode on models

---

panel/models/vtk/util.ts
panel/pane/vtk/synchronizable_deserializer.py
panel/pane/vtk/synchronizable_serializer.py

fix: https://github.com/holoviz/panel/issues/2001

[VTK] Implement Glyph3Dmapper serialization

---

.github/workflows/build.yaml
.github/workflows/docs.yaml
.github/workflows/test.yaml
panel/package-lock.json
panel/package.json
pyproject.toml
setup.py

Bokeh 2.3 is now released so we should build against it.

Bumped bokeh to released Bokeh 2.3 version

---

panel/layout/accordion.py
panel/layout/card.py
panel/tests/layout/test_accordion.py

Ensure Card.collapsed and Accordion.active parameters are synced

---

panel/models/vtk/vtkaxes.ts
panel/models/vtk/vtklayout.ts

Fixes https://github.com/holoviz/panel/issues/1996
Cc @xavArtley: Was seeing some errors when running the simplest VTKJS examples, e.g. the one linked in #1996

Ensure partially defined VTK axes do not error

---

panel/pane/idom.py

Fixes https://github.com/holoviz/panel/issues/2012

Fix None event on IDOM pane

---

panel/models/file_download.ts

Fixes https://github.com/holoviz/panel/issues/1920

Fix FileDownload button styling

---

panel/depends.py

Fixes https://github.com/holoviz/panel/issues/1999

Adds the watch argument to pn.bind

---

panel/models/echarts.py

Closes https://github.com/holoviz/panel/issues/1883

Bump Echarts version to 5.0.2

---

panel/template/golden/__init__.py
panel/template/golden/golden.html

Fixes https://github.com/holoviz/panel/issues/1984

Disable GoldenTemplate sidebar if empty

---

panel/io/__init__.py
panel/io/django.py
panel/io/server.py

@Hoxbro Could you test this? If you want I'll cut a new RC release.

Patch Bokeh Django server consumers to load resources

---

panel/pane/vtk/synchronizable_serializer.py

fix https://github.com/holoviz/panel/issues/2013
It's not 1-1 with vtk c++ since the implementation in js and c++ are a bit different, however if we follow the declaration of scale and orientation array using names it should works:
```python
import vtk
from vtk.util import numpy_support
pn.extension('vtk')
sphereSource = vtk.vtkSphereSource();
mapper = vtk.vtkGlyph3DMapper();
mapper.SetInputData(sphereSource.GetOutput())
mapper.SetScalarModeToUsePointData()
mapper.SetScaleModeToScaleByMagnitude()
mapper.GetLookupTable().SetRange(10,11)
mapper.SetUseLookupTableScalarRange(True)
sphereSource.Update()
np.random.seed(0)
scalars_array = numpy_support.numpy_to_vtk(np.random.rand(mapper.GetInput().GetPointData().GetNumberOfTuples(),1)+10)
orientation_array = …
```

VTKGlyph3D better scale and orientation management

---

doc/developer_guide/index.rst

added a fix suggestion in the guide to set up a working developer environment.

added nodejs mention in dev guide

---

panel/models/card.ts

Fixes https://github.com/holoviz/panel/issues/1927

Fix Card header_background propagation

---

panel/widgets/input.py

fix https://github.com/holoviz/panel/issues/1848

Add format parameter to DatetimeRangeInput widget

---

panel/models/card.ts
panel/models/idom.ts
panel/tests/template/fast/test_fast_grid_template.py
panel/tests/template/fast/test_fast_list_template.py
panel/widgets/tables.py

A few final fixes before release

Various pre-release cleanup

---

panel/widgets/file_selector.py

Fixes https://github.com/holoviz/panel/issues/2044

Fixed FileSelector file icon on selected files

---

panel/template/base.py

Fix loading of template resources from relative paths

---

panel/dist/css/widgets.css

fix https://github.com/holoviz/panel/issues/2068

fix indicator spinner overflow

---

panel/auth.py

Fixes https://github.com/holoviz/panel/issues/1926

Switch GitHub OAuth to use header authorization token

---

panel/pane/perspective.py
panel/tests/pane/test_perspective.py

Fixes https://github.com/holoviz/panel/issues/2054

Handle integer column names on Perspective widget

---

panel/compiler.py
panel/template/base.py

Fixes two issues with bundling:
1. Bundle resources shared by multiple Templates into baseclass bundle directory
2. Ensure template bundle directories are consistently lowercased 
Fixes https://github.com/holoviz/panel/issues/2074

Fix bundling of template resources

---

examples/reference/widgets/FileSelector.ipynb
panel/widgets/file_selector.py

Closes https://github.com/holoviz/panel/issues/2051

Allow setting root_directory on FileSelector widget

---

panel/pane/idom.py

See https://github.com/idom-team/idom/pull/320 for more context on this change.
Closes: #2058

[WIP] use idom.config to set dist dir

---

examples/reference/widgets/EditableFloatSlider.ipynb
examples/reference/widgets/EditableIntSlider.ipynb
examples/reference/widgets/EditableRangeSlider.ipynb
panel/dist/css/widgets.css
panel/widgets/__init__.py
panel/widgets/input.py
panel/widgets/slider.py

```python
float_slider = pn.widgets.EditableFloatSlider(name='EditableFloatSlider', editable=False) 
int_slider = pn.widgets.EditableIntSlider(name='EditableIntSlider', end=10)
range_slider = pn.widgets.EditableRangeSlider(name='EditableRangeSlider', editable=(False, True))
pn.Column(float_slider, int_slider, range_slider)
```

Add editable sliders

---

panel/dist/css/widgets.css
panel/widgets/slider.py

Fixes syncing of Editable slider value and value_throttled parameters.

Fix syncing of values on Editable Sliders

---

panel/reactive.py
panel/widgets/tables.py

Should never have applied model changes directly. This PR ensures all model changes are correctly scheduled.
Fixes https://github.com/holoviz/panel/issues/2116

Ensure changes on ReactiveData source are scheduled correctly

---

panel/widgets/indicators.py

Fixes https://github.com/holoviz/panel/issues/2146

Fix divide by zero issues on Trend indicator

---

examples/gallery/external/DataTable.ipynb

Updates the example based on user questions https://discourse.holoviz.org/t/adding-buttons-to-panel-datatable/2079
- js and css was updated and extended
- added example with export buttons
https://user-images.githubusercontent.com/42288570/114079747-daf0ab80-98aa-11eb-95a9-54065fb591ec.mp4

Update Datatables Gallery Example

---

panel/param.py

Fixes https://github.com/holoviz/panel/issues/2158

Fix for loading parameter widget linking

---

panel/models/tabulator.ts

- Fixes sorting of unpaginated table
- Fixes data initialization of unpaginated table

Fix Tabulator sorting and data initialization

---

panel/pane/holoviews.py
panel/template/base.py

Fixes https://github.com/holoviz/panel/issues/1816
Fixes https://github.com/holoviz/panel/issues/2207

Fix theming on HoloViews plot updates

---

panel/pane/perspective.py

Fixes https://github.com/holoviz/panel/issues/2193

Fixed data handling on Perspective pane

---

.github/workflows/test.yaml
examples/reference/widgets/DatetimeRangeInput.ipynb
panel/links.py
panel/models/player.ts
panel/pane/idom.py
panel/pane/media.py
panel/pane/plot.py
panel/reactive.py
panel/tests/pane/test_base.py
panel/tests/widgets/test_base.py
panel/widgets/button.py
panel/widgets/indicators.py
panel/widgets/input.py
panel/widgets/select.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/2187
Fixes https://github.com/holoviz/panel/issues/2191
Fixes https://github.com/holoviz/panel/issues/2202
Fixes https://github.com/holoviz/panel/issues/2203

Property control fixes

---

panel/models/plotly.ts
panel/pane/plotly.py

Refactors the Plotly pane a little bit and ensures that JS events trigger updates to plot.
Part of the problem here is that all property updates are handled via the same update path so to avoid running this multiple times the actual rendering is triggered by a change to the `_render_count`. However a user triggering updates manually, e.g. via JS will not know to increment the render count. Therefore we set a timeout that ensures that if `_render_count` hasn't been incremented within 250 ms of the an update to one of the properties then it is incremented automatically.
Fixes https://github.com/holoviz/panel/issues/2239

Refactor handling of Plotly updates

---

panel/param.py

Fixes https://github.com/holoviz/panel/issues/2254

Fix update of Param subobjects

---

panel/models/player.ts
panel/models/plotly.ts
panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/2280

fixed build errors #2280

---

examples/reference/templates/React.ipynb
panel/template/react/__init__.py
panel/template/react/react.html
panel/tests/test_template.py

Added dimensions argument for setting minW, minH, maxW, maxH and preventCollision argument for ReactTemplate.

Add dimensions and prevent_collision to ReactTemplate.

---

panel/pane/holoviews.py

Small fix for compatibility with HoloViews 2.0(dev)

Compatibility with HoloViews 2.0

---

jupyter-config/jupyter_notebook_config.d/panel-client-jupyter.json
panel/io/jupyter_server_extension.py

Can be used with https://github.com/holoviz/pyviz_comms/pull/79 to preview a Panel app on a Jupyter server.

Add panel-preview endpoint for jupyter server extension

---

panel/models/reactive_html.ts

Small fix for DOM nodes with an ID that contains dashes.

Fix issues with ReactiveHTML variable names with dashes

---

panel/models/card.ts

Switch to right-pointing arrow as collapsed indicator on Card

---

setup.py

C.f. https://github.com/bokeh/jupyter_bokeh/issues/131#issue-850942714 is now fixed.

set jupyter_bokeh version to get vs code working

---

panel/template/fast/grid/fast_grid_template.html
panel/template/fast/list/fast_list_template.html

Fixes https://github.com/holoviz/panel/issues/2355

Fix Fast Regression

---

examples/gallery/streaming/streaming_tabulator.ipynb
examples/reference/widgets/Tabulator.ipynb
panel/config.py
panel/models/__init__.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/2284

Lazily load Tabulator widget

---

panel/models/reactive_html.ts

Ensures that ReactiveHTML layout and that of its children is computed correctly.

Improve ReactiveHTML layout calculations

---

panel/reactive.py

Searches the scripts on a ReactiveHTML component for any assignments to the `data` model and ensures these are synced.

Sync ReactiveHTML properties which are assigned to in scripts

---

doc/developer_guide/index.rst
doc/developer_guide/testing.rst

- Fixes formatting
- Updates Travis CI references to GH Actions

Updates and fixes for Developer Guide

---

panel/command/serve.py
panel/config.py
panel/io/server.py

As @MarcSkovMadsen suggested in https://github.com/holoviz/panel/pull/2391

Reuse --index CLI argument to specify default application

---

examples/user_guide/Custom_Components.ipynb
panel/links.py

Allows using `ReactiveHTML.jslink` and `ReactiveHTML.jscallback`.

Add ability to link ReactiveHTML parameters as source

---

jupyter-config/jupyter_notebook_config.d/panel-client-jupyter.json

Fix trailing comma in jupyter notebook config

---

examples/reference/widgets/Tabulator.ipynb

Added some basic information for the configuration parameter for the tabulator widget as described in  #2408

Docs for configuration parameter of tabulator widget

---

panel/io/server.py

Fixes a regression introduced when adding support for serving an application at the root.

Fix serving of index template

---

panel/reactive.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/2430

Fix bug sorting and validating on Tabulator

---

panel/reactive.py

Reactive.add_periodic_callback was removed in favor of pn.state.add_periodic_callback

Remove add_periodic_callback method

---

examples/user_guide/Customization.ipynb
panel/tests/test_reactive.py
panel/viewable.py
panel/widgets/base.py

https://github.com/holoviz/panel/issues/2422

Add visible parameter to all components

---

panel/dist/css/widgets.css

Fixes https://github.com/holoviz/panel/issues/1061

Ensure JSON pane string wraps

---

panel/models/plotly.py
panel/models/plotly.ts
panel/pane/plotly.py

Fixes https://github.com/holoviz/panel/issues/1291

Send Plotly restyle and relayout events

---

examples/reference/widgets/DatePicker.ipynb

Fixes https://github.com/holoviz/panel/issues/1809

Document DatePicker start and end parameters

---

examples/reference/layouts/Tabs.ipynb

Fixes https://github.com/holoviz/panel/issues/1387

Fixed Tabs documentation

---

panel/widgets/ace.py

Fixes https://github.com/holoviz/panel/issues/1808

Fix Ace widget disabled parameter

---

examples/user_guide/Components.ipynb

Fixes https://github.com/holoviz/panel/issues/2178

Add documentation about parameterized components

---

panel/tests/widgets/test_tables.py
panel/util.py
panel/widgets/tables.py

Avoids issues with models being used multiple times
Fixes https://github.com/holoviz/panel/issues/2307

Clone table formatters and editors

---

panel/widgets/slider.py

Can make some filtering operations easier.

Add separate RangeSlider value_start and value_end parameters

---

panel/auth.py

Fixes https://github.com/holoviz/panel/issues/2458

Allow unicode auth response body

---

panel/io/save.py

Fixes https://github.com/holoviz/panel/issues/2460

Allow saving Templates

---

panel/pane/plotly.py

Workaround TypeError for non-string json keys

---

panel/template/bootstrap/bootstrap.css

Fixes https://github.com/holoviz/panel/issues/2446

Ensure BootstrapTemplate sidebar collapses completely

---

panel/template/fast/grid/fast_grid_template.html
panel/template/fast/list/fast_list_template.html

Fixes https://github.com/holoviz/panel/issues/2184

Fixed issues with Fast template logo alignment

---

panel/param.py

Fixes https://github.com/holoviz/panel/issues/2389

Fix issue with throttled updates on Param

---

panel/io/resources.py
panel/io/save.py
panel/models/perspective.py
panel/models/tabulator.py
panel/models/tabulator.ts
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/2285

Bundle Tabulator and Perspective resources

---

binder/requirements.txt
doc/_templates/layout.html

Fixes https://github.com/holoviz/panel/issues/1500

Binder fixes

---

panel/tests/widgets/test_terminal.py
setup.py

There have been a few flakey tests lately.

Fix unit tests

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/2185

Reset Tabulator style after applying it

---

panel/models/trend.ts

Fixes https://github.com/holoviz/panel/issues/2229

Wrap Trend title

---

panel/io/save.py
panel/package-lock.json
panel/package.json

Fixes regression in save when bokeh Resources instance is provided.

Save resource mode fix

---

panel/layout/flexbox.html

Fixes https://github.com/holoviz/panel/issues/2494

Fix wrapping on FlexBox in column mode

---

panel/depends.py

Fixes https://github.com/holoviz/panel/issues/2409

Fix chained bind

---

panel/_templates/doc_nb_js.js

Some of the larger dependencies sometimes timeout with the 10ms x 100 attempts (i.e. 1s) timeout, so I've increased it to 25 ms x 200 attempts (i.e. 5 seconds).

Increase notebook resource load timeout

---

panel/pane/perspective.py

Type declarations were wrong in some cases.

Fix Perspective for string types

---

examples/user_guide/Custom_Components.ipynb
panel/models/reactive_html.ts

Closes https://github.com/holoviz/panel/issues/2519

Add ReactiveHTML remove script

---

panel/models/card.ts

Fixes https://github.com/holoviz/panel/issues/2497

Offset Card collapse symbol in header

---

.github/workflows/test.yaml

Update build matrix

---

panel/_templates/autoload_panel_js.js
panel/compiler.py
panel/config.py
panel/io/notebook.py
panel/layout/gridstack.py
panel/models/echarts.py
panel/models/terminal.py
panel/models/terminal.ts
panel/models/vega.py

* Ensures ReactiveHTML requirejs definitions are handled
* Declares a single requirejs config
* Fixes Terminal requirejs definition
* Adds GridStack requirejs definition

Improved requirejs handling

---

examples/gallery/components/MaterialUI.ipynb

Fix https://github.com/holoviz/panel/issues/2547

Fix MaterialUI example

---

panel/widgets/indicators.py

Fix bug updating Tqdm indicator

---

examples/reference/templates/FastGridTemplate.ipynb
examples/reference/templates/FastListTemplate.ipynb

Fix #2560 theme_toggle

---

panel/io/reload.py

Fixes https://github.com/holoviz/panel/issues/2570

Ensure autoreload doesn't error on cleaned up session

---

doc/_templates/layout.html

Fixes https://github.com/holoviz/panel/pull/2474/files

Fix binder links on website

---

pyproject.toml
setup.py

Fixes https://github.com/holoviz/panel/issues/2595

Pin version of tqdm with asyncio support

---

panel/command/serve.py
panel/io/callbacks.py
panel/io/server.py
panel/io/state.py

Cleans up sessions after initializing them in `panel serve` command when `--warm` or `--autoreload` is provided.

Cleanup sessions after warmup

---

panel/io/callbacks.py

Fixes #2612
https://user-images.githubusercontent.com/42288570/128125787-d3b8987c-1e30-4eb1-a8fc-e416ab777f81.mp4

fix no attribute stop #2612

---

examples/gallery/external/Folium.ipynb
panel/pane/plot.py

Fixes https://github.com/holoviz/panel/issues/2231
ps. I removed the `.embed()` line of code in the second last cell of the Notebook example because the slider in the app when `panel serve`d did not work (did not react). I guess this is a bug.

Make Folium height responsive

---

panel/template/fast/css/fast_bokeh.css

@MarcSkovMadsen Could you test this a bit. Fixing the line-height like this seems like an exceptionally bad idea but we have to see if this causes issues.
Fixes #2600

Do not fix line-height in Fast template

---

MANIFEST.in
panel/tests/pane/test_base.py
panel/tests/pane/test_plotly.py

Ensures that all the tests pass in a packaged version of Panel.

Ensure tests pass in packaged version

---

examples/user_guide/Deploy_and_Export.ipynb

Trying to understand the various parameters of the server, there are several functionalities that are in the code and not made explicit in the documentation. I do not know if this is the correct way to correct them, since the control of changes in github makes many differences to me.

Added on_session_destroyed callback to the docs

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/2638

Ensure sorters are applied correctly after updating Tabulator value

---

panel/config.py
panel/io/__init__.py
panel/io/admin.py
panel/io/callbacks.py
panel/io/logging.py
panel/io/profile.py
panel/io/server.py
panel/io/state.py
panel/reactive.py

Add timeline view to admin dashboard

---

panel/models/trend.ts

Fixes https://github.com/holoviz/panel/issues/2652

Ensure Trend indicator can be rendered in layout

---

examples/reference/indicators/Progress.ipynb
panel/models/progress.ts
panel/models/widgets.py
panel/tests/widgets/test_misc.py
panel/widgets/indicators.py

Fixes https://github.com/holoviz/panel/issues/2685

Make progress indicator more consistent

---

README.md
doc/_templates/layout.html
doc/conf.py

Supersedes https://github.com/holoviz/panel/pull/2703

Switch binder links to latest version

---

pyproject.toml

As I just did on the 0.12 version.

Update pyproject.toml for bokeh 2.4

---

panel/command/serve.py
panel/tests/command/test_serve.py
panel/tests/conftest.py

Fixes https://github.com/holoviz/panel/issues/2755

Ensure cleanup happens when enabling --warm or --autoreload with Bokeh 2.4

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

It was just using default values and ignoring the kwargs. Added two simple tests too.

Tabulator download_menu() applies kwargs for the TextInput

---

panel/pane/deckgl.py
panel/pane/echarts.py
panel/pane/equation.py
panel/pane/perspective.py
panel/pane/plotly.py
panel/pane/vega.py
panel/pane/vtk/vtk.py
panel/util.py
panel/widgets/ace.py
panel/widgets/tables.py
panel/widgets/terminal.py

Fixes https://github.com/holoviz/panel/issues/2765

Warn users if extension is not loaded before server page is rendered

---

panel/io/callbacks.py

Fixes https://github.com/holoviz/panel/issues/2764

Fixes for PeriodicCallback

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/2770

Ensure Tabulator style is not lost during rerender

---

panel/tests/test_param.py
panel/widgets/input.py

Add start and end parameters to the base NumericInput class

---

panel/io/server.py
panel/io/state.py
panel/tests/test_server.py

Fixes https://github.com/holoviz/panel/issues/2727

Ensure autoload.js correctly determines state.rel_path

---

examples/gallery/components/MaterialUI.ipynb

Fixes https://github.com/holoviz/panel/issues/2680

Drop MaterialSwitch from example

---

panel/pane/plotly.py
panel/tests/pane/test_plotly.py

Fixes https://github.com/holoviz/panel/issues/2747

Ensure updated Plotly model does not error in Tabs

---

panel/models/reactive_html.ts
panel/reactive.py

Fixes https://github.com/holoviz/panel/issues/2743

Do not sync Viewable types with ReactiveHTML data model

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/2730

Fix HTMLTemplateFormatter on Tabulator

---

panel/widgets/tables.py

Fixed tabulator remote pagination bug.

---

panel/command/__init__.py

Successfully exit after pyct command is executed

---

panel/models/plotly.py
panel/template/bootstrap/__init__.py
panel/template/golden/__init__.py

Fixes https://github.com/holoviz/panel/issues/2860

Update jQuery to remediate CVEs

---

panel/widgets/indicators.py

Fixes https://github.com/holoviz/panel/issues/2879

Do not sync Indicator properties from frontend

---

panel/reactive.py

Fixes https://github.com/holoviz/panel/issues/2855

Fix roundtrip of datetimes on ReactiveData objects

---

panel/reactive.py

All model updates on the server must be recorded in a component's `_changing` dictionary to ensure that we can avoid them from boomeranging. The patch and stream events were not handled like this which was particularly egregious because the boomeranged event could in fact reset the data source to its original value.

Ensure stream and patch events do not boomerang

---

panel/io/state.py

The admin launch profiler will now also show `on_load` callbacks.

Add on_load callback profiling

---

panel/dist/css/card.css
panel/template/material/material.css

Card header CSS continues to be a total nightmare.

Further fixes for Card header alignments

---

panel/models/comm_manager.ts
panel/models/tabulator.ts
panel/reactive.py
panel/tests/widgets/test_tables.py
panel/widgets/tables.py
panel/widgets/terminal.py

Fixes https://github.com/holoviz/panel/issues/2907
Fixes https://github.com/holoviz/panel/issues/2908

Fix various Tabulator regressions

---

panel/models/vega.ts

Fixes https://github.com/holoviz/panel/issues/2930

Fix Vega pane sizing issues

---

panel/layout/accordion.py
panel/tests/layout/test_accordion.py

Fixes https://github.com/holoviz/panel/issues/2932

Ensure toggled Accordion only triggers one event on change of active Card

---

panel/widgets/input.py

Fixes https://github.com/holoviz/panel/issues/2928

Fix target transform on LiteralInput

---

panel/reactive.py

Fixes https://github.com/holoviz/panel/issues/2937

Fix issue in detecting script data assignment

---

panel/pane/image.py
panel/tests/pane/test_image.py

Since we can validate the struct of an image there's no reason not to support this.

Support bytes on Image

---

examples/reference/widgets/Player.ipynb
panel/widgets/player.py

Exposing the direction parameter. xref https://discourse.holoviz.org/t/state-of-player-widget/3133

Added direction to player

---

panel/models/location.ts

Previously the URL hash was only updated on initialization but the hash can change interactively all the time.

Sync URL location hash interactively

---

panel/reactive.py
panel/tests/test_reactive.py

Fix cleanup of children on ReactiveHTML

---

examples/reference/widgets/DiscretePlayer.ipynb
examples/reference/widgets/Player.ipynb
panel/models/player.ts
panel/widgets/player.py

Since we also recently exposed the `direction` property I thought we might as well make it settable.
https://github.com/holoviz/panel/issues/583

Add programmatic control over Player widget

---

panel/tests/widgets/test_select.py
panel/widgets/select.py

Update ButtonGroup value when changing options 

---

examples/reference/panes/Vega.ipynb

Addresses https://github.com/holoviz/panel/issues/3034

mentions vega does not support responsive

---

panel/tests/widgets/test_indicators.py
panel/widgets/indicators.py

Fixes #3039 discussed here https://discourse.holoviz.org/t/tdqm-text-color-change/3193

fixes #3039: tqdm style color reset

---

panel/template/base.py

fix: use provided theme.css

---

panel/io/server.py

Fix .app method

---

panel/models/tabulator.py
panel/models/tabulator.ts

Updates to Tabulator 5.0.10 and avoids re-rendering multiple times when setting frozen columns and on pagination.

Optimizations and updates for Tabulator

---

panel/models/tabulator.ts

Workaround for https://github.com/olifolkerd/tabulator/issues/3530 which caused performance regressions. We disable `frozenColumns` on the `dataLoading` event and re-enable it after the table has been rendered.

Tabulator frozen column optimization

---

setup.py

Partial fix to https://github.com/holoviz/panel/issues/3073

Pin pyvista to <0.33

---

panel/models/tabulator.ts

Ensures that Tabulator components are appropriate resized after initial render and when expanded children are rendered.

Fix Tabulator layout of expanded children

---

panel/io/server.py

In the process of bypassing the document lock we may come up with events which cannot bypass the lock. In these scenarios we need to catch the resulting `RuntimeError` and schedule these events to be triggered in the next event loop where they will be able to obtain the required lock on the Document.

Ensure unlocked decorator dispatches pending_writes

---

panel/io/server.py
panel/io/state.py
panel/reactive.py

Fixes https://github.com/holoviz/panel/issues/3113

Avoid sending messages on closed or closing Websocket

---

panel/io/server.py

Introduced some issues in https://github.com/holoviz/panel/commit/9c543707ec194dc86c3e757698d89f202fa5ae28

Fix dispatch on error in unlocked context

---

panel/models/tabulator.ts

Ensure we redraw on initial render whatever happens.

Fix Tabulator layout

---

panel/models/event-to-object.ts

Syncs with the latest version of event-to-object from IDOM.

Update event to object

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/2770

Do not reset styles on Tabulator re-render

---

examples/reference/panes/DeckGL.ipynb
panel/models/deckgl.py
panel/models/deckgl.ts
panel/pane/deckgl.py

Fixes https://github.com/holoviz/panel/issues/3031
Fixes https://github.com/holoviz/panel/issues/3145
Fixes https://github.com/holoviz/panel/issues/3130
Fixes https://github.com/holoviz/panel/issues/3015
Fixes https://github.com/holoviz/panel/issues/3144

Update and improve DeckGL pane

---

examples/user_guide/Performance_and_Debugging.ipynb

Fixes https://github.com/holoviz/panel/issues/1012

Add layouts + throttling sections to Peformance docs

---

panel/widgets/indicators.py

Fixes #3143
https://user-images.githubusercontent.com/19758978/153645865-8044610f-73aa-457a-b2c9-7e5202e9963c.mp4
https://user-images.githubusercontent.com/19758978/153645878-fa1ef3ef-d020-4a0d-b9f5-ce4a9edb8954.mp4

BooleanStatus and LoadingSpinner now updates when changing color

---

panel/widgets/tables.py

Copies the default alignment for different types from Excel.  
Fixes https://github.com/holoviz/panel/issues/3186

Set default alignment for Tabulator

---

examples/getting_started/Introduction.ipynb

Close https://github.com/holoviz/panel/issues/3230

Provide url for occupancy.csv

---

panel/io/__init__.py
panel/io/document.py
panel/io/profile.py

Fixes some issues introduced in #3252

Pyodide compatibility followup

---

panel/io/resources.py

Fixes https://github.com/holoviz/panel/issues/3257

Fix jinja2 imports

---

.github/workflows/test.yaml
pyproject.toml
setup.py

pyctdev has issues with setuptools >=61

Pin setuptools

---

.github/workflows/build.yaml
.github/workflows/docs.yaml
.github/workflows/test.yaml
CHANGELOG.md
doc/FAQ.rst
doc/getting_started/index.rst
doc/releases.md
panel/io/ipywidget.py
panel/io/jupyter_server_extension.py
panel/io/resources.py
panel/package-lock.json
panel/package.json
panel/tests/pane/test_image.py
pyproject.toml
setup.py

Minor updates backported to the 0.12 branch, mainly to fix compatibility with jinja2 3.1.0.

Branch 0.12.7

---

.github/workflows/docs.yaml
doc/conf.py
setup.py

The main goal of this PR is to fix the docs build that is currently broken and prevented the site update after the release of 0.12.7. This may take a few iterations.

Various updates to the docs and its build

---

.github/workflows/docs.yaml
doc/conf.py

Fix the docs build

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/3256, https://github.com/holoviz/panel/issues/3248

Handle sorters and filters correctly when patching Tabulator

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/3249

Restore scroll position after patch

---

panel/tests/io/test_embed.py
panel/widgets/slider.py

Fixes https://github.com/holoviz/panel/issues/3275 and https://github.com/holoviz/panel/issues/2709

Ensure DiscreteSlider label is updated

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/3271

Restore Tabulator sorters on re-render

---

panel/io/django.py

Fixes https://github.com/holoviz/panel/issues/3246

Fix Django DocConsumer

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/3285

Ensure Tabulator selection is not reset on patch

---

panel/template/base.py
panel/tests/test_reactive.py
panel/tests/test_template.py
panel/viewable.py

Fixes https://github.com/holoviz/panel/issues/3049

Consistent handling of page title

---

panel/io/server.py

Fixes https://github.com/holoviz/panel/issues/2629

Fix handling of oauth_provider argument to panel.io.server.serve

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/2946

Implement keywords filter for Tabulator

---

panel/widgets/input.py

Fixes https://github.com/holoviz/panel/issues/2176

Add support for multiple files in FileInput.save

---

panel/widgets/indicators.py

Fixes https://github.com/holoviz/panel/issues/3166

Ensure Progress default value is -1

---

panel/io/datamodel.py
panel/links.py
panel/pane/holoviews.py
panel/reactive.py
panel/tests/test_links.py

Fixes https://github.com/holoviz/panel/issues/603

Fixes for jslinking HoloViews components

---

binder/apt.txt
binder/requirements.txt
setup.py

Fix some issues related to graphviz installation on binder.

Fix binder deployment on master

---

panel/models/vega.py

Update Vega-lite version

---

.github/workflows/test.yaml
pyproject.toml
setup.py
tox.ini

The pin was only a temporary measure.

Remove setuptools upper bound

---

panel/io/resources.py
panel/io/server.py
panel/template/base.py

Minor followup on some of the resource handling PRs.

Ensure resource handling recognizes pathlib objects

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/3315

Allow sorting on unnamed index in Tabulator

---

panel/models/tabulator.ts

In certain cases renderComplete could end up not being called at all causing a semi-initialized table to be rendered. This PR adds a timeout event that ensures it is called eventually if the internal tabulator machinery does not invoke it.

Ensure Tabulator renderComplete is called

---

panel/reactive.py

Fixes https://github.com/holoviz/panel/issues/3331

Ensure bokeh events set busy indicator

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/3315

Fix Tabulator sorting on columns with non-string names

---

panel/template/base.py

Fixes https://github.com/holoviz/panel/issues/3340

Fix Template JS and CSS resources

---

panel/io/server.py

Reference https://github.com/bokeh/bokeh/issues/12018 and https://github.com/tornadoweb/tornado/issues/2608

Patch asyncio event loop policy on windows

---

panel/io/__init__.py
panel/io/pyodide.py

- Switch to CDN resources
- Isolate each displayed model
- Support syncing array buffers

Improvements to pyodide support

---

examples/reference/panes/Vega.ipynb

This handles both `None` and an empty dict which is what is returned after selecting and then unselecting

Handle empty vega selections

---

panel/widgets/file_selector.py

Makes it so much easier to use in an IDE like VS Code

Add docstrings to FileSelector

---

panel/widgets/ace.py

Makes it much easier to use in an IDE like VS Code

Adds docstrings to Ace Editor

---

panel/pane/__init__.py

Makes it easier to get started and navigate in an IDE like VS Code.

Update docstring of pane module

---

examples/reference/panes/Audio.ipynb
examples/reference/panes/DataFrame.ipynb
examples/reference/panes/JSON.ipynb
panel/pane/alert.py
panel/pane/deckgl.py
panel/pane/echarts.py
panel/pane/equation.py
panel/pane/holoviews.py
panel/pane/idom.py
panel/pane/image.py
panel/pane/ipywidget.py
panel/pane/markup.py
panel/pane/media.py
panel/pane/perspective.py
panel/pane/plot.py
panel/pane/plotly.py
panel/pane/streamz.py
panel/pane/vega.py
panel/pane/vtk/vtk.py

Adds docstrings to panes to make the life of developers using an IDE much easier :-)

add docstrings to panes

---

panel/io/callbacks.py

The Tornado event loop and the bokeh server APIs are not accessible in pyodide so we have to schedule manually on the asyncio loop running inside pyodide.

Add support for periodic callbacks in Pyodide

---

panel/models/tabulator.ts
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/3382

Update the style after an edit event

---

panel/widgets/slider.py

Fixes https://github.com/holoviz/panel/issues/3371

Fix EditableSlider updates when no value_throttled is set

---

examples/gallery/viz/GraphViz.ipynb
examples/gallery/viz/NetworkX.ipynb
examples/reference/indicators/LinearGauge.ipynb
examples/reference/panes/Audio.ipynb
examples/reference/panes/DataFrame.ipynb
examples/reference/panes/JSON.ipynb
examples/reference/widgets/ColorPicker.ipynb
examples/reference/widgets/DatetimePicker.ipynb
examples/reference/widgets/DatetimeRangeInput.ipynb
examples/reference/widgets/Debugger.ipynb
examples/reference/widgets/IntInput.ipynb
examples/reference/widgets/JSONEditor.ipynb
examples/reference/widgets/PasswordInput.ipynb
examples/reference/widgets/Tabulator.ipynb
examples/reference/widgets/TextAreaInput.ipynb
examples/reference/widgets/TextInput.ipynb
examples/reference/widgets/TextToSpeech.ipynb
examples/user_guide/Django_Apps.ipynb
examples/user_guide/FastApi_Apps.ipynb
examples/user_guide/Param.ipynb
examples/user_guide/Server_Deployment.ipynb
examples/user_guide/Templates.ipynb
panel/io/admin.py
panel/io/state.py
panel/widgets/tables.py

Cleanup and fixes

---

.github/workflows/docs.yaml
examples/reference/panes/IDOM.ipynb

Note that we currently only support idom==0.24.

Add warning about IDOM version support

---

examples/reference/layouts/GridBox.ipynb
panel/layout/__init__.py
panel/layout/accordion.py
panel/layout/base.py
panel/layout/card.py
panel/layout/flex.py
panel/layout/grid.py
panel/layout/gridstack.py
panel/layout/spacer.py
panel/layout/tabs.py

Adds docstrings to layouts to make them easier to use in Jupyter and IDEs

Adds docstrings to layouts

---

panel/io/state.py
panel/template/base.py
panel/tests/template/test_base.py

Fixes https://github.com/holoviz/panel/issues/3445

Improve handling of notifications on template

---

panel/compiler.py
panel/models/json_editor.py
panel/template/fast/css/fast_bokeh.css

Fixes https://github.com/holoviz/panel/issues/3428

Improve resources bundling for JSONEditor

---

panel/template/fast/css/fast_bokeh.css

Fix Fast button color

---

panel/config.py
panel/depends.py
panel/io/notebook.py
panel/io/server.py
panel/pane/base.py
panel/widgets/indicators.py

Various docstrings improvements

Improve docstrings

---

panel/models/plotly.py
panel/models/plotly.ts
panel/pane/plotly.py

Fixes https://github.com/holoviz/panel/issues/3448

Add support for Plotly animation frames

---

panel/template/fast/css/fast_bokeh.css
panel/template/fast/css/fast_panel_widgets.css
panel/template/fast/grid/fast_grid_template.html
panel/template/fast/list/fast_list_template.html

Fixes https://github.com/holoviz/panel/issues/3426
Fixes https://github.com/holoviz/panel/issues/3430
Fixes https://github.com/holoviz/panel/issues/3437

Fast css fixes

---

README.md
doc/getting_started/index.rst

Fixes https://github.com/holoviz/panel/issues/3421

Update README and getting started

---

panel/tests/widgets/test_tables.py
panel/widgets/tables.py

Fixes https://github.com/holoviz/panel/issues/3410

Fix remote pagination on_click event row

---

panel/models/tabulator.ts

Fixes https://github.com/holoviz/panel/issues/3472

Skip Tabulator row selection when clicking on expand button

---

panel/io/__init__.py

Catch failing import if newer version of django or channels is installed

---

doc/conf.py

Fixes https://github.com/holoviz/panel/issues/3490

Improve reference gallery component titles

---

panel/_templates/base.html
panel/io/document.py
panel/io/pyodide.py
panel/io/resources.py
panel/io/state.py
panel/template/base.py
panel/viewable.py

Fixes https://github.com/holoviz/panel/issues/3480

Clean up pyodide API

---

panel/reactive.py

Fixes #3512 
The `DatePicker` widget has in Panel a `param.CalendarDate` Parameter that allows None, however in the Bokeh model the `Date` property isn't `Nullable` (which I imagine could be improved). When a Panel `DatePicker` is instantiated without defining `value`, and then `value` is set to a date, the Bokeh model doesn't have `value` yet defined, which causes the error reported in the issue. The suggested change catches the error raised by Bokeh and assumes the property is effectively going to change, since it was not set at all.

Don't try to get an Undefined bokeh property

---

panel/widgets/slider.py

Follow-up of https://github.com/holoviz/panel/pull/3515

DateRangeSlider: value_throttled is also a DateRange Parameter

---

panel/pane/base.py
panel/tests/layout/test_tabs.py

Fixes https://github.com/holoviz/panel/issues/3518

Ensure non-updateable Pane can be updated inside Tabs

---

panel/io/server.py

Attempt at fixing https://github.com/holoviz/panel/issues/3531

Do not switch asyncio loop in Jupyter

---

panel/io/server.py

Fixes https://github.com/holoviz/panel/issues/3531

Do not patch event loop on jupyter_server on windows

---

panel/models/tabulator.ts

Fixes regression introduced by https://github.com/holoviz/panel/pull/3536

Restore update_layout call in Tabulator

---

doc/_templates/sidebar-nav-bs.html
doc/conf.py
doc/developer_guide/index.rst
doc/generate_modules.py
doc/user_guide/index.rst

Add two-level sidebar toctree

---

panel/widgets/player.py

docstrings - interval is specified in ms

---

panel/pane/base.py

`self.warning` to `self.param.warning`.

Small change for compatibility with param 2.0

---

panel/pane/plot.py

Fix Matplotlib.high_dpi issue

---

panel/io/save.py
panel/io/state.py
panel/reactive.py
panel/viewable.py

- Add `ClassVar` where appropriate
- Remove quoting where not needed

Clean up existing type definitions

---

.github/workflows/test.yaml
panel/tests/conftest.py
panel/tests/test_server.py
panel/tests/ui/io/test_state.py
panel/tests/ui/pane/test_markup.py
panel/tests/ui/widgets/test_button.py
panel/tests/widgets/test_tables.py
setup.py
tox.ini

Sets up infrastructure to run UI testing based on [playwright](https://playwright.dev/python/).

Add UI testing based on playwright

---

panel/models/layout.ts
panel/models/tabulator.ts
panel/tests/ui/test_reactive.py

Changes the `PanelHTMLBoxView` to avoid re-rendering when either the `background` or the `loading` parameter changes.

Ensure components do not re-render if background or loading parameters change

---

panel/template/base.py
panel/tests/conftest.py
panel/tests/io/test_reload.py
panel/tests/pane/test_deckgl.py
panel/tests/ui/template/test_fastlisttemplate.py
panel/util.py

Fixes https://github.com/holoviz/panel/issues/3606

Ensure templates resolve resources correctly

---

panel/template/fast/grid/fast_grid_template.css

Fixes https://github.com/holoviz/panel/issues/3614.
I've not been able to test it yet. Waiting for the fix https://github.com/holoviz/panel/pull/3611 to be merged.

fix fastgridtemplate sidebar height

---

panel/models/html.ts
panel/tests/ui/pane/test_markup.py

Fixes https://github.com/holoviz/panel/issues/3609

Invalidate layout on HTML re-rerender

---

panel/io/pyodide.py
panel/viewable.py

Allows `_repr_mimebundle_` to work in pyscript.

Implement repr for pyodide/pyscript

---

panel/command/serve.py

The correct subcommand is oauth-secret

Fix help text

---

panel/tests/ui/widgets/test_tabulator.py

This is an expected failing test for https://github.com/holoviz/panel/issues/3695

Add a test triggering a Tabulator value update

---

doc/developer_guide/index.md
examples/developer_guide/Developing_Custom_Models.ipynb

You can access the webpage if you know it exists: https://panel.holoviz.org/developer_guide/DevelopingCustomModels.html
Will look like this:

Added Developing Custom Models to the table of contents

---

panel/tests/ui/widgets/test_input.py

Adding UI tests to panel.widgets.DatetimePicker. The newly added tests check if DatetimePicker perform correctly with different parameter settings at initialization.

Add UI tests to DatetimePicker

---

.github/workflows/test.yaml
doc/developer_guide/testing.md
panel/tests/test_depends.py
panel/tests/ui/template/test_fastlisttemplate.py
panel/tests/ui/widgets/test_tabulator.py
setup.py

There are a few flaky tests in the test suite, attempting to fix those in this PR.

Fix flaky tests

---

.github/workflows/test.yaml

As title says, switches to the [holoviz_tasks/install](https://github.com/pyviz-dev/holoviz_tasks/tree/main/install) action which standardizes environment setup across our projects.

Switch to pyviz-dev/holoviz_task install action

---

panel/param.py
panel/tests/test_param.py

Fixes https://github.com/holoviz/panel/issues/3723

Allow overriding all widget parameters on Param pane

---

panel/dist/css/markdown.css

Fixes https://github.com/holoviz/panel/issues/1751

Improve Markdown code syntax highlighting

---

.github/workflows/test.yaml
panel/config.py
panel/io/jupyter_server_extension.py
panel/tests/conftest.py
panel/tests/ui/io/test_jupyter_server_extension.py
panel/tests/ui/jupyter_server_test_config.py
setup.cfg
setup.py
tox.ini

Launches jupyter separately in CI and sets up fixture to launch automatically just once if  pytest`--jupyter` option is enabled.

Attempts at making jupyter tests more robust
